### ISSUE TITLE
Best practice for replication?

### ISSUE THREAD

**Issue by mikeyboybs** [ValveSoftware/steamvr_unreal_plugin#10]
Hello, 

I was wondering what the best practice for replication would be. 

Currently I am using event tick and the get finger curls and splays node to get a float value of the finger curls. Then using switch has authority(authority) I set a replicated variable and on Remote I fire a custom event that executes on the server and sets the replicated variable. 

When I run this code without using the finger curls and splays node (e.g. I use a keyboard button to set the float), I get good replication between clients and servers. Everyone does and sees what they are supposed to.

When I run this code with fingers and splays, the client can see the server finger animation but does not see the animation update on their own fingers, on the server side, the server can see their own finger animation, and can see the client move their fingers, but the animation is jittery as if it's fighting between two differing variables. 

I'm still learning replication so I might be missing something but since behavior is different between a standard action mapping and the node, I thought I would reach out. 

If anyone knows best practice for this I would really appreciate it, or if replication isn't supported I can continue with other parts of my project and come back to this when it's ready. 

I can provide screenshots if I'm not being clear. 

Thank you.

**Comment by mikeyboybs** [comment]
Update:
Ok. I've gotten finger positions replicating except that the client seems to definitely be trading variable values from both server and client. When I close my fist on the client, it only represents the intended behavior every other frame (flickering between server and client finger positions). When I close my fist on both the server and client at the same time (by holding the controllers in each of my hands), the flickering reduces only because I'm making the same motions on each player. Here is my code. When I find a solution I'll post it here as well. I fully admit this is probably more me than the plugin.

![FingerPositions](https://user-images.githubusercontent.com/20828914/56441130-48176a80-62a9-11e9-84d9-49f3de3cd7ab.PNG)

**Comment by 1runeberg** [comment]
@mikeyboybs - what's driving your animations?

**Comment by mikeyboybs** [comment]
Hi 1runeberg. Sorry for the late reply. Here is my resolution, but I would love to know if there is a better way. This works with two players, but needs more testing for multiple players. 

I think the problem is that the authority's finger inputs are somehow translated to all the other pawns in a scene. I don't think this is a replication issue. The finger curl and splay inputs are somehow globally connected. I had to perform a manual check to exclude inputs coming from the server on my client pawns. 

I've attached my anim graph as well. It's nothing special. Just a grab animation blended per bone. It's not perfect, but good for the time being.

![anim](https://user-images.githubusercontent.com/20828914/56850633-6ccf9b80-68c2-11e9-9bb4-18ea9fd852f0.PNG)
![fingerresolution](https://user-images.githubusercontent.com/20828914/56850627-4c9fdc80-68c2-11e9-8b06-462b22e87790.PNG)

**Comment by 1runeberg** [comment]
Hi @mikeyboybs - The "Get Curls and Splays" is always local so you have to ensure your anims are run from values from the correct Player State. 

Have you had a chance to read through Cedric's (@exifrexi) Network Compendium, might be helpful to have a look at the PlayerState section there if you haven't already :)

http://cedric-neukirchen.net/2017/02/14/multiplayer-network-compendium/

**Comment by mikeyboybs** [comment]
Thanks! I'll give it a read.

**Comment by mikeyboybs** [comment]
Hi @1runeberg,

Ok, after taking a look. Here's what I "think" I know. 

According to the compendium, the player state is a great place to keep finger curl values because each client has a player state and each player state is replicated to all other clients. Sounds reasonable, so I whip up a player state blueprint and script the following:

![SOplayerstate](https://user-images.githubusercontent.com/20828914/56967389-50c83600-6b1e-11e9-9a0c-2f2cc177cf5c.PNG)

Now I'm going to drive my animation so I get a reference to controller 0's player state in my anim and use the values to push variables within the AnimGraph. I do this because every client considers themselves controller 0 in their own instance. This is how I'm interpreting your advise to ensure anims are run from the correct player state. 

![AnimEG](https://user-images.githubusercontent.com/20828914/56967529-9a188580-6b1e-11e9-8eb0-a6b1797747d4.PNG)

![image](https://user-images.githubusercontent.com/20828914/56967560-adc3ec00-6b1e-11e9-8b10-9a70ae3b8f0f.png)

This works in single player quite nicely. When I launch a multiplayer game, I notice two things. 

1. In both the server and client instances, the controller 0 actor (local) can move their fingers; however, they also move the fingers on the non-local pawn.

2. No behaviors are replicated from the server to client or vice-versa. 

Now here's what I definitely don't know:

1. I'm not doing any RPCs like I did in my original example. This is because in my limited understanding or (misunderstanding), the player state should be replicated to all clients so why would I need to? 

2. Player State doesn't seem to replicate at all. 

3. Even though I'm grabbing a reference to controller 0, other pawns seem to receive inputs derived from my player state.

Unrelated, but sort of related, I'm having almost the exact same problem with the OVRLipSync plugin, except my janky solution for the finger curls using RPCs doesn't seem to work with lip sync. I'm hoping that if I can solve this the way you are explaining, I can use the same concept with lip sync.

**Comment by 1runeberg** [comment]
Hi @mikeyboybs - make sure your PlayerState is being updated in the Server and not on the Client side so it gets replicated properly :)

**Comment by 1runeberg** [comment]
Hi @mikeyboybs - any luck?

**Comment by mikeyboybs** [comment]
Hi @1runeberg,

Yes. I was able to make the code a bit more streamlined but I think it follows the same philosophy I was using before. I'll share my blueprint when I get home.

**Comment by mikeyboybs** [comment]
hi again @1runeberg, sorry for the delay. 

Here is my "final" solution until I can iterate something better. hopefully others find it useful.

Character Blueprint (running a timer here because tracking gets wonky if it's tracked every tick)
![FingerPositionSolution](https://user-images.githubusercontent.com/20828914/57424837-4d941080-71d6-11e9-9795-191c18d1ad3c.PNG)
Animation Blueprint Event Graph
![FingerPositionSolution2](https://user-images.githubusercontent.com/20828914/57424849-5d135980-71d6-11e9-8584-d69c4448df5c.PNG)
Anim Graph
![FingerPositionSolution3](https://user-images.githubusercontent.com/20828914/57424859-669cc180-71d6-11e9-9837-08a0808d5f74.PNG)

Thanks again for your advice.

**Comment by 1runeberg** [comment]
Thanks @mikeyboybs ! Glad you got it all sorted :)

Will refer others to this issue thread until we can get some sample content with multiplayer capabilities in the plugin.
