### ISSUE TITLE
Launching VR editor and clicking 'No All' on bindings prompt still writes to bindings

### ISSUE THREAD

**Issue by muchcharles** [ValveSoftware/steamvr_unreal_plugin#101]
After launching the VR editor I got the bindings warning prompt:

![image](https://user-images.githubusercontent.com/7025369/71033141-ca7c5680-20e4-11ea-9cd8-5b24939986c2.png)

After clicking No All, it still modified my binding .json files adding VR editor actions (not sure if they were fully regenerated but if so it could potentially wipe out hand-edited changes for someone).

Image shows 'generic_hmd.json', which isn't generated by the plugin, but I saw the VR editor actions get added to 'gamepad.json' as a result of clicking 'No All' (I didn't check any others before reverting).  'gamepad.json' does originate in the plugin.

**Comment by 1runeberg** [comment]
Hi @muchcharles  - tried a couple of scenarios but couldnt replicate this somehow, in either the release 4.24 (from Launcher) and the master branch in GitHub.

Can you try in a fresh project, say the VR Template? And/or send me your files under Config/SteamVRBindings and I'll see if I can replicate using those.

Thanks.

**Comment by muchcharles** [comment]
Doesn't seem to happen with the VR template.  I added my generic_hmd.json to the template and it happens afterwards, still writing to gamepad.json and others with the VR Editor bindings, but I think that is actually ok.  It may cause it to overwrite hand edits in that case but I don't think it would have overwritten edits made through the bindings dashboard itself due to that last_edited_by metadata thing once steamvr writes to that.

**Comment by 1runeberg** [comment]
@muchcharles - Tried adding a hand-edited generic_hmd binding there, still not seeing the behavior you are getting.

If you're able to send me your SteamVRBindings folder, I can have a closer look.

**Comment by 1runeberg** [comment]
Hi @muchcharles - are you still having issues with this?

**Comment by muchcharles** [comment]
No issues with it anymore, I think you can close this one out.
