### ISSUE TITLE
Thumbstick d-pad bindings default to "sub_mode": click

### ISSUE THREAD

**Issue by muchcharles** [ValveSoftware/steamvr_unreal_plugin#102]
Thumbstick d-pad bindings seem to default to "sub_mode": "click"

`
                {
                    "mode": "dpad",
                    "path": "/user/hand/right/input/thumbstick",
                    "parameters":
                    {
                        "sub_mode": "click"
                    },
                    "inputs":
                    {
                        "west":
                        {
                            "output": "/actions/main/in/ClickTurnLeft"
                        }
                    }
                },
`

For plain gamepads the engine (not using steamvr) defaults to stick direction without requiring a click, and the previous VR input plugins did too, so this is probably a wrong default.  It is generated for WMR too where there is no thumbstick click.

Also, plain gamepads also have even diagonal overlap, so that might be a better default too, but there is precedent in the older VR plugins to not make the thumbstick directions have overlap, so this one is arguable.

**Comment by 1runeberg** [comment]
added to PR#6459 https://github.com/EpicGames/UnrealEngine/pull/6459

**Comment by 1runeberg** [comment]
@muchcharles - Closing as this has been released in Hotfix 2

If you have any further issues with this however, please jsut let us know.
