### ISSUE TITLE
Example Hand Model

### ISSUE THREAD

**Issue by simongloor** [ValveSoftware/steamvr_unreal_plugin#103]
I am failing miserably attempting to replace the model. 

I have tried exporting it from various sources (the Unity Plugin, the SteamVR-Folder of Steam, Unreal) importing it to Blender and exporting it back to Unreal. I also tried 20+ combintions of axe directions at import and export. The results until now looked all like this:
![image](https://user-images.githubusercontent.com/43432178/71243917-a6ea2380-2311-11ea-807e-e09e55025ab6.png)

Is there a demo .blend file with a note of the correct export setting anywhere or could it be provided?

**Comment by simongloor** [comment]
Okay, I've figured it out.

 - Get a model from any of the above-mentioned sources, import it with different axis settings until you are happy. 
 - Export it to Unreal and check, whether the hand without applied tracking is looking in the same direction as the sample of the plugin. If it doesn't match, rotate mesh and armature in Blender and apply the rotation.
 - If it matches, open the Skeleton, pick a bone and enable translate.
 - Now you can compare the axes of the bones and export your model with different armature axis settings. For me, it was Left: +Y, -X and Right: -Y, -X
 - If it matches, compare the hierarchy: You might need to delete the root bone of the armature in Blender, since the transform of the Armature counts as a bone.

Feel free to contact me, if the blender file should be added to this project.

**Comment by 1runeberg** [comment]
Glad you got it sorted @simongloor - thanks for sharing!
