### ISSUE TITLE
UE 4.24: MotionController Component not tracking Vive Trackers

### ISSUE THREAD

**Issue by sachdevaprash** [ValveSoftware/steamvr_unreal_plugin#104]
In Unreal 4.24, using a standard template map and a MotionController component, Special_1 source does not seem to feed any pose what so ever. Is there some particular binding to be set on the Steam VR UI for the pose to be accessible?

**Comment by 1runeberg** [comment]
Hi Prashant,

You can have a look at instructions in this closed issue:

https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/89#issuecomment-552224750

For 4.24, it won't autogenerate all the Json files except for "waist". So use waist in your SteamVR config for Special1. 

If you want to use other trackers in addition, you need to hand configure those files using the sample entries in the steamvr_manifest and vive_tracker Json files in your project's Config/SteamVRBindings folder. 

We're looking at adding extra tracker support in 4.25 similar to the source code version of the plugin (Github develop branches, e. g. Develop-4.23). 

Hope that helps. 

Cheers, 
Rune

**Comment by sachdevaprash** [comment]
Hi Rune,

Thanks for the prompt reply. I found the information on that issue. However, I cannot seem to find the options on the SteamVR settings area.

![image](https://user-images.githubusercontent.com/1396775/71484387-fffa0180-27c0-11ea-9297-8b29fdd54ea3.png)

And there is no "Create New Binding" option in the interface.

![image](https://user-images.githubusercontent.com/1396775/71484420-2cae1900-27c1-11ea-819f-61cb5bdc725d.png)

Am I missing something or using it incorrectly?

Thanks,
Prashant

**Comment by 1runeberg** [comment]
Hi Prashant,

Try launching the advanced bindings UI from UE4:

![image](https://user-images.githubusercontent.com/17371351/71487375-02b33000-286f-11ea-9ca4-cfcb6ff3906f.png)

Note: If you are using an Oculus headset, you need to disable Unreal's Oculus plugin to show the SteamVR Menu.

Alternatively, you can launch the old bindings UI from SteamVR:

![image](https://user-images.githubusercontent.com/17371351/71487416-4148ea80-286f-11ea-8240-7eea43c80213.png)

Let me know how you go.

Cheers,
Rune

**Comment by sachdevaprash** [comment]
I am checking this now. Let me get back to you with updates. Thanks for the prompt responses!

**Comment by nx306** [comment]
Hello @1runeberg - i would appreciate any hint on how to create the .jsons for 3 trackers, so far no luck with that. 

My main files: 
![image](https://user-images.githubusercontent.com/7034258/74243267-b8332900-4cdf-11ea-90cc-1b4c965850ef.png)

SteamVRBIndings folder:
![image](https://user-images.githubusercontent.com/7034258/74243364-e9135e00-4cdf-11ea-90b6-fdbba8361e17.png)

And Vive_tracket_xxx files: 
![image](https://user-images.githubusercontent.com/7034258/74243306-cd0fbc80-4cdf-11ea-8a3e-9f322b642e76.png)

I'm a bit clueless on what to try next, so any hints would be much welcomed ...

**Comment by nx306** [comment]
Hello, some help or guide on how to generate the .json files for trackers would be appreciated... So far no luck:

My vive_tracker_xxx.json:
![image](https://user-images.githubusercontent.com/7034258/74243618-617a1f00-4ce0-11ea-877c-a6b7ac6dee74.png)

Main .json:
![image](https://user-images.githubusercontent.com/7034258/74243729-8a021900-4ce0-11ea-8387-9119ba5ca474.png)

And my SteamVRBindings folder:
![image](https://user-images.githubusercontent.com/7034258/74243804-a7cf7e00-4ce0-11ea-8964-913e69527612.png)

Any hint on what am I doing wrong would be really helpful

**Comment by 1runeberg** [comment]
@sachdevaprash - Hi, are you still having issues with this?

**Comment by sachdevaprash** [comment]
Hi! I made it work, but not really with any suggestions I found. I had to write my own manifest files after some trial and error. No automatic regeneration of manifest files through any of the built-in options worked for me.

**Comment by 1runeberg** [comment]
HI @sachdevaprash - glad you got it working. The plugin in 4.24 only generates for the camera configuration by default and not for any other roles. Also, one thing to note the steamvr_manifest.json gets overwritten each editor restart, so you might want to try to set it to read-only if you added new tracker roles.

In the Github version, we've published this functionality (for 4.15-4.23) under a develop branch:
https://github.com/ValveSoftware/steamvr_unreal_plugin

We'll hopefully include this for 4.25, as new features aren't allowed in hotfixes for 4.24.

Cheers and thanks for the update.
