### ISSUE TITLE
Launching with -nohmd still launches steamvr when starting the editor

### ISSUE THREAD

**Issue by muchcharles** [ValveSoftware/steamvr_unreal_plugin#106]
Launching the editor with -nohmd still causes steamvr to launch.  Seems to be caused by the StartupModule stuff.

FSteamVRInputDeviceModule::StartupModule should probably wrap everything under `#if WITH_EDITOR` with:

`if (GIsEditor && (!FParse::Param(FCommandLine::Get(), TEXT("nohmd"))))`

**Comment by 1runeberg** [comment]
Hi @muchcharles - I guess you are referring to 4.24? and what's the use case for the nohmd param for a SteamVR UE project?

**Comment by muchcharles** [comment]
Yeah in the one integrated with 4.24, not sure if it affects the plugin in 4.23 etc.

**Comment by 1runeberg** [comment]
We're disabling this feature for now in UE4.24 Hotfix 2 as due to the Engine archi, it's causing issues on other use cases. Please find a change for this in the PR below:

https://github.com/EpicGames/UnrealEngine/pull/6582/

**Comment by kenbrueck** [comment]
> Hi @muchcharles - I guess you are referring to 4.24? and what's the use case for the nohmd param for a SteamVR UE project?

Not OP, but we have the same issue. Our software lets some users launch in VR mode and other users launch in a 2D mode. Some users launching in 2D mode may not even own VR hardware at all.

**Comment by muchcharles** [comment]
@kenbrueck That's probably no happening to due to the plugin anymore.  There is another engine bug that cause this, querying HMD GPU adapter even when -nohmd, which ends up spinning up SteamVR.  I'll try and add an engine pull request with the fix for that and send you a link.

**Comment by muchcharles** [comment]
@kenbrueck https://github.com/EpicGames/UnrealEngine/pull/6980

**Comment by rproepp** [comment]
I have also run into the same problem, using UE 4.21 from the Launcher and the plugin from the Marketplace. Without the plugin, -nohmd works fine, but when I activate it Steam VR always starts. So in this case it does seem to be related to the plugin, has it not been fixed for the UE 4.21 version?
