### ISSUE TITLE
No way to map Index thumbstick positions to axis bindings

### ISSUE THREAD

**Issue by martindeegan** [ValveSoftware/steamvr_unreal_plugin#107]
I'm trying to use the Index thumbstick to move my character.
[Here](https://i.imgur.com/etn2Wjp.png) is an image of my bindings.

When I regenerate and reload with the plugin, the axes don't get mapped.
[Here](https://i.imgur.com/v5RMOkH.png) is an image of the error in the browser and the thumbstick section is empty.

Additionally I've noticed when trying to manually bind the inputs, the position of the thumbsticks is a vector2 which to my knowledge is not supported by UE4 inputs.

**Comment by muchcharles** [comment]
I think you have to name the actions to end in _X and _Y for the plugin to pick them up as 2d and generate/handle the right bindings.

**Comment by 1runeberg** [comment]
Hi @martindeegan - you are right, as Unreal doesn't have a concept of a Vector2 action at the moment, we auto group two vector1 actions with names that end with _X and _Y at the end as mentioned by @muchcharles.

Also note however that the actions ending with _X and _Y must have corresponding controller keys bound to them. 

For example, to create a Vector2 ThumbstickMovement action, you need to:

(1) Create axis action: ThumbstickMovement_X
(2) Map a  controller input under (1) -- e.g. Valve Index (L) Thumbstick X
(3) Create axis action: ThumbstickMovement_Y
(4) Map a  controller inputunder (2) -- e.g. Valve Index (L) Thumbstick Y

Notice that (2) & (4) are paired X,Y controller inputs from the same controller and input type (thumbstick). 

Also note that (1) & (2) have the same name except for the _X & _Y at the end.

Once these conditions are met, the plugin will automatically generate a Vector2 Action for you.

You can also check the mappings we provided in the sample projects here:

**Sample project (UE4.15-4.23):**    https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin.zip   

**Sample Project (UE.424+):** https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

There is some Vector2 support in UE4.24, but this hasn't been fully implemented in the engine. My understanding is that this is planned for UE4.25, at which time this workaround won't be necessary - we'll publish something in the release notes when this happens.

**Comment by 1runeberg** [comment]
hi @martindeegan - are you still having issues with this?

**Comment by martindeegan** [comment]
Hi @1runeberg, this worked thanks!
