### ISSUE TITLE
4.24 MotionController not tracked in new project

### ISSUE THREAD

**Issue by insanepure** [ValveSoftware/steamvr_unreal_plugin#110]
hey, I just started VR Development for Unreal with C++. I'm following the VR tutorial here but I'm having some problems: https://docs.unrealengine.com/en-US/Platforms/VR/DevelopVR/MotionController/index.html

I set up my Controllers within my Pawn. They are displayed with the Display Device Model Flag by the MotionControllerComponent, so I can see them ingame.
I set one as "Left" the other as "right". They are childs of the RootScene of my Pawn.

Now when I start the VR Preview, they are both on the ground. If i move my controllers, nothing happens.

Someone told me that adding a new input and rebuilding steam vr input bindings fixes the issue. I tried that and it works now. 
So, would be great if this is fixed for new users.

**Comment by simongloor** [comment]
Finally! I was looking for this bug for days. I thought I was doing something wrong. ^^

I just wanted to add that the motion tracking on a Windows Mixed Reality device won't work as long as there is no button of it assigned, even if you add inputs for other motion controllers.

**Comment by 1runeberg** [comment]
> Finally! I was looking for this bug for days. I thought I was doing something wrong. ^^
> 
> I just wanted to add that the motion tracking on a Windows Mixed Reality device won't work as long as there is no button of it assigned, even if you add inputs for other motion controllers.

Thanks for the feedback @simongloor - just double-checked that the fix should take care of this as well. But do let us know if it's causing you issues. This fix should come out in 4.24.2.

**Comment by Qwigs** [comment]
Note on this, I got this same issue yesterday on 4.24.3 and think turning off Oculus Plugin fixes it. Is this possibly a multi-cause issue? Is there a fix for the cross-talk problem in the future?

**Comment by 1runeberg** [comment]
Hi @Qwiggalo - possibly not without an engine architecture change. OpenXR is meant to resolve this, but for now, either plugin must be turned on or off depending on which platform you wish to test on.

**Comment by insanepure** [comment]
I just closed this as it was fixed here: https://github.com/EpicGames/UnrealEngine/commit/15be362d03e2a21a82d290d64dc5e7ac60dccfda
