### ISSUE TITLE
SteamVR Nodes dissapearing when reloading project

### ISSUE THREAD

**Issue by pablonaj** [ValveSoftware/steamvr_unreal_plugin#111]
Hi Runeberg,

I am having some issues updating from 4.23 to 4.24.1.

I migrated the files from this comment (https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/99#issuecomment-568067725). 

Everything seemed ok but for some reason in the AnimGraph inside the Animation Blueprints for the gloves, the SteamVR Set Wrist Transform and SteamVR Skeletal Anim Pose keep disappearing. They work initially but if I close and reopen the project they are gone. They also don't work when I package the project.

May be something obvious I am missing, any ideas?

**Comment by 1runeberg** [comment]
Hi @pablonaj -are there any related events in the project logs?

It's possible the engine is somehow internally trying to refer to anim nodes from the marketplace plugin which wouldnt be in your new project in 4.24. 

Have you tried reapplying the nodes by deleting and adding them back in?

**Comment by pablonaj** [comment]
Hi Runeberg,

It's working after deleting the Build, Intermediate, Saved and Binaries folders, forgot to do it after updating to 2.24.1 so probably something old was being referenced.

Thanks for your help.

**Comment by 1runeberg** [comment]
awesome! glad you got it sorted. will close this now then, but let us know if you need anything else on this. 

Cheers,
Rune
