### ISSUE TITLE
Path handling of action bindings not working correctly

### ISSUE THREAD

**Issue by Ben-Cykyria** [ValveSoftware/steamvr_unreal_plugin#113]
This is a minor issue and easy to work around, however, I think it's important to track it.

I used a path for the UE project with spaces ("../vrexppluginexample - Copy/.."), this leads to the error below. Simply renaming the folder to ("../vrexppluginexampletest/..") and restarting solved the issue.

Unreal Engine error output log:

```
LogSteamVRInputDevice: Display: Reloading Action Manifest in: D:/bitbucket/vrexppluginexample - Copy/Config/SteamVRBindings/steamvr_manifest.json
LogSteamVRInputDevice: Display: [STEAMVR INPUT] Registering Application Manifest D:/bitbucket/vrexppluginexample - Copy/Config/steamvr_ue_editor_app.json : VRApplicationError_None
LogSteamVRInputDevice: Display: [STEAMVR INPUT] Editor Application [10964][application.generated.ue.virtual-reality-bp-game-template-10757647.ue4editor.exe] identified to SteamVR: VRApplicationError_None
LogSteamVRInputDevice: Error: [STEAMVR INPUT] Setting Action Manifest Path: Mismatched Action Manifest
```

Using UE 4.24 (with the built-in SteamVR Input plugin), original issue here for reference: https://forums.unrealengine.com/development-discussion/vr-ar-development/89050-vr-expansion-plugin?p=1711890#post1711890

**Comment by 1runeberg** [comment]
Thanks for the report. Will investigate.

**Comment by 1runeberg** [comment]
Hi @Ben-Cykyria - I just tried to replicate this and couldn't get the issue.

However, the **Mismatched Action Manifest** error is symptomatic of something else - steamvr may be holding on to another set of bindings for a similarly named project.

**You can fix this by:**
(1) Go to your **{Program files} \ Steam \ config** directory 
(2) In the file s**teamvr.vrsettings**, remove any json entries with **ue** in it. You can also delete this file altogether to regen to defaults. 
(3) Close UE 
(4) Restart SteamVR 
(5) Open UE

There is a way to override this steamvr behavior from a plugin code, but atm we need to wait for a OpenVR update in UE to get that in - so possibly, this wouldnt be an issue anymore in UE 4.25.

**Comment by aadeshrao123** [comment]
<h2>I get this error when I try to play my unreal packaged build with my oculus in SteamVR</h2>
<h3>How can I fix this I am using unreal engine 5 I get this error when I try to play with steam VR</h3>

![com oculus xrstreamingclient-20221101-114158](https://user-images.githubusercontent.com/55663044/199182526-7babe622-52b2-44f3-8cef-cc0478c3cd9c.jpg)
![com oculus xrstreamingclient-20221031-174101](https://user-images.githubusercontent.com/55663044/199182561-b28dee29-64d9-4c3d-8527-58a6e77eee9b.jpg)

**Comment by 1runeberg** [comment]
Hi @aadeshrao123 - I opened a new issue for this:

https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/196
