### ISSUE TITLE
"Trackpad Touch" as Axis in UE4.24 Hotfix 2 requires Press

### ISSUE THREAD

**Issue by 1runeberg** [ValveSoftware/steamvr_unreal_plugin#115]

**Comment by 1runeberg** [comment]
When "[Controller] Trackpad Touch" is set to an Axis action, new default behaviour requires a press to be triggered, which is the same behaviour as an axis mapping to "[Controller] Trackpad".

This will be fixed so behavior on  "[Controller] Trackpad Touch" emits a value. In the meantime: 

(1) Since the values for Touch are always 0 or 1, map "[Controller] Trackpad Touch" as a boolean action - that is, map in the Action/Key bindings instead of an Axis binding.

- Or -

(2)  Map the Axis Action to "Touch" in the SteamVR Controller Bindings.

**Comment by Andyhdr** [comment]
Thanks for opening the issue. 
The touch itself is registered as you mentioned (0/1). Also the button presses (touch up/down/left/right) work. But we don´t get any information about the touch in a specific direction. We have a radial menu where we use the touch functionality to select the different buttons and we use the actual touch press to trigger this button. In the earlier versions we just used the x/y axyis value of the touch to detemine the location the user is pointing at.

**Comment by Andyhdr** [comment]
Any news on this issue yet?

**Comment by 1runeberg** [comment]
Hi @Andyhdr  - we have a candidate fix but not sure if it's going to make it to Hotfix3.... 

For the touch directions, are you referring to Vive inputs? A vector2 (TrackpadX, trackpadY) on the vive trackpad should respond on touch.

**Comment by 1runeberg** [comment]
Pull Request here: https://github.com/EpicGames/UnrealEngine/pull/6680

**Comment by Andyhdr** [comment]
Awesome, thank you. One thing we found out yesterday:
The input mapping for the Trackpad is not triggered by the Vive(L/R) Trackpad Y/X. You can test it if you open up the 4.24 demo project and delete the axis mapping for it. In this case you still get the values. But if you delete the Valve Index Thumbstick and the Mixed reality Thumbstick also nothing works anymore. They seem to be mixed up in a strange way.

**Comment by 1runeberg** [comment]
@Andyhdr - when you open the SteamVR Input dashboard (via the UE UI), which controller profile does it say is active?

**Comment by 1runeberg** [comment]
Addressed in: https://github.com/EpicGames/UnrealEngine/pull/7073

**Comment by 1runeberg** [comment]
This is now fixed in 4.26, thanks for reporting!
