### ISSUE TITLE
Axis values are not -1 to 1

### ISSUE THREAD

**Issue by Gitschi** [ValveSoftware/steamvr_unreal_plugin#117]
I'm using the version for UE 4.23 and the axis values I get from the analogue sticks or vive wand touchpad are completely messed up.
For the knuckles controller I'm getting -2 to 2 and for the vive wands it's between -123 to 123 instead of being between -1 and 1 as it should be.
This makes it really cumbersome to implement things such as snap turning at a certain threshold.
It also makes the player run at full speed when just touching the stick or pad a little bit.

**Comment by 1runeberg** [comment]
Hi @Gitschi - can you try the latest code in develop-4.23?
https://github.com/ValveSoftware/steamvr_unreal_plugin

It should have the fix for this, let us know though if you're still when using the latest develop version. Thanks.

**Comment by Gitschi** [comment]
Hi @1runeberg
Thank you for the answer.

Updating to latest code did indeed fix the issue with the axis values.
However the motion controllers stopped tracking completely now and are locked to the vr origin.
Tried it with vive wands and index controllers.

**Comment by 1runeberg** [comment]
hi @gitschi - that's odd. is this with axis inputs defined? can you send over the project logs please. thanks ( to runeb@valvesoftware.com if it has sensitive info).

Also, can you test with the standard vr template?

**Comment by Gitschi** [comment]
@1runeberg 
For the inputs I just generated the default ones that come with the plugin.
I just tried with a fresh standard vr template and the same issue persists.
All the inputs are working fine, but the hands are just locked into the ground.

I put the log and the project files up on g drive for you to check out.
https://drive.google.com/drive/folders/1VVDi3be9P0ArMeroGQLUNEi-J0e181MP?usp=sharing

**Comment by 1runeberg** [comment]
Hi @gitschi - Thanks for the logs. Can you try moving the project in a directory without spaces and let me know how that goes for you:

![image](https://user-images.githubusercontent.com/17371351/74679958-5f015300-5213-11ea-8942-6a3481447e60.png)

**Comment by 1runeberg** [comment]
also @Gitschi, if you have moved the project or opened it at a different project folder before, please clear any entries with ue4 in your steamvr.vrsettings (...program files x86\steam\config) and restart SteamVR.

**Comment by Gitschi** [comment]
Hey @1runeberg , sorry to bother you again, but that also doesn't fix the issue.

I moved the project over to a folder without spaces and got rid off the **vrappconfig** files.
After that I also made a completely new project again and made sure it's in a folder path without spaces.

I put a new log up on the same drive folder:
https://drive.google.com/drive/folders/1VVDi3be9P0ArMeroGQLUNEi-J0e181MP?usp=sharing

I also made a shipping build and put it in the drive folder.
The same issue persists.

**Comment by 1runeberg** [comment]
Hi @Gitschi - sorry I somehow missed this reply.

From the logs, OculusInput is taking over. You need to disable tohe oculus plugin for builds bound for SteamVR or change the engine priority.

Alternatively, you can change the priorities in engine.ini to something like:
[HMDPluginPriority]
OculusHMD=20
SteamVR=10

**Comment by 1runeberg** [comment]
Hi @Gitschi - Do you need any further assistance on this?
