### ISSUE TITLE
Valve Index not working in VR Editor Mode

### ISSUE THREAD

**Issue by OptimisticMonkey** [ValveSoftware/steamvr_unreal_plugin#118]
Not sure if this is right place to post - but the default vr editor is broken in 4.24.2

There is no way to display the popup windows or context menus, and every button is mapped to the same function.   

Ideally, you should be able to create a new VR Project, toggle VR Mode in editor , and use the index controllers out of the box.  

BTW - Is there an official Valve Index Developer forum to post this kind of issue?

**Comment by 1runeberg** [comment]
Hi @OptimisticMonkey - as far as im aware, there's still no Index support in the VR Editor. this may be something that'd be great to put in https://epicsupport.force.com/unrealengine/s/ or the UE forums, but this way it's tracked. Let me know and we can help amplify the request as well.

**Comment by OptimisticMonkey** [comment]
Thanks runeberg - I submitted bug to Epic, they replied via email and asked question whether it was knuckles or wand...  Cant seem to find any tracking number.

The title was "Valve Index default vr editor controller bindings are broken in 4.24.2"

**Comment by 1runeberg** [comment]
HI @OptimisticMonkey - Not sure if this is what you're asking but, "Knuckles" refers to the Valve Index Controllers while "Wands" are the HTC Vive Controllers.

**Comment by OptimisticMonkey** [comment]
Yeah I had told them Knuckles - btw just got a reply:

"...spoke with QA and it turns out that the Knuckles are not yet supported. :-\
No timeline for support was given.
Sorry to be the bearer of bad news,...."

So I guess no using Knuckles in UE Editor for now :-(

**Comment by 1runeberg** [comment]
Closing this now as we don't have any direct influence on the VR Editor, but we do suggest UE Developers to follow it up directly with Epic.
