### ISSUE TITLE
Hello, some help or guide on how to generate the .json files for trackers would be appreciated... So far no luck:

### ISSUE THREAD

**Issue by 1runeberg** [ValveSoftware/steamvr_unreal_plugin#119]
Split from Issue #104 by @nx306:

"Hello, some help or guide on how to generate the .json files for trackers would be appreciated... So far no luck:

My vive_tracker_xxx.json:
![image](https://user-images.githubusercontent.com/7034258/74243618-617a1f00-4ce0-11ea-877c-a6b7ac6dee74.png)

Main .json:
![image](https://user-images.githubusercontent.com/7034258/74243729-8a021900-4ce0-11ea-8387-9119ba5ca474.png)

And my SteamVRBindings folder:
![image](https://user-images.githubusercontent.com/7034258/74243804-a7cf7e00-4ce0-11ea-8964-913e69527612.png)

Any hint on what am I doing wrong would be really helpful

_Originally posted by @nx306 in https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/104#issuecomment-584652916_

**Comment by 1runeberg** [comment]
HI @nx306 - Thanks for reaching out. A couple of things:

(1) steamvr_manifest.json in "default bindings", you need to specify the new tracker json files
(2) In your tracker json files, in "poses",  you only need to map the pose (left/right foot) that this tracker json file is referrign to,
(3) In your tracker json files, make sure the controller_type matches the controller_type refferred to in steamvr_manifest.json under "default bindings"

In addition, there's better support for trackers in the Marketplace version of the plugin (develop-source only) - it'll autogenerate the correct poses for all possible tracker configs as well as add additional Motion Sources in the engine specific for trackers:
https://github.com/ValveSoftware/steamvr_unreal_plugin

We're also looking into porting this functionality for inclusion in UE4.25.

**Comment by nx306** [comment]
@1runeberg - thanks for the tips, will try it out. If I understand it correctly, the marketplace plugin works only up to Unreal 4.23, so when we're using 4.24 we're out of luck, correct? 4.25 seems to be too far for us to be viable.

**Comment by 1runeberg** [comment]
Hi @nx306 - correct, the marketplace plugin is only up to UE4.23, you can however try grabbing the develop branch though in GitHub and add to a sample project, say the VR Template and check the generated tracker controller files if you need more samples.

**Comment by 1runeberg** [comment]
Also, one thing to note the steamvr_manifest.json gets overwritten each editor restart, so you might want to try to set it to read-only. It's less than ideal unfortunately, but hopefully we'll get the better tracker support out in 4.25 as no new features are allowed in 4.24 hotfixes.

**Comment by 1runeberg** [comment]
Hi @nx306 - we've added new features in 4.26 to automate this, do you want to try them and let me know if you have any issues?

**Comment by nx306** [comment]
@1runeberg we actually did something in previews and my colleague said that the Unreal support works quite well, however he has few suggestions mostly on SteamVR part. First is that you need to go to legacy binding UI and set tracker on camera as camera pose. Secondary SteamVR needs to be switched to work without HMD and the driver needs to be set manually in .vrsettings files to work without HMD. As virtual production is getting Steam and many studios are using trackers to track camera, this would be good to either resolve, or make some kind of official tutorial / wiki. But anyway, good work!

Also tagging my colleague here directly, so he may provide fuhrer feedback if needed. @bombush

**Comment by 1runeberg** [comment]
Thanks for the feedback.Will keep this in mind as we work on the OpenXR support. Cheers.
