### ISSUE TITLE
Buttons that are mapped to an axis action are set to "force" instead of "scalar_constant"

### ISSUE THREAD

**Issue by smapty** [ValveSoftware/steamvr_unreal_plugin#12]
Hi!
So, I noticed that inputs that are buttons (in this case the Vive Controller Grips) that are mapped to axis values get set to force inputs instead of scalar_constants.

Until I found it, I thought the inputs weren't working. Once I remapped them, I was able to figure out what was happening. I have a fix for the grip issue only, but it'd be nice to have a better fix that would work with any button.

[SteamVRInputDevice.zip](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/3114392/SteamVRInputDevice.zip)

**Comment by 1runeberg** [comment]
Thanks for reporting @smapty ! Will have a look.

**Comment by 1runeberg** [comment]
This is now addressed (all buttons) in develop branch.

In the process of testing the solution, also uncovered that X, Y buttons specific to Oculus touch controllers aren't handled at all by the plugin. This functionality was added as well in the last commit.

develop is in 4.15, but you should be able to cherry-pick the last two commits to a copy of your version branch or repo fork.

Any issues on this from your end, pls just let me know.
