### ISSUE TITLE
I'm running into a problem with UE 4 vr gloves joints. Can I use the joints for the left and right gloves? In the default there is only a right glove that's mirrored. Do I have to mirror the glove? If don't have to, than how should I orient the joints?

### ISSUE THREAD

**Issue by 1runeberg** [ValveSoftware/steamvr_unreal_plugin#120]
_Originally posted by @tedconry in https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/71#issuecomment-585267477_

I'm running into a problem with UE 4 vr gloves joints. Can I use the joints for the left and right gloves? In the default there is only a right glove that's mirrored. Do I have to mirror the glove? If don't have to, than how should I orient the joints?

**Comment by 1runeberg** [comment]
Hi  @tedconry - For the Valve provided gloves, you should have two skeletons, one for the left and one for the right:

![image](https://user-images.githubusercontent.com/17371351/74360552-61316f00-4e19-11ea-9c52-018d674bbe6a.png)

If you are referring to the stock UE4 Skeleton (the one that comes with the UE VR Template)

![image](https://user-images.githubusercontent.com/17371351/74360599-77d7c600-4e19-11ea-8141-186de5151d4a.png)

In the animation, you need to set the Skeleton anim pose to the following values:

![image](https://user-images.githubusercontent.com/17371351/74360856-ef0d5a00-4e19-11ea-8569-7ff3ec9afd0e.png)

**Comment by tedconry** [comment]
Ok, I'm using the skeleton from the "Mannequin hand right" for a left hand. The joints in maya are orientated the same way. But it's not deforming correctly. Is the code for your plug in allow for mannequin "hand_r" joints hierarchy as well a "hand_l" or does it have to be mirrored in unreal? In maya I'm trying to replicate the mannequin hand right to make left hand. If I want to use separate skeleton meshes one left, one right, than do I need the stream vr or can I use the mannequin joints? (without mirroring)

**Comment by 1runeberg** [comment]
you should be able to just apply a -1.0 scale on the Z axis of the right mesh in UE4 to get the left hand, then apply those anim node values I've posted earlier.

if you need a separate left skeleton, you can try unchecking "mirror" on the node I posted above and still keeping to "Left Hand", but we've not tested it for this use case as these settings are meant for the UE4 provided skeleton and Epic only provides the right hand, developers are meant to scale the mesh to get the left hand.

**Comment by BreakMaker** [comment]
Did this work out for you?

**Comment by 1runeberg** [comment]
@tedconry @BreakMaker  - let me know if you folks still have issues with this
