### ISSUE TITLE
Oculus Touch and Vive Cosmos motion controllers are translated incorrectly under UE4.24

### ISSUE THREAD

**Issue by Ma8ter** [ValveSoftware/steamvr_unreal_plugin#122]
Since UE4.24 my controllers in-game shifted upwards, forward, and to the right. It looks like motioncontrollercomponent's position vector is multiplied by some value.

**Comment by 1runeberg** [comment]
Hi @Ma8ter - with the new input system, the origins are different for each controller than legacy, so you may need to apply some offsets to get the exact controller position you need/want for Oculus Touch controllers.

You can have display device model on temporarily to help with hte alignment, and you use something like this to detect controller type in your project:
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/97

The Sample project for UE4.24 also has this:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

I hope that helps

**Comment by Ma8ter** [comment]
Thanks for your reply, @1runeberg

I guess I should've also added that in SteamVR home and dashboard those controllers are tracked perfectly, and so they are if I use clean Pawn class. Positions shift when I use Character class. Tried to attach my Pawn to my Character, but the outcome is the same as if I attached MotionControllerComponents to it directly.
Don't really know if it helps to understand the issue here, but it looks like so.

Oculus Touch works perfectly via OculusVR plugin, btw, but my project needs to support both Oculus and Cosmos, so SteamVR is an obvious choice.

Will try the offset-applying approach though and update whether it works.

**Comment by 1runeberg** [comment]
Hi @Ma8ter - The plugin doesn't distinguish between a character or pawn. It merely sends translation and input data from steamvr to the engine.

I just quickly tested using ue default pawn and character classes and have gotten consistent results:

![image](https://user-images.githubusercontent.com/17371351/74891085-0cbe5e80-53da-11ea-9e29-863085e232b4.png)

Other than the steamvr default provided offset for which you need to account for depending on controller type as I mentioned in my last reply, i'm not seeing any other offset differences between using a pawn or a character - at least with the vanilla ue ones and a stock ue 4.24 install with no other plugins other than the epic provided ones.

**Comment by Ma8ter** [comment]
Kinda found the source of the problem and it just blows my mind as hell. Every single project of mine includes Chameleon Postprocess plugin, and it never caused any issue until I started to use SteamVR plugin. The former somehow manages to screw the latter up so much that I need to restart SteamVR, UE, and Cosmos completely to fix the consequences.
After I deleted an instance of Chameleon from all levels and rebooted everything, controllers are tracking just perfect.
Trying to understand how something like this may be even possible. After that will try to figure out, what exactly went wrong.
Sorry for bothering and thanks for your help.

**Comment by 1runeberg** [comment]
Hi @Ma8ter - thanks for the update. Yeah, mentioned specifically vanilla UE install because have had reports from other plugins - normally plugins that might be doing some sort of predictive transform correction, especially anything linked to networking. Wasn't too sure that applied to your case though, so appreciate the update.

Issue sometimes could be the 3rd party plugin is expecting legacy steamvr mesh origins, so things might look a bit off.

**Comment by Ma8ter** [comment]
Update:
Even without Chameleon plugin, my controllers jump away whenever ResetOrientationAndPosition node is triggered, and they remain off place until I restart SteamVR. Don't see any direct connection but it is possible that Chameleon actor triggered ROAP node somehow.

**Comment by 1runeberg** [comment]
Hi @Ma8ter - are you seeing the same behavior in a vanilla VR Template? It's usually a good baseline to test if anything might be causing the issue (e.g. way the MC attachments are done etc).

**Comment by grantbolton** [comment]
I am seeing this issue in projects post 4.24, with a previously working pawn, vanilla template or brand new ‘Empty’ pawn. It only happens when calling ResetOrientationAndPosition.

**Comment by 1runeberg** [comment]
@Ma8ter  - have you had a chance to check the standard template?
