### ISSUE TITLE
Steam VR not picking up controller bindings

### ISSUE THREAD

**Issue by VismayaStudio** [ValveSoftware/steamvr_unreal_plugin#123]
Hello,

Firstly sorry if this is the wrong place to post this. Unfortunately, Unreal answers have been down for over a week and I don't seem to be getting much response from the forum/reddit. 

I have integrated Steam VR and the packaged game works perfectly on my end — however, no one else seems to be able to get their controllers working with Steam VR.

The hands in-game are facing each other (🙏) and none of the bindings are working. Head tracking is working however.

I am using Unreal Engine 4.24.2. 

I have followed the instructions for this issue #112 and as instructed, created a Config folder with SteamVRBindings but it still doesn't seem to work. This is the contents of that folder:

https://imgur.com/4QdpLKd

Do you have any idea how I can resolve this?

Thank you,
Krish.

**Comment by 1runeberg** [comment]
Hi @krishkrush - A couple of things to check:

(a) Make sure that the Oculus Plugin is not enabled when packaging for SteamVR
(b) You need to copy the config/steamvrbindings folder from your Project file
(c) To ensure a unique project name - make sure in your UE project settings, you have a Project Name specified.

You can also do the following steps before running your packaged build in your machine to test what your users are possibly seeing on their end:

(1) Go to your {Program files} \ Steam \ config directory
(2) In the file steamvr.vrsettings, remove any json entries with ue in it. You can also delete this file altogether to regen to defaults.
(3) Restart SteamVR
(4) Open the packaged build

**Comment by VismayaStudio** [comment]
Thanks for you assistance @1runeberg :) 

Unfortunately that hasn't fixed it :(

I can confirm that:

a) Oculus was disabled when packaging
b) I copied over the files from the Project file as indicated
c) I have a unique name 'Playne VR' in the project name field in Project Description.

A minor correction in my initial post is that the packaged build does not work on my machine neither.

Also, I couldn't find any json entries in the steamvr.settings file.

I will attach the code from the json on files in case it helps you to identify the issue.

vive.json
`{
	"name": "Default bindings for Vive Headset",
	"controller_type": "vive",
	"last_edited_by": "UnrealEngine",
	"bindings":
	{
		"/actions/main":
		{
			"sources": []
		}
	},
	"description": "Playne VR-11100242"
}`

vive-controller.json
`{
	"name": "Default bindings for Vive",
	"controller_type": "vive_controller",
	"last_edited_by": "UnrealEngine",
	"bindings":
	{
		"/actions/main":
		{
			"sources": [
				{
					"mode": "button",
					"path": "/user/hand/left/input/trigger",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/GrabLeft"
						}
					}
				},
				{
					"mode": "button",
					"path": "/user/hand/right/input/trigger",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/GrabRight"
						}
					}
				},
				{
					"mode": "trackpad",
					"path": "/user/hand/left/input/trackpad",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/TeleportLeft"
						}
					}
				},
				{
					"mode": "trackpad",
					"path": "/user/hand/right/input/trackpad",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/TeleportRight"
						}
					}
				},
				{
					"mode": "dpad",
					"path": "/user/hand/right/input/trackpad",
					"parameters":
					{
						"sub_mode": "click"
					},
					"inputs":
					{
						"north":
						{
							"output": "/actions/main/in/RThumbstickUp"
						}
					}
				},
				{
					"mode": "dpad",
					"path": "/user/hand/right/input/trackpad",
					"parameters":
					{
						"sub_mode": "click"
					},
					"inputs":
					{
						"south":
						{
							"output": "/actions/main/in/RThumbstickDown"
						}
					}
				},
				{
					"mode": "dpad",
					"path": "/user/hand/right/input/trackpad",
					"parameters":
					{
						"sub_mode": "click"
					},
					"inputs":
					{
						"west":
						{
							"output": "/actions/main/in/RThumbstickLeft"
						}
					}
				},
				{
					"mode": "dpad",
					"path": "/user/hand/right/input/trackpad",
					"parameters":
					{
						"sub_mode": "click"
					},
					"inputs":
					{
						"east":
						{
							"output": "/actions/main/in/RThumbstickRight"
						}
					}
				},
				{
					"mode": "button",
					"path": "/user/hand/left/input/application_menu",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/SpinMenu"
						}
					}
				},
				{
					"mode": "button",
					"path": "/user/hand/right/input/grip",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/ActivateWeatherPower"
						}
					}
				},
				{
					"mode": "button",
					"path": "/user/hand/left/input/grip",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/ActivateTimePower"
						}
					}
				},
				{
					"mode": "button",
					"path": "/user/hand/right/input/application_menu",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/StartMeditation"
						}
					}
				},
				{
					"mode": "button",
					"path": "/user/hand/right/input/trigger",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/RightTrigger"
						}
					}
				},
				{
					"mode": "button",
					"path": "/user/hand/left/input/trigger",
					"inputs":
					{
						"click":
						{
							"output": "/actions/main/in/LeftTrigger"
						}
					}
				},
				{
					"mode": "trackpad",
					"path": "/user/hand/left/input/trackpad",
					"inputs":
					{
						"position":
						{
							"output": "/actions/main/in/MotionControllerThumbLeft_X,MotionControllerThumbLeft_Y X Y_axis2d"
						}
					}
				},
				{
					"mode": "trackpad",
					"path": "/user/hand/right/input/trackpad",
					"inputs":
					{
						"position":
						{
							"output": "/actions/main/in/MotionControllerThumbRight_X,MotionControllerThumbRight_Y X Y_axis2d"
						}
					}
				}
			],
			"poses": [
				{
					"output": "/actions/main/in/controllerleft",
					"path": "/user/hand/left/pose/raw",
					"requirement": "optional"
				},
				{
					"output": "/actions/main/in/controllerright",
					"path": "/user/hand/right/pose/raw"
				}
			],
			"skeleton": [
				{
					"output": "/actions/main/in/skeletonleft",
					"path": "/user/hand/left/input/skeleton/left"
				},
				{
					"output": "/actions/main/in/skeletonright",
					"path": "/user/hand/right/input/skeleton/right"
				}
			],
			"haptics": [
				{
					"output": "/actions/main/out/vibrateleft",
					"path": "/user/hand/left/output/haptic"
				},
				{
					"output": "/actions/main/out/vibrateright",
					"path": "/user/hand/right/output/haptic"
				}
			]
		}
	},
	"description": "Playne VR-11100242"
}`

**Comment by VismayaStudio** [comment]
Also, @1runeberg I have sent you a Steam key via beyondreality.io that will give you quick access to the packaged game.

**Comment by 1runeberg** [comment]
Hi @krishkrush - can you officially resend the key or ideally invalidate please and send the key to my Valve email/Steam Account instead runeb@valvesoftware.com as that email isn't for Valve correspondence :)

**Comment by VismayaStudio** [comment]
Of course - sent :) Thank you.

**Comment by VismayaStudio** [comment]
I wasn't sure if its worth nothing this, but this project was upgraded from 4.23 to 4.24.2.  Thanks.

**Comment by 1runeberg** [comment]
I havent gotten the key, but you can send me a link with the compressed packaged build instead since your build isn't running on your own machine either.

**Comment by VismayaStudio** [comment]
I've just sent you the details to runeb@valvesoftware.com again. Hope you get it. Are you on discord? If so I could send you there if this doesn't work. 

Also, my email is krish@playne.co.

**Comment by 1runeberg** [comment]
Hi @krishkrush  - thanks for that. the location of the config directory is outside the project in your build, but even moving it in, the application manifest doesn't seem to be loading so SteamVR is reverting to legacy default bindings.

I can't seem to see any attempts from the app to load the manifest in - can you make a 64 bit debug build please and send it over to me?

If you're using a source build of the engine, you can also enable logging in shipping:
https://forums.unrealengine.com/development-discussion/c-gameplay-programming/1614392-how-to-add-buselogginginshipping-to-my-project?p=1614965#post1614965

**Comment by VismayaStudio** [comment]
@1runeberg 64bit build works!!! :D :D : D

However, 32bit does not.

Would it help you if I sent you the 64bit build to see what might be happening?

**Comment by 1runeberg** [comment]
Hi @krishkrush the plugin has only been whitelisted for 64bit platforms

is there any particular reason you are publishing in 32 bit?

**Comment by VismayaStudio** [comment]
Ah, that makes sense. I have now migrated over to 64bit and it seems to be working!

Thank you for helping me with this @1runeberg :)

**Comment by 1runeberg** [comment]
No prob! Thanks for the update @krishkrush !
