### ISSUE TITLE
Steam VR Hands Misaligned

### ISSUE THREAD

**Issue by VismayaStudio** [ValveSoftware/steamvr_unreal_plugin#124]
Hello,

I have another issue related to the Steam VR plugin for unreal.

The VR hands seems to be pointing about 45 degrees too high from the natural position. This seems to only occur when using Steam VR (via oculus there are no issues).

Any idea what might be happening here?

Thanks,
Krish.

**Comment by VismayaStudio** [comment]
Just did a bit more digging @1runeberg — The issue is present even in the VR template.  

In Oculus, the hand position is correct. But when you disable Oculus and just use Steam VR, then hands are about 45 degrees too high.

**Comment by 1runeberg** [comment]
Hi are you referring to this: https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/122

**Comment by VismayaStudio** [comment]
Hey @1runeberg ,

I'm not sure if this issue is a duplicate of #122 — with my issue, the controller just faces up but about 45 degrees. Also, I am getting the same issue with the vanilla VR template, and only when using Steam VR.

If I do simply just need to set an offset for this, do you know the recommended way to do this?

Thanks,

**Comment by 1runeberg** [comment]
Hi @krishkrush - there is a future plan toexpose the offsets easier, but at the moment, devs would have to apply the adjustments manually depending on their project and hand mesh in use.

the offsets may vary slightly from project to project depending on how your character is setup, your hand mesh orientations, other plugins in use and is outside the scope of the plugin support.

Generally however, you can easily apply relative transforms to the mesh attached to your motion controller component to match your expected result depending on controller type in active use.

Oculus and SteamVR maintain separate APIs and therefore they wont always match completely.

**Comment by VismayaStudio** [comment]
Thank you so much for your time in helping me with this @1runeberg . I have used RelativeRotation to offset the VR hands and it seems to be working.
