### ISSUE TITLE
Steam Chaperone Compile Error

### ISSUE THREAD

**Issue by VismayaStudio** [ValveSoftware/steamvr_unreal_plugin#125]
There seems to be a SteamVR compile error in a new VR template on Unreal engine 4.24.2.

Is it okay to unplug this node? 

![Compile Error](https://i.imgur.com/ltXe5JM.png)

Thanks,

**Comment by 1runeberg** [comment]
Hi - Not seeing that error on my end. The template was developed by Epic though so the folks at the UE Answer Hub might be better able to assist :)

**Comment by 1runeberg** [comment]
Hi @krishkrush - do you still need help from our end on this? 

We don't maintain hte VR Template and Im also unable to see any errors on vanilla vr templates from our end.

If you are having specific issues with the VR Templates, Epic Answer Hub is your best resource as then Epic may want to fix these if they find an issue.

**Comment by VismayaStudio** [comment]
@1runeberg I just checked and it looks like the 4.24.3 hotfix has resolved this issue.

Thanks for checking this.

**Comment by RobH22** [comment]
I'm now seeing this issue on all the VR files I  have. I'm getting this in 4.24.3 as well in 4.25 and 4.26. Anyone else having the issue?

**Comment by 1runeberg** [comment]
That's an issue with the outdated VR template, not with the input plugin. You need to delete the chaperone component and all the nodes relating to it as that doesn't exist anymore in the newer versions of the engine. 

This should be communicated directly with Epic, but we have already raised this before to them.

**Comment by RobH22** [comment]
I appreciate the feedback. Thank you. 

I realize it's an Epic issue but this is the only place my searches turned up as threads discussing it. So, pardon my intrusion but thanks for the confirmation. :)
