### ISSUE TITLE
Vive Trackers: UE4 and SteamVR fail to link

### ISSUE THREAD

**Issue by MWaerzner** [ValveSoftware/steamvr_unreal_plugin#126]
Hi, 

for a couple of days now I am trying to get HTC Vive Trackers running with the new integrated SteamVR Input plugin within UE4 4.24.3 (updated to this as it lists a related fix, did not change anything though). I am using SteamVR 1.9.16

I suspect the main problem is the linking between SteamVR and Unreal Engine as it fails to register the application manisfest and the identification to SteamVR

![image](https://user-images.githubusercontent.com/25768712/75338789-97e29d00-588f-11ea-9af1-0264ac08ef9c.png)

None of my paths have any spaces or other problematic characters in them as far as I have checked.

I have tried the following solutions/suggestions without success:

https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/89
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/104
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/113

Regarding the setup of the trackers I followed the instructions given in issue 89. Any suggestions on how to fix this are welcome

Thank you

**Comment by 1runeberg** [comment]
Hi @MWaerzner,

For 4.24, the vive tracker support is a bit limited, but you can easily set the camera role as in this demo video:

https://youtu.be/nL61ZsXk1xc

If you need additional tracker roles, you need to generate or copy the camera json under the SteamVRBindings folder. 

For instance, in your steamvr_manifest json, make sure you have a corresponding link to the tracker json:
![image](https://user-images.githubusercontent.com/17371351/75379985-610d9500-592a-11ea-9e77-eec64004f531.png)

Then look at vive_tracker_camera.json and you can pattern the other roles from this, save a new file and update the steamvr_manifest file. One other caveat is you might need to set the steamvrmanifest file to read-only afterwards so UE won't overwrite it.

We understand this is less than ideal, but in an upcoming 4.25 release candidate for the plugin, the vive tracker support is much improved and you wouldnt need to do any manual binding or json manipulation, see WIP of this in the following demo vid:

https://youtu.be/AZMOl1Ik8Rk

I hope that helps.

Cheers,
Rune

**Comment by MWaerzner** [comment]
Hi again,

thanks for the response. I did some further testing and found out something interesting:

I listed all the tracked motion sources using blueprint.

![image](https://user-images.githubusercontent.com/25768712/75427859-8b218000-5947-11ea-9cff-6561ea121a98.png)

I found that Special-5 is tracking. So configuring the input using SteamVR input seems to be working.

![image](https://user-images.githubusercontent.com/25768712/75427347-9fb14880-5946-11ea-8129-5054ad765609.png)

But as seen here the Tracker position is correct in the SteamVR Dashboard but in my unreal project the tracker is at the pawns origin not tracking at all. I marked the correct tracker position.

![Screenshot 2020-02-27 07 53 04](https://user-images.githubusercontent.com/25768712/75428616-c2dcf780-5948-11ea-90f1-a2f7a0d3ad89.png)

Any ideas why this is happening?  I also tested a fresh VR Template with a simple MotionController actor and it also did not work.

**Comment by MWaerzner** [comment]
If I use "Get Tracked Device Position and Rotation" per tick to get the tracking data it works... why does it not work when using the motion controller component? This seems odd to me.

![image](https://user-images.githubusercontent.com/25768712/75435172-f0c73980-5952-11ea-9965-e73af1abae8f.png)

**Comment by MWaerzner** [comment]
Update: Found the issue. The object owning the Motioncontroller Component MUST be spawned so that the VR Pawn with the specified player index is its owner. That was not the case in 4.21. Wish there was proper documentation on this stuff... Case dismissed.
