### ISSUE TITLE
Using "Find Steam VR Origin Tracked Device Info" with Vive Pro controllers returns "Other"?

### ISSUE THREAD

**Issue by bbishop86** [ValveSoftware/steamvr_unreal_plugin#129]
As suggested I'm using the "Find Steam VR Origin Tracked Device Info" node to detect which controllers are being used. I'm changing how input is handled when the player is using certain controllers so I really need to know which are the right ones. However when using Vive Pro controllers it returns nothing.

edit: I forgot "other" was the output of my function not the node lol. Now I've gone back to my index controllers and restarted everything but it's still not working, it worked fine before :/

**Comment by bbishop86** [comment]
After this it stopped working completely, and now it's back to working. Not sure but I guess it got confused when I was switching between using Vive and Index controllers.

**Comment by 1runeberg** [comment]
Hi @bbishop86 - Is the action being triggered prior to the node being called?

Action specified in the node needs to be triggered first -- if that's not convenient, you might want to hook up to a dummy action you map for this purpose. You can use Trigger Touch, Trackpad Touch, or any other inputs that your player would naturally trigger.

**Comment by bbishop86** [comment]
> 
> 
> Hi @bbishop86 - Is the action being triggered prior to the node being called?
> 
> Action specified in the node needs to be triggered first -- if that's not convenient, you might want to hook up to a dummy action you map for this purpose. You can use Trigger Touch, Trackpad Touch, or any other inputs that your player would naturally trigger.

Yeah, I was using the left grip action and after I set the node to be called on tick I realised it wasn't working until I actually pressed grip. I will have another look at it today and hopefully find a workaround.

**Comment by bbishop86** [comment]
OK I fixed it. What I did was instead of waiting for the player to trigger the action, I used the "Simulate key press" node from Rama's Victory plugin to make sure it always happens immediately.

**Comment by 1runeberg** [comment]
Thanks for the update and sharing @bbishop86 . Good 'ol Rama! :)
