### ISSUE TITLE
SteamVREditor.Build.cs has warnings when GenerateProjectFiles.bat is run

### ISSUE THREAD

**Issue by martinsweitzer** [ValveSoftware/steamvr_unreal_plugin#13]
Adding       ModuleDirectory +  allows the plugin directory to be placed where ever it needs to go

        PublicIncludePaths.AddRange(
            new string[] {
                "Public"
            }
            );

        PrivateIncludePaths.AddRange(
            new string[] {
                "Private",
            }
            );

should be:

        PublicIncludePaths.AddRange(
            new string[] {
               ModuleDirectory + "/Public",
            }
            );

        PrivateIncludePaths.AddRange(
            new string[] {
                 ModuleDirectory + "/Private",
            }
            );

**Comment by 1runeberg** [comment]
Hi @martinsweitzer - is this because you have addtl subdirectories for the plugin tree?

**Comment by martinsweitzer** [comment]
\depot_squanch\EZBake\Engine\Plugins\ThirdParty\SteamVRInput\Source\SteamVREditor\SteamVREditor.Build.cs: warning: Referenced directory 'C:\depot_squanch\EZBake\Engine\Source\Public' does not exist.
C:\depot_squanch\EZBake\Engine\Plugins\ThirdParty\SteamVRInput\Source\SteamVREditor\SteamVREditor.Build.cs: warning: Referenced directory 'C:\depot_squanch\EZBake\Engine\Plugins\ThirdParty\SteamVRInput\Source\Private' does not exist.

is what ends up trying to include

the other build.cs files have this syntax:  

        PublicIncludePaths.Add(Path.Combine(ModuleDirectory, "Public"));
        PrivateIncludePaths.Add(Path.Combine(ModuleDirectory, "Private"));


Which is basically the same thing as the ModuleDirectory + "/    "   from above

**Comment by 1runeberg** [comment]
ah gotcha. thanks for the clarification.

The editor module was done initially in 4.15 where the other modules were downgraded from 4.21, module base was generated from the UE Editor iirc - need to make them consistent then. Thanks!

**Comment by 1runeberg** [comment]
This is now addressed in develop. 

any further issues on this, please just let me know. Cheers.
