### ISSUE TITLE
Oculus Touch bindings not showing up

### ISSUE THREAD

**Issue by elitenas** [ValveSoftware/steamvr_unreal_plugin#131]
I am trying to setup Axis mappings for my oculus touch.... i have them listed here:

![Screenshot_4](https://user-images.githubusercontent.com/50789023/76861745-10070780-682b-11ea-85e2-91c705d53603.png)

Then when I go to steamvr binding :

![Screenshot_5](https://user-images.githubusercontent.com/50789023/76862385-08942e00-682c-11ea-951d-8380a2adfc47.png)

I don't see Move_Y there at all. I am on UE4.24. It seems when I change the binding to 
![image](https://user-images.githubusercontent.com/50789023/76862080-8c014f80-682b-11ea-8d82-6726e989c91c.png) then it shows up. Any idea why?

**Comment by 1runeberg** [comment]
Hi @pixelcitystudio - Thanks for reaching out!

Just form the screenshots alone, it looks like the Move_Y is bound, but the one that's concerning is Strafe_X and Rotate_X, they should have also been bound.

Are you able to share the steamvr_manifest.json and your oculus_touch.json files? If you're not comfortable posting them here, you can send them to runeb@valvesoftware.com

**Comment by 1runeberg** [comment]
Hi @pixelcitystudio - Do you have corresponding Y axis actions for Rotate and Strafe?

They need to all be paired with corresponding X & Y actions for the thumbsticks to be bound properly by SteamVR.

Move_Y shouldn't actually appear, but you should have a bound thumbstick action called "Move"

**Comment by elitenas** [comment]
That made it work! Thank you! One quick question... on vive, you can't bind to System Key then why is there?

**Comment by 1runeberg** [comment]
Glad you got it working now @pixelcitystudio :)

The keys are based primarily on OpenXR keys (6.4.4):
https://www.khronos.org/registry/OpenXR/specs/1.0/html/xrspec.html

Some applications may not have access to it, but we're supporting the path at least.
