### ISSUE TITLE
WMR.json? Bindings?

### ISSUE THREAD

**Issue by uno1982** [ValveSoftware/steamvr_unreal_plugin#132]
Rune,

After migrating from 4.22.3 to 4.24.3 I've noticed that I'm not seeing a WMR binding or json file at all? 
![snapright](https://user-images.githubusercontent.com/45907836/77021597-29a46e00-6955-11ea-8452-5065a7eb9dea.PNG)

![bindings](https://user-images.githubusercontent.com/45907836/77021562-08dc1880-6955-11ea-9208-d504770c28a2.PNG)
![json](https://user-images.githubusercontent.com/45907836/77021565-0b3e7280-6955-11ea-9cc4-6365e5fd8649.PNG)

**Comment by 1runeberg** [comment]
Hi @uno1982 - "Mixed Reality" is the WMR... and "holographic_controller.json" is the corresponding json file.

**Comment by uno1982** [comment]
Thanks for the clarification on that! 😊How would one go about setting the dev defaults in steamvr? Would I only be able to do this through the json since I don’t have the physical controller?

**Comment by 1runeberg** [comment]
The plugin generates for all supported controllers (where the dev has bound them in the UE4 UI) and will be set as the defaults.

If you are asking about WMR specifically, you need to download the driver from Steam so you can see it as an option in the SteamVR Dashboard.

**Comment by 1runeberg** [comment]
@uno1982 - are you still having issues with WMR?

**Comment by uno1982** [comment]
No you can close this. Not an issue per say just didn't know which json was used for that controller profile. Thanks again.
