### ISSUE TITLE
UE 4.23 Teleport sowing sphere instead of path

### ISSUE THREAD

**Issue by Fidom** [ValveSoftware/steamvr_unreal_plugin#134]
I'm using UE 4.23 and downloaded the Steam Vr template form Github and used the marketplace install. Now i added the MotionControllerPawn in a new scene connected the VR hands and animations. the controllers and tracked but there is no teleport path visible. It looks now like a sphere. The problem is that i can only move like 1 meter and not teleport further away. 

![SteamVR_UE4 23](https://user-images.githubusercontent.com/18272960/77257095-6d0f1d00-6c72-11ea-9a3b-65857890a09e.png)

**Comment by 1runeberg** [comment]
Hi @Fidom that looks like a navmesh issue in your scene? Is our test scene working properly?

**Comment by Fidom** [comment]
Thanks for helping, I indeed think its the navmesh but i copied everything exactly form the test scene tot my own one. In the test scene its working but in my own one not. Here is a screenshot and the log:

[UR_VR_Log.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/4372038/UR_VR_Log.txt)

![UE_VR_Screen](https://user-images.githubusercontent.com/18272960/77366024-6f977280-6d57-11ea-87d7-653aed0d512b.png)

**Comment by 1runeberg** [comment]
Hi @Fidom - this doesn't seem like an issue with the plugin. is your scene working when you use the VR Template? We didn't implement our own teleport, it simply uses the same one from the Epic Template.

Another thing you can check for though is anything in your scene (or pawn/character) causing block collisions that may block the teleport beam.

Also check what mesh that beam is actually using/set to.

**Comment by Fidom** [comment]
Hi @1runeberg , thank you very much. The "ProceduralFoliageVolume" was the problem. Its causing the collisions because the collision presets was on custom, when i put it on NoCollision it works perfectly. 

Everything works fine now! 

Thank!

**Comment by 1runeberg** [comment]
awesome! glad you got it sorted! :)
