### ISSUE TITLE
Can't Access Dashboard (for project)

### ISSUE THREAD

**Issue by SinnStudio** [ValveSoftware/steamvr_unreal_plugin#135]
I'm unable to use the dashboard for my project specifically. I can access it for SteamVR and other apps, but not my own Unreal Engine project. A friend of mine is able to access his just fine, and if I use his config files, I can access mine (but with his inputs, of course). No errors, the page just never loads for my project.

I've made no changes to the configs and did everything he did step by step.
Attached a screenshot of the console log when trying to load it.

![ConsoleLog](https://user-images.githubusercontent.com/27145091/77769494-4eb27400-701a-11ea-8e40-50f445a9d428.png)

**Comment by 1runeberg** [comment]
Hi @SinnStudio - Are you able to open the dashboard for your project otherwise using SteamVR? 

![image](https://user-images.githubusercontent.com/17371351/77795630-0484cd80-70c2-11ea-803f-9c763ff9432a.png)

![image](https://user-images.githubusercontent.com/17371351/77795647-09498180-70c2-11ea-9472-698f60d8e7b6.png)

**Comment by SinnStudio** [comment]
It shows up as **GAMENAME-0 [UE EDITOR]** in the "Show Old Binding UI" menu, but clicking on it doesn't do anything. Clicking the other options (for other installed games [including this one directly from Steam library]) does work. 

I'm also now no longer able to see the main dashboard via the URL. This worked before. But even when it did work, I couldn't click on my own UE game.

The URL I'm referring to: _http://localhost:27062/dashboard/controllerbinding.html?app=application.generated.ue.medieval-0.ue4editor.exe_

**Comment by 1runeberg** [comment]
Hi @SinnStudio - could be a browser issue, can you try clearing your browser cache and/or try with different browsers or incognito mode?

**Comment by SinnStudio** [comment]
I did try it with a different browser, cleared caches and incognito mode but no luck. The fact that it doesn't work via the old binding UI either does hint at a different problem altogether

**Comment by 1runeberg** [comment]
also, try removing any entries with "ue4" in your {X}:\Program Files (x86)\Steam\config\steamvr.vrsettings

**Comment by 1runeberg** [comment]
since the problem is local to your machine it could be config related as well, so have a look at you documents and appdata and clear any project entries.

**Comment by SinnStudio** [comment]
<details><summary>The **steamvr.vrsettings** file doesn't seem to have any entries with "UE" in them. This is what's inside:</summary><p>

```
{
   "DesktopUI" : {
      "controllerbinding_desktop" : "181,233,1504,601,0",
      "pairing" : "568,271,800,600,0",
      "settings_desktop" : "711,281,800,600,0"
   },
   "GpuSpeed" : {
      "gpuSpeed0" : 669,
      "gpuSpeed1" : 670,
      "gpuSpeed2" : 670,
      "gpuSpeed3" : 665,
      "gpuSpeed4" : 761,
      "gpuSpeed5" : 670,
      "gpuSpeed6" : 665,
      "gpuSpeedCount" : 7,
      "gpuSpeedDriver" : "26.21.14.4259",
      "gpuSpeedHorsepower" : 668,
      "gpuSpeedRenderTargetScale" : 1.5,
      "gpuSpeedVendor" : "NVIDIA GeForce GTX 1080",
      "gpuSpeedVersion" : 2
   },
   "LastKnown" : {
      "HMDManufacturer" : "Oculus",
      "HMDModel" : "Oculus Rift CV1"
   },
   "steamvr" : {
      "installID" : "7072478241135650523",
      "lastVersionNotice" : "1.10.32",
      "lastVersionNoticeDate" : "1584997241",
      "showAdvancedSettings" : true
   }
}
```

</p></details>

**Comment by SinnStudio** [comment]
I re-installed the OS recently so my C drive was wiped, but this was a problem before and after the reformat. In my Documents folder, the "steamvr" folder has an "inputs" folder, but it's empty.

**Comment by 1runeberg** [comment]
other things to look  out for:

(1) Any other VR Tools installed that may interfere with SteamVR that your friend doesn't have installed
(2) You can remove entries for your app if it is in here:
{X}:\Program Files (x86)\Steam\config\steamapps.vrmanifest
(3) Reinstall SteamVR
(4) %APPDATA% .. in Local, try removing SteamVR and your UE4 Project caches in here
(5) Backup then Delete your Config\SteamVRBindings folder, restart the Editor to regenerate

It's odd though if you have had a full OS and apps reinstall... is this Windows 10?

Also if you can check in the Console Log where the plugin is trying to load the action manifest from and make sure it is pointing to your local project directory and this is the one autogenerated by the plugin - it seems like your project doesnt have the correct controller binding for some reason or it isn't set properly in the action manifest.

Failing all that, send me your friend's UE project config directory for the same project as well as yours plus the uprojectfile and I can have a look for ya -- runeb@valvesoftware.com

**Comment by SinnStudio** [comment]
Oculus Home launches every time SteamVR launches (I have a Rift set up currently), could that be it? I'm trying the other things you suggested but no luck so far, will post back if that changes

**Comment by SinnStudio** [comment]
I think it's working now (after trying your 4th suggestion)! I can get into the dashboard and the project there properly.

Thanks for your help!

**Comment by SinnStudio** [comment]
I'm not sure how to mark this as Solved

**Comment by 1runeberg** [comment]
That's great to hear @SinnStudio ! and thanks heaps for updating us on hte results :)

Closing esp. by the user means it's resolved (at least from our perspective). Will close this for you since you've confirmed :) 

Cheers,
Rune

**Comment by SinnStudio** [comment]
Hey, I deleted that last comment just to avoid confusion but here's what's going on:
- I can now get into the dashboard and the project there fine, but
- None of my inputs show up. All the values are default.

I tried:
- Deleting the configs and regenerating

**Comment by 1runeberg** [comment]
HI @SinnStudio - Can you change the name of your project in Project Settings > Project Name as a quick test and restart the Editor?

**Comment by SinnStudio** [comment]
No luck. I'm also unable to access the project via the dashboard again.
_Sent you an email with my configs, just in case_

**Comment by 1runeberg** [comment]
Offline Ticket Update as reference for others who might encounter the same issues in the future:

Three Identified Issues:

**(1) Possible corrupted steamvr htmlcache or incorrect/outdated actionmanifest causing Dashboard viewing issues.**

Resolution:  In %APPDATA% .. /Local, try removing SteamVR and UE4 Project caches 

**(2) Action Names have special characters ( / in particular)**

Resolution: Remove special characters in Action Names under Project Settings > Input
Enhancement (Future Versions): Ignore special characters in json generation

**(3) Vector2s not showing in Inputs:**

Potential Resolution:
For Vector2s (X,Y axes)... Along with having _X & _Y in the names, another thing to note is that your controller inputs in Project Settings > Input must also match (at this point, please don’t use the MotionController abstraction if you are using UE 4.23 and below but rather specific controller inputs), like so:

**Move**\_X
    OculusTouch\_**Left**\_Thumbstick\_**X**
    
**Move**\_Y
     OculusTouch\_**Left**\_Thumbstick\_**Y**

You can then split the X & Y axes in your BP and use them as needed. You can grab our sample projects here to see some sample usage:

Sample project (UE4.15-4.23):    https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin.zip   
Sample Project (UE.424+): https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

**Comment by SinnStudio** [comment]
What Rune wrote above this is your best bet if you run into this problem. Problem solved, everything works! Thanks, Rune.

**Comment by SinnStudio** [comment]
Hey Rune,

I’m not able to get my Oculus Touch controllers to track in-engine using SteamVR.
In a shipping build it seems to work fine, my Rift testers had no problem, and other games work fine for me via SteamVR, too.

What I have tried:

  *   Disabling Oculus VR plugin, keeping SteamVR only
  *   Deleting the project’s appdata files
  *   Deleting the SteamVR file in configs
  *   Regenerating everything
  *   PC restart
  *   Project restart
  *   SteamVR restart
  *   Firmware update check (not needed)

Unreal engine 4.24

**Comment by 1runeberg** [comment]
@SinnStudio - Opened a new ticket for this so it doesn't get mixed up with this one.
