### ISSUE TITLE
UE4 Default Mannequin Left Hand not working properly

### ISSUE THREAD

**Issue by elitenas** [ValveSoftware/steamvr_unreal_plugin#137]
Hi,

I am trying to setup steamvr hands on my character. I got the right hand to work properly but the left hand is having issues.

The left hand seems to be animating the wrong way
![image](https://user-images.githubusercontent.com/50789023/78599199-52ae7500-7816-11ea-87f6-cd572471557e.png)

This is making my IK blend the arm area backwards.

This is what i have for it. Do I need to do transform bone or anything?
![image](https://user-images.githubusercontent.com/50789023/78599010-f51a2880-7815-11ea-8fde-c8a8de1968cf.png)

How can I make it work with ue4 default Mannequin right hand mesh. I tried rigging a left hand as well for this from ue4 Mannequin but it was even worse

**Comment by 1runeberg** [comment]
Hi @pixelcitystudio - can you try putting a -1 scale in the Z (leave X & Y to +1) for the mesh?

**Comment by elitenas** [comment]
Nope... no effect on my arm...

![image](https://user-images.githubusercontent.com/50789023/78602980-f1d66b00-781c-11ea-8635-da621bf1fae8.png)

My left arm is backwards.... The ik seems to be interfering with my left hand/arm

This is my animbp

![image](https://user-images.githubusercontent.com/50789023/78603095-24806380-781d-11ea-9edc-41f72e336260.png)

![image](https://user-images.githubusercontent.com/50789023/78603109-2a764480-781d-11ea-8f29-725e19e5aa17.png)

**Comment by elitenas** [comment]
This is my rig... for ue4 left hand mesh https://cdn.discordapp.com/attachments/609876675005775882/696802066907267183/MannequinHand_Left_Proper_V2.fbx

**Comment by 1runeberg** [comment]
Hi @pixelcitystudio - the anim nodes that came with the plugin only support the standard SteamVR and UE4 skeletons, that is, using the right hand UE4 mesh with the correct skeleton applied, and applying a -1 Z  on the scale (Static Mesh Component in UE4) to flip it to become the left hand.

Have you had a chance to check our sample projects? The UE4Hands sample map demoes using hte standard UE4 skeleton:

Sample project (UE4.15-4.23):    https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin.zip  

Sample Project (UE.424+): https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

**Comment by elitenas** [comment]
Got it to work without IK with Y = -1 but with IK... its messing up still. Have you tried it with a body IK system?

**Comment by 1runeberg** [comment]
No, we haven't tested with any IK System internally. Although there are titles that use them and the plugin.

You'd have to check with the IK System you are using or your own IK code for troubleshooting, this would be outside the scope of our support unfortunately.
