### ISSUE TITLE
4.24 SteamVR Motion Controller Material

### ISSUE THREAD

**Issue by elitenas** [ValveSoftware/steamvr_unreal_plugin#139]
I have a problem with the show controller model option in motion controller component, in the editor I see the right material, but in a packaged game, the material is missing. It was fixed in 4.23 but I think it came back in 4.24. Is this a known bug?

**Comment by 1runeberg** [comment]
Hi @pixelcitystudio - this may be a better issue raised in UDN/AnswerHub:
https://answers.unrealengine.com/index.html

As this is more engine implementation than with the input module/plugin :)
