### ISSUE TITLE
Unable to Use Valve Index Thumbstick Bindings

### ISSUE THREAD

**Issue by Skeltpr** [ValveSoftware/steamvr_unreal_plugin#142]
Using Unreal Engine 4.24.3.

Currently cannot replicate any functionality for Thumbsticks on the Valve Index controllers. I've tried my best to follow the guidelines outlines in on this github and the wiki, but have had no avail.

First I set up my project axis bindings:
![One](https://user-images.githubusercontent.com/30379969/80764323-6e9ff080-8b0e-11ea-8089-275c1cd4474b.PNG)

Next I go to SteamVR Input and Regenerate Action Manifest, Controller Bindings, Reload Action Manifest.

Afterwards, I implement the Vector Axis Binding in my code:
![Two](https://user-images.githubusercontent.com/30379969/80764415-ac9d1480-8b0e-11ea-9661-1ccde2798eee.PNG)

However, upon running the game, even though inputs like my Triggers or A/B buttons work, and I can clearly view the game in VR and my Index controllers in VR, I am unable to change the output of the code. It always remains 0, 0, 0:
![Three](https://user-images.githubusercontent.com/30379969/80764523-da825900-8b0e-11ea-9a87-84e600434968.PNG)

Assuming I have not missed anything, I believe this is a bug.

**Comment by 1runeberg** [comment]
Hi @Skeltpr - vector inputs arent yet fully implemented in the engine afaik so i wouldnt be relying on that at this time.

At any rate, the plugin itself isnt using vectors because of Epic advice. you need to use individual X, Y axes inputs as usual in UE. the plugin does the vector conversion for openvr and then splits them back again going back to the engine.

**Comment by Skeltpr** [comment]
Ahh! Thank you for the quick response!

However, that is what I tried the first time, and I had no success. I tried it again just now, and I'm afraid I've been left with the same results as before. Is there anything else I could be overlooking?

![OneOne](https://user-images.githubusercontent.com/30379969/80765828-fc310f80-8b11-11ea-951c-18fa67f8a6d6.PNG)

![OneTwo](https://user-images.githubusercontent.com/30379969/80765835-fe936980-8b11-11ea-8a85-0089a91e95c8.PNG)

(Like before, I'm moving the thumbstick all around, but the console output does not change at any point)
![OneThree](https://user-images.githubusercontent.com/30379969/80765852-0a7f2b80-8b12-11ea-951a-4ec53a1e1a8b.PNG)

**Comment by 1runeberg** [comment]
the action names should still have the _X & _Y similar to the first input screenshot you had. this is how the plugin recognizes if the dev wants a vector input. 

make sure your action names are consistent as well in your code.

you can also have a look at the sample 4.24 project to see how it should look all setup as described in the wiki:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

also good to compare against your project input setup/settings.

**Comment by Skeltpr** [comment]
Thank you for your patience. It is now working properly. I could've sworn I tried this already, but perhaps I forgot to Regenerate/Reload the SteamVR Inputs. Apologies for taking your time.

For anyone else having trouble and reading this in the future, here's my exact setup:

![FourOne](https://user-images.githubusercontent.com/30379969/80766801-41eed780-8b14-11ea-91d2-8f5b167a6db5.PNG)

![FourTwo](https://user-images.githubusercontent.com/30379969/80766805-43b89b00-8b14-11ea-8833-498aa40636da.PNG)

Thank you once again @1runeberg :)

**Comment by 1runeberg** [comment]
awesome! glad its sorted.. could just be the action names you had in the CPP end were different (i think they were in your first screenshot at least).
