### ISSUE TITLE
Main Game Actions Not Listing in SteamVR Browser Dashboard

### ISSUE THREAD

**Issue by OptimisticMonkey** [ValveSoftware/steamvr_unreal_plugin#143]
I can see the correct actions in steamvr_manifest.json, but cannot assign them in the browser ui because they are not listed  :-(

Thanks for any help

**Comment by 1runeberg** [comment]
Hi @OptimisticMonkey  - which headset and version of the engine are you using. Also, do you get any errors in the Output Log after doing an Editor Preview?

**Comment by OptimisticMonkey** [comment]
Using 4.24 with Valve Index and Knuckles..

And I do get this error:
 Error: [STEAMVR INPUT] Setting Action Manifest Path to: Mismatched Action Manifest
LogSlate: Window 'Plugins' being destroyed

Thanks 1runeberg
How to fix?

**Comment by OptimisticMonkey** [comment]
I also get:
LogSteamVRInputDevice: Error: Error trying to generate application manifest

**Comment by 1runeberg** [comment]
Hi @OptimisticMonkey - Thanks for the update.

Can you try the steps in here and lemme know how it goes:
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/113#issuecomment-590543108

**Comment by OptimisticMonkey** [comment]
Thanks - Will do - I bet its Perforce locking the files steam vr needs.. will test

**Comment by 1runeberg** [comment]
if you're using perforce, you can (and should) add in your p4ignore the app manifest (Config\steamvr_ue_editor_app.json). We're moving this file in Saved in the next release.

**Comment by OptimisticMonkey** [comment]
ahhh - that was exactly the issue i was having - Thanks 1runeberg!

**Comment by 1runeberg** [comment]
Closing now, please feel free to comment or re-open if needed :)

Cheers,
Rune
