### ISSUE TITLE
On steamvr tracking initialization event

### ISSUE THREAD

**Issue by uno1982** [ValveSoftware/steamvr_unreal_plugin#144]
Rune,

I’ve been working with the plugin a while and in 4.24.3 I’m detecting the hardware I’d of the steamvr controllers to setup grip profiles for wands vs index controllers (toggle vs releases) the issue is that my check fails on possession if the controller id is invalid due to not being on or tracking isn’t ready on possession. Are you aware of an event or delegate I can bind that fires when steamvr detects a tracked controller ID is available and valid that I can use instead of relying on begin play or possession?

**Comment by 1runeberg** [comment]
Hi @uno1982 - we  recommend using the new input system to detect controller types and not directly dealing with device ids:
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/97
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/129

It requires an action to be triggered and you can use that event, an axis (automatically triggers on every change) or key event thats likely for a player holding a controller to be triggered can be used, or manually trigger one at an appropriate time/s in your game, you should normally need to be able to detect the controller only once in a session.

**Comment by uno1982** [comment]
Rune,

Thanks for the speedy reply. I ended up using trackingstatechanged event and when tracking results in true it looks to understand what controller profile i'm dealing with for handling my toggle/release grip behavior. What event were you mentioning?

Below is my example
https://cdn.discordapp.com/attachments/575076664132763653/709840668121497750/unknown.png

**Comment by uno1982** [comment]
Rune, 

Also I'd agree that I probably need to move my detection out of the character and into a place like gameinstance so i'm not constantly checking and resetting this on state change.

**Comment by 1runeberg** [comment]
> Rune,
> 
> Thanks for the speedy reply. I ended up using trackingstatechanged event and when tracking results in true it looks to understand what controller profile i'm dealing with for handling my toggle/release grip behavior. What event were you mentioning?
> 
> Below is my example
> https://cdn.discordapp.com/attachments/575076664132763653/709840668121497750/unknown.png

glad you got it sorted. the OpenVRHMDType, isnt part of our plugin. We recommend using the new input system over the legacy device ids. The events are just your standard input events that you can define.

have a look at the samples in the following issues:
#97
#129

**Comment by uno1982** [comment]
Yeah I'm just using OpenVRHMDType to get the HMD to determine if I even need to check controllers. I use GetControllerDeviceID XRDeviceID to pass the modelnumber. I do this because I try to keep as many things capable of being brought over to Oculus SDK and Store and reliance only on steamvr returned identifiers would have to be re-done.
