### ISSUE TITLE
Please Help! Bindings not working in Packaged build

### ISSUE THREAD

**Issue by Dual-Perception-Games** [ValveSoftware/steamvr_unreal_plugin#145]
Hi guys,

I have a really odd issue going on with the plugin. If I create custom bindings everything works in Unreal Engine but nothing works in my packaged build.
If I use the sample bindings everything works in the packaged build but only on Vive.

I have been pulling my hair out trying to resolve this issue as I have a finished game that I cant release because of this one plugin.

I do also admit that I´m not a seasoned developer by any stretch of the imagination and am aware that the problem could well be between chair and keyboard.

Engine Version 4.22
Blueprint project
Market place Steam VR Input plugin. 

Thanks for any help you can offer on this as I´m somewhat desperate.

Dave

**Comment by 1runeberg** [comment]
@DefPenGames - Can you check if you have the Config\SteamVRBindings folder in your packaged build?

**Comment by Dual-Perception-Games** [comment]
Hi 1Runeberg,  it turned out to be the Oculus VR plugin was running. I have no idea why as I don't actually own any Oculus products.

So, it seems that it now works on both Vive and Oculus test machines. however, it still does not work on my own PC, the machine it was developed on. Any idea as to what would cause this behaviour as I'm all set to launch but would really like to be able to double check everything in the Steam Version of the game myself.

Thanks for your time.

Dave

**Comment by 1runeberg** [comment]
Hi @DefPenGames - have a look at %APPDATA%, check AppData\Local and see if your title appears here - you can delete the folder that's named after your game to refresh the bindings.

**Comment by 1runeberg** [comment]
closing issue based on offline conversation/confirmation
