### ISSUE TITLE
Having OculusSDK and SteamVR both enabled together

### ISSUE THREAD

**Issue by elitenas** [ValveSoftware/steamvr_unreal_plugin#146]
Hi,

A few of the devs and I are having issue with both plugins (OculusSDK and SteamVR enabled at the same time).

When the game launches and you get the option:

![image](https://user-images.githubusercontent.com/50789023/83986280-d9103180-a901-11ea-98e3-d8639a7553b0.png)

Regardless of what we select... we launch with Oculus. Unless, we disable OculusSDK... then we  launch into SteamVR. Is there a way for us to enable both and give the player an option to select?

This worked fine before 4.24 release.

**Comment by elitenas** [comment]
@1runeberg I understand that we can override these in the config but then we are overriding it for the user. Ideally, the player should be given the option. Otherwise, what is the point of this dialog box?

**Comment by 1runeberg** [comment]
Hi @pixelcitystudio - I just tested this and the platform selection seems to work fine in various versions of the engine includign the latest ones (4.25).

Can you verify if you have your command line arguments set properly to the correct plugin in Steamworks like so:

![image](https://user-images.githubusercontent.com/17371351/84109934-34a7ff80-aa67-11ea-9a53-1e9603c43068.png)

**Comment by elitenas** [comment]
I tried those exact commands in 4.24.3 and it didn’t seem to work. All the other devs I mentioned are on 4.24.3 as well.

**Comment by 1runeberg** [comment]
Not sure, I've tested in various engine versions already including published in Steam with the vanilla engine template, and results are fine/as expected.

You may want to check if there are other plugins that may be interfering with the command line params and plugin load sequence. Other avenues you may want to check is if your project can actually run with both plugins enabled (i.e. no issues with any code or nodes that are platform specific).

A quick way to verify which plugin is running if you aren't already, is look for LogHMD in the logs and what it reports as the runtime platform.

However, you might need to open a ticket with Epic for specific support on your project (e.g. via UDN) if this continues to be an issue on your project as this is really outside the scope of the plugin support or Steamworks. 

Ultimately we dont dictate loading sequence based on those command line parameters, the engine needs to load the correct plugin and this is outside our control as long as we call the arguments correctly from Steam and the binaries are correctly uploaded.

**Comment by 1runeberg** [comment]
Sorry for clarity, yes, one of the versions I tested is 4.24.3 (Epic Games VR Template with both SteamVR & Oculus plugins enabled):

![image](https://user-images.githubusercontent.com/17371351/84115584-a422ec80-aa71-11ea-8cda-4b0ad1a18200.png)

![image](https://user-images.githubusercontent.com/17371351/84115658-c0bf2480-aa71-11ea-8904-28b20f9c8fa8.png)

**Comment by 1runeberg** [comment]
And just in case this is related to what you are seeing, please note the following known engine issue in 4.24 builds (true for any controller):
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/112

Summary: make sure you manually copy all the json files in the Config/SteamVRBindings folder in your build for input to work. Epic has resolved this in 4.25.

**Comment by pixelcitystudio** [comment]
@1runeberg I can confirm this bug doesn't happen on packaged build when you create a shortcut and add the -hmd argument to the shortcut. However, I tried on SteamVR again and it defaults to oculus there. Would it be possible for you to test this on steamvr with 4.24.3 build? It would help to know if this is indeed fixed in 4.25.

![image](https://user-images.githubusercontent.com/50789023/84187433-a9733d80-aa57-11ea-8935-dc873a23270c.png)

**Comment by pixelcitystudio** [comment]
To take it a step further... i printed out the arguments passed in while launching the game:

![image](https://user-images.githubusercontent.com/50789023/84199725-42f81a80-aa6b-11ea-9bbf-61fb2433e562.png)
and It came blank

![image](https://user-images.githubusercontent.com/50789023/84199755-4db2af80-aa6b-11ea-9ff9-f9f181b50274.png)

While in a regular packaged build... the argument comes as steamvr or oculus

This is an issue with steamworks then. Who can I contact about this issue?
