### ISSUE TITLE
Launching with -nohmd still launches SteamVR input (UE 4.21)

### ISSUE THREAD

**Issue by rproepp** [ValveSoftware/steamvr_unreal_plugin#148]
I've recently switched to using the SteamVR input plugin from using legacy input in UE 4.21. Before, when using the -nohmd command line option, SteamVR didn't start when the game starts. But since I've started using the plugin, SteamVR always starts even with -nohmd.

My game can be played on screen and in VR, so that behavior is annoying for users who own a headset but want to play on screen.

**Comment by 1runeberg** [comment]
Hi - the nohmd option will depend on the engine and we dont have any control on this due to the way the marketplace plugin is setup. you need to try and upgrade to the integrated version from 4.24 if you need any of the more integrated commandline options from the engine.

**Comment by rproepp** [comment]
I've upgraded to 4.25.4 now, but the issue persists. There are a couple of issues and PRs here and on the Unreal Engine repo, so I'm not sure what the status is. 

https://github.com/EpicGames/UnrealEngine/pull/6582 looks like it should fix the issue? But https://github.com/EpicGames/UnrealEngine/pull/6980 is still open. Does that mean it is still not fixed in master (and the launcher version), but applying PR 6980 should get rid of the problem?

**Comment by 1runeberg** [comment]
Hi @rproepp - unfortunately as mentioned in #106, we dont have any control on this, our PRs were added on 4.26, not 4.25  but they only cover input and doesnt have any relation to the hmd/xr boot up process in the engine. please report this  issuedirectly via official Epic channels.

**Comment by 1runeberg** [comment]
@rproepp - please see Issues #157  and #106 for more info
