### ISSUE TITLE
X and Y touch events for the Oculus Touch controller are mapped as clicks in steam

### ISSUE THREAD

**Issue by joticarroll** [ValveSoftware/steamvr_unreal_plugin#152]
**Affected Versions:** 4.25.1

**Steps to reproduce:**
1.) Download SteamVRInputPlugin_UEIntegrated example project
2.) Open the project and go to the Input section of the project settings.
3.) Create a new action and add "Oculus Touch (L) X Touch" or "Oculus Touch (L) Y Touch" to it.
4.) Save the project.
5.) Go to the Steam section of the project settings and click the "Launch SteamVR Bindings Dashboard"
5.) Check the mapping for the X or Y buttons

**Results:** Actions are mapped as Click.

**Expected Result:** Actions should be mapped as Touch.

**Crash?:** No

**Comment by 1runeberg** [comment]
Addressed in: https://github.com/EpicGames/UnrealEngine/pull/7073

**Comment by 1runeberg** [comment]
This is now fixed in 4.26, thanks for reporting!
