### ISSUE TITLE
Is it possible to listen to SteamVR Actions?

### ISSUE THREAD

**Issue by jdevoldere** [ValveSoftware/steamvr_unreal_plugin#155]
In Unity you can do this with AddOnChangeListener on a SteamVR_Action_Boolean but there doesn't seem to be an equivalent in Unreal.

**Comment by 1runeberg** [comment]
Hi @jdevoldere - Can you elaborate on what you are wanting to achieve? The Key and Axis Input Action events in unreal should catch boolean action changes, as they are events.

You can also put any boolean action into an Axis Action mapping and that'll give you a constant feed of the value if you do want to manually monitor this.

**Comment by jdevoldere** [comment]
@1runeberg Ah, you're right my bad. I got confused because it works differently from the way it works in Unity.
