### ISSUE TITLE
How do i uninstall SteamVrInput

### ISSUE THREAD

**Issue by BonzoMartini** [ValveSoftware/steamvr_unreal_plugin#160]
I updated my project from 4.22 to 4.24. I believe StreamVR Input is causing problems. How do i uninstall it 

thanks

**Comment by BonzoMartini** [comment]
SteamVrInput only becomes active in one project -so it seems tied to the project

**Comment by BonzoMartini** [comment]
An Unreal Process has crashed: UE4-SteamVRInputPlugin

**Comment by 1runeberg** [comment]
Hi @BonzoMartini - In 4.24, the SteamVRInput plugin was integrated to the engine. 

For the GitHub version, this shouldn't compile for 4.24, but you can easily remove it from your project via unticking it in the plugins menu before the upgrade or deleting the plugin from the Plugins folder. You should also remove any individual controller key mappings as the controller definitions were moved from the SteamVRInput plugin to the engine core.

For the Marketplace version you can untick it in the project settings before upgrading. 

Let me know if you have any issues with the update after removing the plugin in 4.22.

**Comment by BonzoMartini** [comment]
Thanks for getting back. So I did not compile for 4.24. I added via marketplace to a project and later updated the project from 4.22 to 4.24
Where is it in plugins menu? I guess you mean under the UE/Edit/Plugins window - it's not under VR. It's not searchable? It does not show up in the Plugins folder.
What does "untick it in the project settings" mean ? Where do I untick it? This must very obvious to you

**Comment by 1runeberg** [comment]
Hi @BonzoMartini - You need to do it from the original project in 4.22

Go to Project Settings > Plugins > Virtual Reality and look for SteamVR Input. Untick this plugin to disable/remove it from your project.

**Comment by BonzoMartini** [comment]
Hi as i said it is not showing up in the plugins list under Virtual reality

**Comment by 1runeberg** [comment]
Was the plugin installed? If it doesnt show up in the list, that means the plugin isn't installed and isn't running.

**Comment by BonzoMartini** [comment]
on the UE toolbar i see 'SteamVrInput' button on this project

**Comment by BonzoMartini** [comment]
The plugin wasnt installed to this engine version.

**Comment by BonzoMartini** [comment]
or is that button part of SteamVR?

**Comment by 1runeberg** [comment]
Hi @BonzoMartini - 

Are you trying to disable the plugin from 4.24 or 4.22? 

For an upgraded project WITH a Marketplace version of the plugin in UE4.22, you need to do the following as I mentioned on my first response:

Disable the plugin from your UE4.22 project not in the UE4.24 project, via the Plugins list and you need to REMOVE the Input bindings for all controllers in Project Settings > Input.

If the "SteamVR Input" plugin doesn't appear in UE4.22's list, then it's likely you are not using the Marketplace version of the plugin for that project.

For UE4.24, the plugin is already part of the official engine code so you cant disable just the Input part, you need to disable the entire SteamVR plugin.

**Comment by BonzoMartini** [comment]
I was trying to disable the plugin in 4.24. Ok so that makes sense if "the plugin is already part of the official engine code" Thankyou for your help!
