### ISSUE TITLE
"bTracked" member on MotionControllerComponent is allways true

### ISSUE THREAD

**Issue by chunfinplos** [ValveSoftware/steamvr_unreal_plugin#161]
--- Testing in UE4 4.25.3 with vive controllers and HTC vive ---

In order to avoid this bug, you can use "CurrentTrackingStatus" member.

Log with Motion controllers turned off:
    **CurrentTrackingStatus= ETrackingStatus::NotTracked | bTracked= TRUE**

Log with Motion Controllers turned on:
    **CurrentTrackingStatus= ETrackingStatus::Tracked | bTracked= TRUE**

I hope this helps!

**Comment by 1runeberg** [comment]
@chunfinplos can you point me to the specific code line you're referring to?

**Comment by chunfinplos** [comment]
Hi, is not in your plugin. Is in UMotionControllerComponent class. But is related with VR interface input. File MotionControllerComponent.h in line 132 (UE4_4.25.3)

**Comment by 1runeberg** [comment]
Hi @chunfinplos if you are reporting a fix or a bug with the engine itself, it would be more appropriate to create a Pull Request with EpicGames:

https://github.com/EpicGames
https://www.unrealengine.com/en-US/ue4-on-github

MotionController Component affects all XR Platforms.
