### ISSUE TITLE
Input issues on UE 4.25

### ISSUE THREAD

**Issue by BreakMaker** [ValveSoftware/steamvr_unreal_plugin#163]
Hi Valve Team,

I want to add support for the Index Knuckles in my VR interaction system "Realistic VR Doors" (https://www.unrealengine.com/marketplace/en-US/product/realistic-vr-doors-physics-based-parameterised?sessionInvalidated=true) but I am running into an input-related issue. I tried to follow the Quickstart guide and I checked the example project thoroughly.

Now first of all I want to add support from 4.25 upwards; I realize the Plugin has been integrated into the engine. The animation Blueprint and skeletal mesh deformations have been set up / work properly based on the input coming from the device.

My problem is that if I create new input it does not seem to trigger at all. Even if I import your input settings from the example project so it is identically followed in my project, it does not work.

I recorded a quick video (just a few minutes) to demonstrate the problem and put it in the cloud, maybe this way I can convey my problem more effectively (see link below).

https://www.dropbox.com/s/shoxzjedar1bs9k/Video%20to%20Valve%20Input%20Issue.mp4?dl=0

Sorry if I am missing something very obvious!

Thanks a lot!

**Comment by 1runeberg** [comment]
Hi @BreakMaker - thanks for the video, helped clarify a few things.

It looks like the updated action manifest isn't registering properly to SteamVR for some reason in your project, can you please try:

(1) Close the Editor
(2) Delete steamvr_ue_editor_app.json under the Config folder. This is the application manifest that identifies your UE project to SteamVR and points to the location of the action Manifest (Under the Config/SteamVRBindings folder)
(3) Delete the entire SteamVRBindings Folder
(4) Delete the Saved directory 
(5) Start the Editor

They should all regenerate and the engine will try to re-register to SteamVR.

We have an in-editor tool that'll also force a manifest regeneration and reloading to SteamVR you can use:

(1) Go to Project Settings
(2) Under Plugins section, Select SteamVR
(3) Enable our toolbar button:
![image](https://user-images.githubusercontent.com/17371351/97065048-683e8d00-15f6-11eb-9df1-eb2b3ac344a2.png)

(4) You should then have a number of options to regenerate each set of json files as well as re-register the action manifest to steamvr as well as launch the SteamVR bindings dashboard:
![image](https://user-images.githubusercontent.com/17371351/97065072-9f14a300-15f6-11eb-92f7-4e1efa1bce96.png)

Failing that, try adding a ProjectName under ProjectSettings and/or look into C:\Users\{username}\AppData\Local for a folder named after your project and delete that folder.

**Comment by BreakMaker** [comment]
Hi Rune,
this worked like a charm! Actually, one more step needed was re-activating the bindings in SteamVR dashboard! (otherwise after removing the files even hand tracking was dead).
Also, great to know the Steam VR Input Plugin menu was simply hidden... I started to wonder if it was not carried on to 4.25.

Now its all working, thanks a lot!!!

**Comment by 1runeberg** [comment]
No prob @BreakMaker thanks!

**Comment by dslnc** [comment]
I have issues packaging a project to an .exe file and maintain vive tracker functionality with ue.4.25.4 - exporting the vivetrackers fails to register no matter what. In the editor all works fine.

**Comment by 1runeberg** [comment]
afaik that's the name for a standalone preview not a proper build. the build should be reporting as the project name.
