### ISSUE TITLE
How to use with UE mannequin left hand?

### ISSUE THREAD

**Issue by BreakMaker** [ValveSoftware/steamvr_unreal_plugin#164]
Hi Rune,
I wonder what would be the best approach to use the Knuckles / Steam VR anim nodes with the left hand of the standard mannequin. I could not find an example implementation in the example project and the video tutorial is focused on the moondust and robo recall hands, the latter having a custom left hand already created. 
However, the UE4 VR template just uses the right hand, and inverts the left hand in scale. This way it can be ensured that all functions in the hand class work irrespecitve of which hand it is.

But somehow this does not work with the Steam VR animation nodes in the animation blueprint. Even if I invert the mesh in the actor blueprint, the left hand looks like a right hand. Finger tracking works correctly when using the "mirror" input in the "SteamVR Skeletal Anim Pose" node; this is not the problem.

1. I tried using the "transform / modify bone" node to apply a negative scale to the left hand again; but this flips the normals on the mesh and also creates all sorts of complications downstream when I am using IK for various stuff.

2. I considered just exporting the mesh to Blender and mirroring it but then I guess the animations that are for the right hand would not work correctly, making it necessary to mirror all baked hand animations one by one.

I am pretty sure there is an easier way to do this. Have you thought about this perhaps?
Thanks!

**Comment by 1runeberg** [comment]
Hi @BreakMaker - We do have a sample where we show how to use the Animation Nodes for the standard UE Mannequin hand, including how set it up for the Left Hand.

If you open the UEHands_SampleMap, you should be able to try it out. 

UEHand_AnimBP will have these core nodes that handles the left hand (scaled right hand mesh):

![image](https://user-images.githubusercontent.com/17371351/97948228-0ba45480-1de4-11eb-8742-ad99a818757f.png)

**Comment by BreakMaker** [comment]
Hello  @1runeberg ,
yes, this is exactly what I had done.

I inverted the hand in the hand actor bp (y world scale -1.0), and used the SteamVR Skeletal Anim Pose to apply mirroring if it is the left hand (see screenshots below)
![Screen2020-11-03 22 46 20](https://user-images.githubusercontent.com/30862875/98044187-c81f0a00-1e26-11eb-9854-dcd7c999feba.png)

I have figured out a solution, though I do not understand why this is the solution :D : I had to include a delay node before "Set world scale", as if there was some sort of race condition. I double checked, and I am not setting the scale anywhere else (except the fact that transform must be set when spawning from the class but this should occur before even begin play in the spawned actor, so this cannot be it)


![Screen2020-11-03 22 45 04](https://user-images.githubusercontent.com/30862875/98044204-cce3be00-1e26-11eb-807a-0526aea1c1fa.png)

Anyway, it works now and I could not reproduce the issue in your example project (the only thing to watch out for in the exmaple project is to set the property "socket needs flipping", otherwise the left hand will not be inverted!

**Comment by 1runeberg** [comment]
Not sure why you would need a delay there @BreakMaker, not sure if that's a localized version of the engine but the commas in place of the period in your float values seem a bit odd.

Not clear on why a custom socket would impact flipping a mesh scale, I don't think we have this in our sample project and inverts just fine, but glad you got it all working! :thumbsup:

**Comment by BreakMaker** [comment]
I did not notice it, but you are right: I have commata instead of periods everywhere . Maybe the engine reads the region settings from the OS (I am based in Germany whe have comma instead of period) (see the image below for an example)
![Screen2020-11-03 23 04 03](https://user-images.githubusercontent.com/30862875/98045912-893e8380-1e29-11eb-8055-75afee0599e6.png)


Regarding the pawn: But you do have it: The screenshot below is from the sample project "BP motion controller". 
![image](https://user-images.githubusercontent.com/30862875/98045704-3369db80-1e29-11eb-9b3b-9539b1f41fb1.png)
There is a branch node leading up to set world scale based on NeedsFlip.
And Needs flip is exposed on spawn when you make the spawn in "MotionControllerPawn", reading the value of SocketNeedsFlip.
![image](https://user-images.githubusercontent.com/30862875/98045779-4ed4e680-1e29-11eb-9d87-531e3485dc0d.png)

But the default value of "socket needs flip" is false. So failing to set it to true before running the smaple project in VR, effectively produces the same problem because set scale never fires. Maybe worth to check it out : )
