### ISSUE TITLE
Where is SteamVR Input Toolbar in 4.25+

### ISSUE THREAD

**Issue by OptimisticMonkey** [ValveSoftware/steamvr_unreal_plugin#166]
Need to regenerate action manifest and its not showing up on toolbar?

**Comment by OptimisticMonkey** [comment]
![image](https://user-images.githubusercontent.com/7347/98267983-352ac080-1f49-11eb-8397-f7cd2afc1958.png)
Found the buttons in Project Settings now

**Comment by 1runeberg** [comment]
Cheers @OptimisticMonkey ! By ticking the "Show Steam VR Input Toolbar Button" you can also have the SteamVR button in the main toolbar for easy access to those functions (putting numbered screenshot here for others):

![image](https://user-images.githubusercontent.com/17371351/98287507-914d1d80-1ff9-11eb-8288-7859e9957e6b.png)
