### ISSUE TITLE
How to include correct manifest when packaging....

### ISSUE THREAD

**Issue by OptimisticMonkey** [ValveSoftware/steamvr_unreal_plugin#167]
So when I play in VR preview, and configure using steamvr ui - everything works great.

But when I package, it doesnt include the changes I made in the ui?

**Comment by 1runeberg** [comment]
Hi @OptimisticMonkey - Are you saving over the default bindings?

![image](https://user-images.githubusercontent.com/17371351/98589657-b6a39980-2321-11eb-960d-6abc02ddff42.png)

**Comment by 1runeberg** [comment]
Hi @OptimisticMonkey - do you still need help on this?

**Comment by 1runeberg** [comment]
Closing, stale issue.
