### ISSUE TITLE
A way to test UE4 and vive tracker/Steam connection?

### ISSUE THREAD

**Issue by Blofd** [ValveSoftware/steamvr_unreal_plugin#173]
Trying to follow this tutorial, (and also trying using vivemocapkit) but there seems to be something broken (for me) in the connection between UE4 and vivetracker/SteamVR. Trackers and stations are showing up fine on SteamVR

https://www.youtube.com/watch?v=LiV8RhzvUHI

Also, when I go to "Steam VR Binding Dashboard" and try editing "current binding" or "create new bingin" after selecting the appropriate tracker. Nothing happens.

Using 4.26 (but also tried the tutorial in 4.25.4)

Any help would be greatly appreciated. Thanks!

**Comment by 1runeberg** [comment]
Hi @Blofd I'm not sure which engine version the tutorial is on, but the official way of using the trackers would be via the SteamVR Input system.

For version 4.19 to 4.23, have a look at the following issue:
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/89

And for 4.24 and above:
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/126
https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/104

Here's a demo video as well:
https://www.youtube.com/watch?v=nL61ZsXk1xc&feature=youtu.be

I hope that helps!

**Comment by Blofd** [comment]
Hi 1runeberg,

      Thanks! I tried the demo video until 0:57 mark. After that when I click on Edit Current Binding or Create New Binding, nothing happens.

Tried using both "Show Old Binding UI" from SteamVR and "SteamVR Input" > "Launch..." from UE4.

**Comment by 1runeberg** [comment]
Can you send a screenshot from your end for steps in 0:46 and 0:56?

**Comment by Blofd** [comment]
https://imgur.com/a/gkExbfw

Really appreciate your quick responses, been struggling with this for a while!

**Comment by 1runeberg** [comment]
That seems fine to me, not sure why its not opening up the menu... can you try controller bindings? Otherwise can you send the SteamVR Report?
![image](https://user-images.githubusercontent.com/17371351/102171127-ee39ce80-3ee9-11eb-8e26-4cb9cb4997c7.png)

**Comment by Blofd** [comment]
[SteamVR-2020-12-15-AM_09_58_31.txt](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/5693342/SteamVR-2020-12-15-AM_09_58_31.txt)

I'm only using trackers and no hmd or controllers. Attaching the report.

**Comment by 1runeberg** [comment]
Oh, we don't officially support a headless configuration for the UE plugin. So this configuration isn't valid.

**Comment by Blofd** [comment]
Are there any suggestions to how to fix this though? Primarily I'm trying to use vivemocapkit in UE4 and also a tracker for camera.

**Comment by 1runeberg** [comment]
are you unable to attach a headset? not sure if the engine's tracking and XR init will kick in anyways without one at any rate.

there is also Epic's new Live Link XR Plugin in 4.26, which in my understanding supports trackers and can try if it supports headless.

**Comment by Blofd** [comment]
A few people have been doing mocap using just trackers and "ViveMocapKit" plugin on UE4 markerplace. That is what I intend to follow.

BTW, Vive Trackers aren't linking even while using Epic's Link XR in 4.26, following this https://www.youtube.com/watch?v=UexGZ08goEU

At ~3:30 mark he adds the Vive tracker and it shows up with a green light. For me "Subject Name" "role" columns remained empty even after adding. 

So I guess it just cements the point that SteamVR and UE4 aren't talking in my case.

**Comment by 1runeberg** [comment]
As mentioned, unfortunately a headless setup isn't something we officially support in the steamvr plugin - it was designed for use in a VR setup with headset and controllers.

If the mocap plugin you are using guarantees it supports this type of setup, then you'd have to contact them directly for support.

**Comment by EMDO81** [comment]
Hi Rune, I've been having the same issue in 4.26 with a setup including the Index (with two Knuckles) and 3 Vive trackers set to Left Foot, Right Foot, and Waist within SteamVR controller settings.  Points of note:

- Similar to OP, I can't create or edit bindings for the trackers consistently.  When I can, I don't have Special1 or other actions to set, I see "right pose" or "left pose" selections.  Editing Index Controller bindings is possible, though.  However, one time was I able to see Special1/other actions but they don't show up anymore.  Soo, I'm a bit befuddled.
- Using the following tutorial as my template, I got 2 out of 3 trackers to work by adding more motion controllers to the original Event Graph.  However, upon a restart, they stopped working in UE4 but the base stations and SteamVR continue to track them.  My last resort was to reinstall Win10 with UE4 and Steam installed only and the same thing happened.  They worked on the initial install then stopped working after subsequent (normal) system restarts.  


https://www.youtube.com/watch?v=ehK6j6Es-ck

This post is about as close as I've got to finding someone with a similar issue.  Please let me know if this is worthy of re-engaging!

**Comment by 1runeberg** [comment]
@EMDO81 - sorry I think this got mixed in with another issue - with 4.26, you should see specific motion sources for the trackers (Not the Specialx) and they should already be bound to the correct poses in SteamVR (you still need to bind the tracker to the role in SteamVR though as well). One thing to note is to see the trackers you need to attach a mesh as the visualization mesh doesn't appear in 4.26. Lemme know if you're still having trouble.

**Comment by EMDO81** [comment]
Thanks, Rune.  I believe we resolved this and the other issue concurrently at the time.  Everything is working as it should - thanks for putting me on track on this

**Comment by 1runeberg** [comment]
Nice! Really glad to hear that!
