### ISSUE TITLE
Getting the SteamVR Device ID from the device role

### ISSUE THREAD

**Issue by Rectus** [ValveSoftware/steamvr_unreal_plugin#177]
The USteamVRFunctionLibrary::GetTrackedDevicePositionAndOrientation function requires the SteamVR device ID as an input, but the only way to get the ID I can find is from USteamVRFunctionLibrary::GetValidTrackedDeviceIds which only outputs devices with a valid pose and doesn't output any further information about what device maps to what ID. 

Is there any way of either getting the device ID from a motion controller component, or identify the IDs that map to the left/right controllers and HMD?

**Comment by 1runeberg** [comment]
Hi @Rectus - Can you clarify what you plan to use the DeviceIDs for? The input system is designed to abstract away from developers the need to query devices manually.

**Comment by Rectus** [comment]
I'm trying use GetTrackedDevicePositionAndOrientation to check if the controller is turned on, tracked and has a valid pose. 

As per https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/161 the IsTracked method in the motion controller component to check tracking status doesn't return anything useful. The method documentation is also very ambiguous on what it is supposed to return, so I'm not sure if that is what it is meant to be used for. I filed an UE4 bug report on it about a week ago, but haven't heard anything back yet.

Without either, the only way I've found to check for a valid tracking state from blueprint is to check if the motion controller position is a zero vector.

In general it seems very hard to use any of the SteamVR functions together with the stock XR interface, with no way of getting the data the function parameters require. I think the abstracted system is a good idea though.

**Comment by 1runeberg** [comment]
Gotcha. We could potentially expose this on our end but the proper way to get the tracked bit is via the engine provided way. In #161 it seems to be broken on the engine side so this needs to be raised with Epic directly. 

If you're using C++, you can check out commented portions in the SteamVRTrackingRefComponent.cpp

**Comment by Rectus** [comment]
Thanks for the help.

It's not an ideal solution, but I guess I could iterate through the controllers though OpenVR and match the controller role property with the motion controller component hand. 

As a side note, the engine XR system doesn't seem to have any way of differentiating the motion controller being turned off and not having a correct tracked pose. It goes into the zero transform in both cases, and that might cause jitter, especially if the engine is applying smoothing.

**Comment by 1runeberg** [comment]
jitter? is the controller still moving in your scene when it's turned off? if it is, then that'll be a bug that needs actioning so I think this feedback is better communicated with Epic directly.

**Comment by Rectus** [comment]
I have to double check that I haven't set things up wrong, but the controller component always spawns at the world origin and returns there when losing tracking. I'll be sure to send a bug report to Epic.

**Comment by Rectus** [comment]
I checked it and the controller returns to the tracking space origin whenever it's not tracked. 

Looking though the code, the problem seems to lie with `SteamVRInputDevice::GetControllerOrientationAndPosition` in the SteamVR plugin. It will always update the position and orientation as long as a `GetPoseActionData` returns without error, whereas the versions for the other runtimes have checks for if the pose is valid.

The motion controller component uses the return value from `GetControllerOrientationAndPosition` to set `bTracked`, so that is what seems to be causing https://github.com/ValveSoftware/steamvr_unreal_plugin/issues/161 as well.

I also looked at `FSteamVRInputDevice::GetControllerTrackingStatus`, and that appears to behave differently as well. It only checks if the device is connected, whereas the Oculus runtime seems to check for a valid pose instead, and failing to find that, it can also return `ETrackingStatus::InertialOnly` for an estimated pose. I haven't verified if everything works correctly in the other runtimes though.

**Comment by Rectus** [comment]
I tested the behavior with the OpenXR runtime, and there is seems to work correctly. The controller pose freezes to the last position when the tracking stops updating, and the tracking status can be read from the XR system.

**Comment by 1runeberg** [comment]
HI @Rectus - for the specific behaviour you're wanting (motion controller pose to be retained in the last known valid tracking frame), I've traced in the SteamVRHMD and it seems the engine isn't calling:
ETrackingStatus FSteamVRHMD::GetControllerTrackingStatus(int32 DeviceId) const

The trackignframe does get updated from OpenVR with the correct tracking status, but the engine just doesn't seem to call this part of the plugin, unlike the Oculus and OpenXR plugins.

The SteamVRHMD was developed and maintained by Epic, so you can provide this extra info in your bug report. I cant see any issues from the plugin itself though, just that somehow the engine isn't calling this function as it should. 

From our end fwiw, we're not making any major changes to the Input side of the plugin (SteamVR Input) in favour of the move to OpenXR. And could also be the reason why this has flown under Epic's radar so far.

**Comment by Rectus** [comment]
I already filed the bug report, but I'll be sure to provide it if they ask for more info. Thanks!

**Comment by 1runeberg** [comment]
Closing now as this would be an Epic decision/pre-rogative
