### ISSUE TITLE
4.25.4 Controller inputs not firing in packaged build

### ISSUE THREAD

**Issue by JoachimHolseter** [ValveSoftware/steamvr_unreal_plugin#178]
I know there are multiple threads on this issue, and I have tried the solutions from those threads already.

Mainly, I tried the solutions from #163 without luck. 

Every input action is working fine in the editor, but once the game has been packaged, the controller inputs no longer work. 

One thing to note, the "Launch SteamVR bindings dashboard" button either does nothing when pressed or opens a webpage and loads indefinitely.

**Comment by 1runeberg** [comment]
Hi @JoachimHolseter - can you check if the config/SteamVRBindings folder is included in the packaged build?

there's a known engine issue that broke this a while back as these files should have been part of the pak during packaging.

**Comment by JoachimHolseter** [comment]
> Hi @JoachimHolseter - can you check if the config/SteamVRBindings folder is included in the packaged build?
> 
> there's a known engine issue that broke this a while back as these files should have been part of the pak during packaging.

Hi there! Thanks for the quick reply! Yes, the folder is indeed there.

**Comment by 1runeberg** [comment]
Thanks. Can you send me the logs then please from the build (Saved/Logs) ?

**Comment by JoachimHolseter** [comment]
> Thanks. Can you send me the logs then please from the build (Saved/Logs) ?

Yep! 
[CaveRails.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/5869645/CaveRails.log)

**Comment by 1runeberg** [comment]
Thanks for that. The plugin looks like it's loading the manifests fine and functioning properly. There's an issue however with one of your BP's with a divide by zero:

[2021.01.25-18.08.47:491][821]LogScript: Warning: Script Msg: Divide by zero detected: 0.000000 / 0

Might be stopping the app from running properly? Otherwise If you send us a SteamVR system report as well, I can validate the end to end communication between your app and steamvr.

**Comment by JoachimHolseter** [comment]
A bit of speculation here; When I open the "Manage controller bindings" menu in the UE4 editor the application is called "UE4Editor" and when I'm playing the compiled game the application's name is "UE4Game". Does it know that these applications are the same?

**Comment by 1runeberg** [comment]
afaik that's the name for a standalone preview not a proper build. the build should be reporting as the project name. 

They are and should be treated differently. The Editor version should also have the name of the project as well as a uniquue engine build number.

If you've tried a standalone run before, it may be picking up an old config. You can try deleting any config remnants in %APPDATA%/Local

**Comment by JoachimHolseter** [comment]
Hello again.
I just created a brand new project using the SteamVR Template in 4.25.4 and the issue persists! 
Although, it just seems to be the triggers that are the issue! 
The trackpad inputs work just fine in the packaged build. but I receive no input from the triggers. 

In my actual project, I'm only using the triggers as input, so I didn't notice at the time that those were the only ones not working.

**Comment by JoachimHolseter** [comment]
Using the OG Vive btw. I don't have any other headsets to try on.

**Comment by JoachimHolseter** [comment]
Is there any way to delete all custom saved input profiles? Or even disable SteamVR Input in 4.25.4 altogether and use the old Input system?

**Comment by 1runeberg** [comment]
> Hello again.
> I just created a brand new project using the SteamVR Template in 4.25.4 and the issue persists!
> Although, it just seems to be the triggers that are the issue!
> The trackpad inputs work just fine in the packaged build. but I receive no input from the triggers.
> 
> In my actual project, I'm only using the triggers as input, so I didn't notice at the time that those were the only ones not working.

Can you clarify which "SteamVR Template" you're referring to? Can you check the input mappings from the UE ui and see if the Vive trigger is properly mapped?

We have a sample project for 4.24 and above here:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

I also highly recommend having a look at our quickstart guide to get a better understanding of the new input system:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/Quickstart

**Comment by 1runeberg** [comment]
> Is there any way to delete all custom saved input profiles? Or even disable SteamVR Input in 4.25.4 altogether and use the old Input system?

The input profiles are stored as json files, not sure what you mean by custom, is it the personal bindings in the dashboard ui? If so, there should be a delete button right in the ui. 

The legacy input system isn't supported in UE4.24 and above. And our legacy input system also doesn't support any newer controllers such as the Index.

**Comment by JoachimHolseter** [comment]
> Can you clarify which "SteamVR Template" you're referring to? Can you check the input mappings from the UE ui and see if the Vive trigger is properly mapped?

When you first create a project and select "Virtual Reality" in there there is a map called MotionControllerMap.

I'm downloading the sample project now to see if it works there, 
Thanks.

**Comment by JoachimHolseter** [comment]
I managed to fix the problem by migrating all of my files to the sample project you provided! 
Weird issue, but thanks for the help.

**Comment by JoachimHolseter** [comment]
I managed to fix the problem by migrating all of my files to the sample project you provided!
Weird issue, but thanks for the help.

**Comment by 1runeberg** [comment]
fwiw the main difference with the standard template with regards to builds is the "Project Name" in UE's Project Settings. Which could be causing your issue in the other project.

All UE Games with no project name set may look alike to the SteamVR runtime. These can be reset/deleted from the following directory: %APPDATA%/Local/   You can delete the UE or ProjectName folder under here which holds user specific UE config files.

**Comment by JoachimHolseter** [comment]
> fwiw the main difference with the standard template with regards to builds is the "Project Name" in UE's Project Settings. Which could be causing your issue in the other project.
> 
> All UE Games with no project name set may look alike to the SteamVR runtime. These can be reset/deleted from the following directory: %APPDATA%/Local/ You can delete the UE or ProjectName folder under here which holds user specific UE config files.

Good to know. Thanks, Rune!
