### ISSUE TITLE
Using the plugin in a multiplatform project

### ISSUE THREAD

**Issue by rproepp** [ValveSoftware/steamvr_unreal_plugin#181]
Hi, I'm trying to port my project which uses SteamVR input to more platforms that don't support SteamVR (Mac for now). Mostly this seems to work, but I have issues with a few functions I'm calling in my Blueprints, such as PlaySteamVR_HapticFeedback. These don't exist on unsupported platforms, breaking the Blueprint compile.
What is the best practice to deal with these Blueprint nodes? As far as I know, platform-gating is impossible in Blueprints. I've tried to call the function from C++ (so I can use the preprocessor to gate it), but I can't include SteamVRInputDeviceFunctionLibrary.h because SteamVRInputDeviceFunctionLibrary.generated.h can't be found.

**Comment by 1runeberg** [comment]
Hi @rproepp - unfortunately we can't provide any support for OS platforms we haven't whitelisted in the plugin at this time.

Sorry we can't help on this further.
