### ISSUE TITLE
[4.25] Controller material "M_DefaultDevice" loses textures in packaged game

### ISSUE THREAD

**Issue by iMaciaP** [ValveSoftware/steamvr_unreal_plugin#182]
In editor is working fine, i can edit this material and see the changes working.

![image](https://user-images.githubusercontent.com/47883521/111984538-c622c280-8b0b-11eb-86be-477fc6e457bb.png)

But, 
I'm working with this motion controller config, and i see a grid material when game is packaged.

**Comment by 1runeberg** [comment]
I believe this was a known engine issue that was fixed in 4.23. I'm unsure if there was a regression.

That material and its packaging is general to the engine XR architecture, so I suggest bringing this up directly to Epic Games:
https://answers.unrealengine.com/
