### ISSUE TITLE
[Question] Game pose updating

### ISSUE THREAD

**Issue by Rectus** [ValveSoftware/steamvr_unreal_plugin#183]
I noticed that when the SteamVR plugin calls VRCompositor->GetLastPoses() in SteamVRHMD.cpp:730 to retrieve the poses used for the game thread, it uses the first two parameters in the function instead of the last two.

According to the API header, the last two parameters retrieve poses with further prediction applied to them, meant for game simulation of the next frame. Shouldn't it use those instead to get more accurate poses, or am I missing something?

**Comment by 1runeberg** [comment]
That looks right since UE blocks on WaitGetPoses() in the render thread, so they should use the renderPoses retrieved from this call instead of the gamePoses (second set of params) which is predicted further out.

**Comment by Rectus** [comment]
Thanks for clearing that up. The documentation for GetLastPoses() is a bit ambiguous on what it's supposed to do. From the description, I was under the impression that it would return a set of cached poses from the previous call to WaitGetPoses().
