### ISSUE TITLE
4.22 UE4 ,Valve Index make my game error.

### ISSUE THREAD

**Issue by wayne-wwwTW** [ValveSoftware/steamvr_unreal_plugin#185]
Before pakage,I test in project , is work.
![](https://user-images.githubusercontent.com/77315720/116204266-2e01a400-a76f-11eb-9e6c-277f83c78e75.png)
After Pakage, error.
![](https://user-images.githubusercontent.com/77315720/116203991-debb7380-a76e-11eb-80e4-923ed1fa6e61.png)

I use 4.22 ,and have same problem like him.
Link answers is work, But my game VR hands will not be work. 
That is not I want.
answers.unrealengine.com/questions/940461/view.html

Thank for reading.
I try my best.

**Comment by wayne-wwwTW** [comment]
answers.unrealengine.com/questions/940461/view.html

Link is here!

**Comment by 1runeberg** [comment]
Hi Wayne - can you package a Debug build:

![image](https://user-images.githubusercontent.com/17371351/116305109-6f3d9680-a7f7-11eb-8967-ebf482ef5de6.png)

Run to reproduce the issue and send us over the resulting logs:

![image](https://user-images.githubusercontent.com/17371351/116305388-d22f2d80-a7f7-11eb-87bd-05bdab6c1e2a.png)

**Comment by wayne-wwwTW** [comment]
Thanks for your reply!!

I couldn't find  **Package Project / Build Configuration / Debug**
![未命名](https://user-images.githubusercontent.com/77315720/116338963-33163000-a80f-11eb-872b-4af86b3c4de4.png)

So, I Package **Development** and run the game, I'm not sure if this is enough for you to find the problem. I still Looking for how to package **Debug**.
![Logs 2021_4_28 上午 10_43_38](https://user-images.githubusercontent.com/77315720/116339432-fb5bb800-a80f-11eb-9ef7-abc32ffce71f.png)


logs :
[Work_0807.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/6388996/Work_0807.log)

**Comment by wayne-wwwTW** [comment]
Hi Rune berg - I have new progress.
I download the Sample Project , and package it, is working .

And I use my Project to package the Simple project Level 【UEHands_SampleMap】.
Is doesn't work in game.
In Simple Level (Simple Project Level) ,It didn't crash game ,Just only can't control VR hands (Valve index).
In my own project level , it always crash game, and didn't show anything about error.

And both two ( Simple Level and mu own project level) Log, have repeat this paragraph.
**【SteamController is not available】**
Hope these processes can use it. 

(All of the above are working in project edit.)

My own project log. ( error )
[Work_0807.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/6396967/Work_0807.log)

Simple project log. ( work )
[SteamVRInputPlugin.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/6396969/SteamVRInputPlugin.log)

**Comment by wayne-wwwTW** [comment]
I package Debug build , and Hey! is work!
And I back to build Development and shipping, is always error and destroy my game.

Debug Build - Work.
[Work_0807.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/6412767/Work_0807.log)

Development Build - Not work.
[Work_0807.log](https://github.com/ValveSoftware/steamvr_unreal_plugin/files/6412771/Work_0807.log)


I will keep trying.

**Comment by 1runeberg** [comment]
Hi @wayne-wwwTW. We need to generate the logs to see why the crash is happening. Include the debug files in your development build like so:

![image](https://user-images.githubusercontent.com/17371351/116918545-2593f680-aca4-11eb-9fcd-45d81edd954d.png)

Send us a copy of your packaged build AFTER running once and crashing in your system. Make sure to zip all directories.

Thanks,
Rune

**Comment by wayne-wwwTW** [comment]
Hi
I follow your steps ,click 【Include Debug Files】, build Development.
And I run it once , make sure is still error and broke game.
Hope this is what you need.
 WindowsNoEditor.zip
<https://drive.google.com/file/d/1_UQYLalvZZ6Lbx2CNDu_YkUBHWZ97oH4/view?usp=drive_web>


Rune Berg ***@***.***> 於 2021年5月4日 週二 上午2:47寫道：

**Comment by 1runeberg** [comment]
Hi @wayne-wwwTW - I cant seem to access that link, if you don't want to send a test build publicly, you can send a link to:
runeb@valvesoftware.com instead.

Cheers,
Rune

**Comment by wayne-wwwTW** [comment]
Oops!
Sorry, I forgot to set it public.
Try it again.
<https://drive.google.com/file/d/1_UQYLalvZZ6Lbx2CNDu_YkUBHWZ97oH4/view?usp=drive_web>

**Comment by 1runeberg** [comment]
Hi @wayne-wwwTW - 

Thanks for that - can you try removing on your project any haptic feedback for the controllers and let me know how that works for you in a packaged development build?

Also, is your project C++ or Blueprint only?

Thanks,
Rune

**Comment by wayne-wwwTW** [comment]
Hi Rune Berg

I have to out of business these four days, and I will not develop projects
for the time being.

 Thank you for your positive response. I will come back soon and try again.

I’m not sure if I using Blueprint only?
I have some plug-in in project ,need create C++ class to rebuild it.

Thanks!

Rune Berg ***@***.***>於 2021年5月6日 週四，03:06寫道：

**Comment by 1runeberg** [comment]
If you're building the plugin and not just using a pre-built binary, then your project is likely in C++. It seems your project uses invalid values for haptic feedback, so would be good to test on your end. I thought I made sure you cant feed the BP nodes and plugin functions invalid values but I could be mistaken or the offending values are coming from some project C++ code overriding the checks.

**Comment by wayne-wwwTW** [comment]
Hi @1runeberg -

I removed the haptic feedback, and the game no longer crashes.
But the strange is that I can't track the position of my hand(No tracking), but I can use the Valve index button _(I use Left Thumbstick)_ to move my character(is work).

Also, everything is fine in Debug build.
Only Development and shipping build have this problem.

Here is Development build.
https://drive.google.com/file/d/14uBGLlxb-VpKPbadR5qKYiwR7BVhryaJ/view?usp=sharing

**Comment by 1runeberg** [comment]
Closing and creating new github issue for the missing tracking as they are completely different issues
