### ISSUE TITLE
Any input that is not registered on dashboard not firing in UE4

### ISSUE THREAD

**Issue by Monster1234** [ValveSoftware/steamvr_unreal_plugin#186]
Any input that is not registered on dashboard are not firing in UE4. This prevents the ability to use Any Key input action. I guess this is done for OpenXR specifications you mentioned in other issues. Is there a way to get the state of any button without registering it on dashboard?

My usecase: I need to gather every input to animate fingers according to the state of the buttons. Currently, I have to set an Input Action for every possible button and set them in dashboard to collect every buttons state.

**Comment by 1runeberg** [comment]
Hi @Monster1234 - By "dashboard" do you mean the Unreal Editor Input UI? Yes, you need to explicitly define every input binding.

You can have an "any" action defined but you must define which buttons and state (touch/press) triggers this action. there is no catch all key.

**Comment by Monster1234** [comment]
Hi @1runeberg, I meant SteamVR Bindings Dashboard. Btw, I can use "Any Key" action in BP to catch every button state on Oculus. But it doesn't work on SteamVR.

**Comment by 1runeberg** [comment]
@Monster1234 - I suggest using Unreal's built-in Input UI if you're using UE4.24 and above. The "Any Key" is an engine convention afaik and not a vr platform-dependent one. We don't support it natively in SteamVR Input and the upcoming OpenXR standard unless Epic adds it in the engine input.

**Comment by 1runeberg** [comment]
Thanks for the feedback, closing this now however as we're focusing on OpenXR and will not be releasing any major changes to the plugin.

This is however feedback that you bring up directly with Epic for potential inclusion in their OpenXR implementation.
