### ISSUE TITLE
Support for projected camera passthrough

### ISSUE THREAD

**Issue by Rectus** [ValveSoftware/steamvr_unreal_plugin#188]
It would be nice to have access to the HMD passthough camera views, and be able to project them on the players view. UE4 already has AR systems that could be used for this. Alternatively, having support in SteamVR for overlaying the the game output onto the existing compositor passthough would be even better, like with the OpenXR XR_ENVIRONMENT_BLEND_MODE_ALPHA_BLEND mode.

I've been trying to implement it myself using the IVRTrackedCamera interface in OpenVR for a while now, but haven't been able to get the projection to line up properly.

**Comment by 1runeberg** [comment]
Thanks for the feedback! We've noted this request. Please note however that our focus is on OpenXR implementations of current extensions and won't be making any significant changes to the SteamVR plugin moving forward.

**Comment by Rectus** [comment]
Managed to implement it myself.
https://github.com/Rectus/UE4SteamVRPassthrough
