### ISSUE TITLE
How can I add a new action mapping item whick likes demo ValveIndex_Left_Trackpad_Click in UE427

### ISSUE THREAD

**Issue by andlxsen** [ValveSoftware/steamvr_unreal_plugin#191]
How can I add a new action mapping item whick likes demo ValveIndex_Left_Trackpad_Click in UE427.
when I add new action drop down list don't have the item likes steam vr valve index(L) trackpad click.

**Comment by andlxsen** [comment]
ValveIndex_Left_Trackpad_Click which is In the demo project action mapping action can be executed.How can I add custom event and binding corresponding valve index button? Please sir

**Comment by 1runeberg** [comment]
Hi @andlxsen - Sorry somehow missed this last week.

In 4.27, you can use "Valve Index Thumbstick Up/Down/Left/Right" (SteamVR) or "Valve Index Thumbstick X/Y" (OpenXR) as an "Action Binding" to get dpad behavior:

![image](https://user-images.githubusercontent.com/17371351/139734316-da8e48d3-cecf-4272-8c51-ac5c63f811cd.png)

**Comment by andlxsen** [comment]
![1635825130](https://user-images.githubusercontent.com/7390637/139784485-c2b7004b-1e5c-4514-a206-9f34265b3f51.png)

**Comment by andlxsen** [comment]
It should be solved.Thanks a lot!

**Comment by 1runeberg** [comment]
Great! Glad you got it sorted. Cheers!
