### ISSUE TITLE
Unable to rebuild project after extracting plugin files in PATH/TO/PROJECT/Plugins

### ISSUE THREAD

**Issue by shh1v** [ValveSoftware/steamvr_unreal_plugin#194]
I am working on [Carla 0.9.13 build](https://carla.readthedocs.io/en/0.9.13/#building-carla). I have [Unreal Engine 4.26 (Carla)](https://github.com/carlaunreal/unrealengine) installed and running.

When I extract the [steamvr_unreal_plugin-master](https://github.com/ValveSoftware/steamvr_unreal_plugin) and place the SteamVRInput folder into PATH/TO/PROJECT/Plugins/, right-click on the *.uporject file and create visual studio files, and try to rebuild project in visual studio, I get the following errors:

`
Plugin 'SteamVR' (referenced via default plugins -> SteamVRInput.uplugin) does not contain the 'SteamVRInput' module, but lists it in 'E:\work\CarlaDReyeVR\UECarla\Engine\Plugins\Runtime\Steam\SteamVR\SteamVR.uplugin'.	
`

`
MSB3073	The command "E:\work\CarlaDReyeVR\UECarla\Engine\Build\BatchFiles\Rebuild.bat -Target="CarlaUE4Editor Win64 Development -Project=\"E:\work\CarlaDReyeVR\carla\Unreal\CarlaUE4\CarlaUE4.uproject\"" -Target="ShaderCompileWorker Win64 Development -Quiet" -WaitMutex -FromMsBuild" exited with code -1.
`

![image](https://user-images.githubusercontent.com/76883453/170120517-920213d1-279a-4c89-bef3-157c61a2e581.png)

I am just starting out. Can anyone please help me out with this?

**Comment by 1runeberg** [comment]
UE 4.26 already has this plugin built-in to the engine, so you don't need to build or add it separately. It's part of the official SteamVR engine plugin.

**Comment by shh1v** [comment]
Oh, I See. I don't know what made me led to think that I need to install the plugin. Thank you :)

**Comment by 1runeberg** [comment]
No prob 👍
