### ISSUE TITLE
Errors when rebuilding plugin to 4.26

### ISSUE THREAD

**Issue by OKgamedev** [ValveSoftware/steamvr_unreal_plugin#195]
![steamVRinputError](https://user-images.githubusercontent.com/83257600/189537056-7ac45258-67d5-4bcc-a2ac-a3e1c5d9b5f5.png)

Whenever I try to rebuild the plugin to 4.26, I get these errors. Any way to fix it?

**Comment by 1runeberg** [comment]
Hi @OKgamedev - for UE4.26, the plugin is already built-in to the engine. If you want/need to create any modifications, you need to make a custom engine build instead.

**Comment by OKgamedev** [comment]
I'm not sure I understand what you mean?

**Comment by 1runeberg** [comment]
You don’t need to add this plug-in to your projects if you are using UE 4.26. The engine itself already includes this plug-in.

**Comment by 1runeberg** [comment]
Closing this one for now, but feel free to open an issue if you have any issues on using the plugin in UE4.26 (Enable Project Settings > Plugins > VR (category) > SteamVR 

You can also try our sample project:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z
