### ISSUE TITLE
Using SteamVR Skeletal Anim Pose in packaged app cause crash

### ISSUE THREAD

**Issue by TarasDev** [ValveSoftware/steamvr_unreal_plugin#20]
LogWindows: Error: begin: stack for UAT
LogWindows: Error: === Critical error: ===
LogWindows: Error:
LogWindows: Error: Fatal error!
LogWindows: Error:
LogWindows: Error: Unhandled Exception: EXCEPTION_ACCESS_VIOLATION writing address 0x00000001
LogWindows: Error: HandleError re-entered.
LogWindows: Error:
LogWindows: Error: [Callstack] 0x00007ffdbcfba0da vrclient_x64.dll!UnknownFunction []
LogWindows: Error: [Callstack] 0x00007ffdbcf5d799 vrclient_x64.dll!UnknownFunction []
LogWindows: Error: [Callstack] 0x00007ff6e0f821a0 VRoom.exe!FSteamVRInputDevice::GetSkeletalData() [E:\Unreal Engine\VRoom\Plugins\SteamVRInput\Source\SteamVRInputDevice\Private\SteamVRInputDevice.cpp:282]
LogWindows: Error: [Callstack] 0x00007ff6e0f6f488 VRoom.exe!FAnimNode_SteamVRInputAnimPose::Evaluate_AnyThread() [E:\Unreal Engine\VRoom\Plugins\SteamVRInput\Source\SteamVRInputDevice\Private\AnimNode_SteamVRInputAnimPose.cpp:112]
LogWindows: Error: [Callstack] 0x00007ff6e3490303 VRoom.exe!FPoseLink::Evaluate() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Engine\Private\Animation\AnimNodeBase.cpp:355]
LogWindows: Error: [Callstack] 0x00007ff6e3446441 VRoom.exe!FAnimInstanceProxy::EvaluateAnimationNode() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Engine\Private\Animation\AnimInstanceProxy.cpp:1152]
LogWindows: Error: [Callstack] 0x00007ff6e3446106 VRoom.exe!FAnimInstanceProxy::EvaluateAnimation() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Engine\Private\Animation\AnimInstanceProxy.cpp:1130]
LogWindows: Error: [Callstack] 0x00007ff6e346b4cb VRoom.exe!UAnimInstance::ParallelEvaluateAnimation() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Engine\Private\Animation\AnimInstance.cpp:624]
LogWindows: Error: [Callstack] 0x00007ff6e368c1ed VRoom.exe!USkeletalMeshComponent::EvaluateAnimation() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Engine\Private\Components\SkeletalMeshComponent.cpp:1719]
LogWindows: Error: [Callstack] 0x00007ff6e36a20a3 VRoom.exe!USkeletalMeshComponent::PerformAnimationProcessing() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Engine\Private\Components\SkeletalMeshComponent.cpp:1805]
LogWindows: Error: [Callstack] 0x00007ff6e36a18cb VRoom.exe!USkeletalMeshComponent::ParallelAnimationEvaluation() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Engine\Private\Components\SkeletalMeshComponent.cpp:3399]
LogWindows: Error: [Callstack] 0x00007ff6e368b265 VRoom.exe!FParallelAnimationEvaluationTask::DoTask() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Engine\Private\Components\SkeletalMeshComponent.cpp:111]
LogWindows: Error: [Callstack] 0x00007ff6e368d5d7 VRoom.exe!TGraphTask<FParallelAnimationEvaluationTask>::ExecuteTask() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Core\Public\Async\TaskGraphInterfaces.h:845]
LogWindows: Error: [Callstack] 0x00007ff6e153a171 VRoom.exe!FTaskThreadAnyThread::ProcessTasks() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:1029]
LogWindows: Error: [Callstack] 0x00007ff6e153af7d VRoom.exe!FTaskThreadAnyThread::ProcessTasksUntilQuit() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:854]
LogWindows: Error: [Callstack] 0x00007ff6e154227b VRoom.exe!FTaskThreadAnyThread::Run() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Core\Private\Async\TaskGraph.cpp:930]
LogWindows: Error: [Callstack] 0x00007ff6e18e8acf VRoom.exe!FRunnableThreadWin::Run() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:96]
LogWindows: Error: [Callstack] 0x00007ff6e18e8824 VRoom.exe!FRunnableThreadWin::GuardedRun() [D:\Epic\UnrealEngine-4.22.1-release\Engine\Source\Runtime\Core\Private\Windows\WindowsRunnableThread.cpp:53]
LogWindows: Error: [Callstack] 0x00007ffe37277974 KERNEL32.DLL!UnknownFunction []
LogWindows: Error: [Callstack] 0x00007ffe37aca271 ntdll.dll!UnknownFunction []
LogWindows: Error:
LogWindows: Error: Crash in runnable thread TaskGraphThreadHP 7
LogWindows: Error: Crash in runnable thread TaskGraphThreadHP 6
LogWindows: Error: end: stack for UAT
![4yutZQYB 1](https://user-images.githubusercontent.com/1777733/57179108-a3895100-6e82-11e9-9019-faa7c98924f5.png)
Engine version: _4.22.1 source_
Plugins version: _0.65a_

**Comment by 1runeberg** [comment]
HI @TarasDev - I've tested various scenarios using:

4.22.1 - Source Build - no edits made
0.65a in 4.22 release branch
SteamVR 1.4.7 (latest beta) & SteamVR 1.3.23 (latest public)

in a packaged win x64 build using the provided sample content as the default game maps and unable to replicate the issue.

can you provide us with some repro steps please. Also, if you can share your full game log and a SteamVR System Report, it might help provide us more info.

**Comment by TarasDev** [comment]
Thats me being dumb. Crash is my fault not plugin
