### ISSUE TITLE
Unable to init SteamVR runtime when connected to Oculus Rift

### ISSUE THREAD

**Issue by mikeyboybs** [ValveSoftware/steamvr_unreal_plugin#3]
When using the HTC Vive with Knuckles or Vive controllers all works as expected, 

When using Oculus Rift with SteamVR (SteamVR shows oculus connected), the following displays and none of the options from the "SteamVR Input" tool bar respond in the output log.

**LogSteamVRInputDevice: Error: Unable to init SteamVR runtime 1.2.10: Not Initialized (109)**
LogSteamVRInputDevice: Display: Action Manifest Path: ../../../../../../Unreal Projects/4.21/GameWorks/SoulOccupant/Config/SteamVRBindings/steamvr_manifest.json
LogSteamVRInputDevice: Display: Controller Bindings Path: ../../../../../../Unreal Projects/4.21/GameWorks/SoulOccupant/Config/SteamVRBindings
LogSteamVRInputDevice: Display: Temporary action [GrabRight] defined.
LogSteamVRInputDevice: Display: Attempt to define digital action GrabRight unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action GrabRight unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action GrabRight unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action GrabRight unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Temporary action [LaserInteractionR] defined.
LogSteamVRInputDevice: Display: Attempt to define digital action LaserInteractionR unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action LaserInteractionR unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Temporary action [TeleportLeft] defined.
LogSteamVRInputDevice: Display: Attempt to define digital action TeleportLeft unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action TeleportLeft unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action TeleportLeft unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action TeleportLeft unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Temporary action [TeleportRight] defined.
LogSteamVRInputDevice: Display: Attempt to define digital action TeleportRight unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action TeleportRight unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action TeleportRight unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Attempt to define digital action TeleportRight unsuccessful! Possibly reached limit of 50 actions.
LogSteamVRInputDevice: Display: Temporary action [MoveLeft_X,MoveLeft_Y X Y_axis2d] defined.
LogSteamVRInputDevice: Display: Temporary action [MoveLeft_X,MoveLeft_Y X Y_axis2d] defined.
LogSteamVRInputDevice: Display: Temporary action [MoveRight_X,MoveRight_Y X Y_axis2d] defined.
LogSteamVRInputDevice: Display: Temporary action [MoveRight_X,MoveRight_Y X Y_axis2d] defined.
LogSteamVRInputDevice: Display: Temporary action [SqueezeLeft axis] defined.
LogSteamVRInputDevice: Display: Temporary action [SqueezeRight axis] defined.
LogSteamVRInputDevice: Display: Temporary action [TeleportDirectionLeft_X,TeleportDirectionLeft_Y X Y_axis2d] defined.
LogSteamVRInputDevice: Display: Temporary action [TeleportDirectionLeft_X,TeleportDirectionLeft_Y X Y_axis2d] defined.
LogSteamVRInputDevice: Display: Temporary action [TeleportDirectionRight_X,TeleportDirectionRight_Y X Y_axis2d] defined.
LogSteamVRInputDevice: Display: Temporary action [TeleportDirectionRight_X,TeleportDirectionRight_Y X Y_axis2d] defined.
LogSteamVRInputDevice: Searching for Controller Bindings files at: ../../../../../../Unreal Projects/4.21/GameWorks/SoulOccupant/Config/SteamVRBindings
LogSteamVRInputDevice: Warning: Unable to determine controller type for this binding file, skipping: ../../../../../../Unreal Projects/4.21/GameWorks/SoulOccupant/Config/SteamVRBindings/steamvr_manifest.json
LogOcInput: OculusInput is initialized

**Comment by keithbradner** [comment]
Looks like you also have the Oculus plugins enabled. I believe those take precedence on the engine side. You'll need to disable the oculus plugins if you want to use the SteamVR Input Plugin.

**Comment by mikeyboybs** [comment]
![2yolob](https://user-images.githubusercontent.com/20828914/56175628-34bc8480-5fb5-11e9-9106-a19717e40154.gif)

Thank you for the help @keithbradner! it goes to show I still have a ways to go. Such a simple thing. :)
