### ISSUE TITLE
Maps missing from content folder in Sample File download

### ISSUE THREAD

**Issue by Eyesaac** [ValveSoftware/steamvr_unreal_plugin#38]
There are no maps in the content folder for the sample map download. 

Edit: It worked when I opened it in Unreal version 4.19 but not in 4.22.

**Comment by 1runeberg** [comment]
Hi @stearnsi1 -- is this the Marketplace version or the source version from github? 

The sample project just links to the sample maps from the plugin. So the plugin needs to be installed in the correct Engine for the sample project to work.

**Comment by Eyesaac** [comment]
That's exactly what it was. Turns out I hadn't installed to that version, my mistake. Feel free to delete this thread.
