### ISSUE TITLE
No input from Knuckles EV3 on Unreal Engine 4.22.2 on Windows 64 bit.

### ISSUE THREAD

**Issue by eugenestrickbag** [ValveSoftware/steamvr_unreal_plugin#39]
I have been having issues with the unreal market place steam vr input plugin. When enabled on unreal engine 4.22.2 there is no input from any motion controller. There is no tracking of the controllers or any input from buttons, trackpads or thumbsticks. I tested this with both the knuckles EV3 controllers and the vive wands with the same result.

My steamvr version is the beta 1.5.6. This was tested on a blank project with no other plugins enabled besides steamvr. When debugging the input I can see that input is being captured it just doesn't seem to be received by unreal engine. 

I tried opening steamvr before opening the engine and opening it after unreal engine and neither had any effect.

**Comment by 1runeberg** [comment]
Hi @eugenestrickbag !

Did you add input mappings in your project?

The SteamVR input system requires Action and Axis key mappings defined so that it can properly generate the correct action and controller manifests.

We've made a quick start here to try out the sample maps:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/Quickstart

Also, we've made a fully working sample project her you can try out:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin.zip

Check them out if you haven't yet and let me know you go! :)

Cheers,
Rune

**Comment by eugenestrickbag** [comment]
Yeah I had input bindings setup. With bindings setup and all those things generated there is no input from the controllers and they are locked to the tracking origin. Part of the problem is without the plugin enabled the tracking is fine for the controllers but when I enable the plugin it breaks all input and tracking for all motion controllers.

**Comment by 1runeberg** [comment]
Hi @eugenestrickbag - can you try the sample project and let me know if that's working from your end?

It sounds like the bindings aren't being loaded in for some reason. Typical causes are:

- Other plugins that uses SteamVR Input conflicts with the plugin
- Engine modifications that has tangential effect to the engine input system/pathways

**Comment by eugenestrickbag** [comment]
The sample project works as intended.

**Comment by 1runeberg** [comment]
Must've been a missed setup step then as the sample project was made from the Blank Blueprint project.

Can you try double-checking the steps on the quickstart here please:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/Quickstart

Check the steps on adding sample inputs to your project and test them using the sample maps included in the plugin.

let me know how you go!

Cheers,
Rune

**Comment by eugenestrickbag** [comment]
Followed all the steps and tested the sample maps and still the same.

**Comment by 1runeberg** [comment]
Can you try adding a Project Name in your Project Settings if there's none there? 

Failing that, are you able to do a diff on files from our Sample project with the files on your Blank project? Have a look at what's different as they are based from the same template so should function the same. Unless we missed an obvious step in our documentation which I'm curious about.

Otherwise, if you can post screenshots of how your Input Dashboard looks like, as well as your Input Settings under Engine > Input, that'll help. thanks.

**Comment by 1runeberg** [comment]
Hi @eugenestrickbag - any luck?

**Comment by mckress5433** [comment]
I'm having the same problem. My motion controllers are not tracking. I've followed the quick start guide verbatim and the suggestions you listed above. Here is a screenshot of the Input Dashboard. My project name is MyProject2.

![image](https://user-images.githubusercontent.com/8797486/59726079-23366980-91fe-11e9-81d6-5616e4bc47bf.png)

**Comment by 1runeberg** [comment]
Hi @mckress5433, sorry didn't see this comment earlier. not sure this is the same issue though. can you send me your logs (in Saved directory) of your project please and I'll have a look. 

If you can open a different issue as well for this that'll help for tracking and ensure I don't mix it up. Thanks.

**Comment by mckress5433** [comment]
I created a new project so that I could list out the steps to my approach in a new issue I was going to open, but the project works. So I figured I'd just post here that everything is working now.

**Comment by 1runeberg** [comment]
@mckress5433 - thanks! glad you got it sorted.

@eugenestrickbag - how's your project going?

**Comment by 1runeberg** [comment]
No response - closing for now. Please reopen if you're still having issues :)

**Comment by dddubbb** [comment]
@1runeberg I am having exactly the issue described. Everything works fine in editor. After building in 4.22 win64 the motion controller components stay at the tracking origin.
Disabling steamVR input for Unreal plugin fixes the issue. Running Beta Version 1.0-sdk 1.4.18 from the marketplace.
Also using Mordentrals VR expansion plugin. First tried to remove his OpenVRPlugin to try and remove conflicts but this didn't change anything.

Been trying to troubleshoot it for a while, not the most technical person. Going to go through your troubleshooting advice above but was hoping @eugenestrickbag might have discovered the problem.

**Comment by 1runeberg** [comment]
@dddubbb - Can you open a different issue for this please, as it's getting mixed up with other issues. thanks.

There is a known issue with VRE, I believe mordentral recommends to remove the OpenInput module to ensure shipping builds work.

I'm not sure if mordentral has already moved out his OpenInput module as a separate plugin, you need to disable this specific plugin if you have it.

**Comment by dddubbb** [comment]
@1runeberg I'll open a new issue after trying this current fix. I have removed his open input module but still experience the issue. I chatted to him briefly and tried a few similar things and he looked over my binding files.
