### ISSUE TITLE
Crash when trying to add virtual bone to UE4HandSkeleton

### ISSUE THREAD

**Issue by TarasDev** [ValveSoftware/steamvr_unreal_plugin#43]
Assertion failed: Pose.GetNumBones() == UE4HandSkeleton::GetBoneCount() [File:D:\Build\++Portal+Dev-Marketplace+Full\Sync\LocalBuilds\PluginTemp\HostProject\Plugins\SteamVRInput\Source\SteamVRInputDevice\Private\AnimNode_SteamVRInputAnimPose.cpp] [Line: 150]

**Comment by 1runeberg** [comment]
Hi @TarasDev - Yes, this is right. The assert is there as we do not support other skeletons for the animation retargetting other than the stock UE4 one (unmodified).
