### ISSUE TITLE
Add "Both Hands" option to Haptics Node

### ISSUE THREAD

**Issue by sbsce** [ValveSoftware/steamvr_unreal_plugin#46]
Sometimes, it's required that both hands play the same haptics. Would be easy to have a "Both" option additionally to "Right" and "Left" in the PlaySteamVRHapticFeedback function.

**Comment by 1runeberg** [comment]
Had a look at this, we won't be implementing any enhancements on this node as it has potential carry-on effects on other nodes and/or we may need to implment by having an additional "both" enum.

You can however create a fork for this or simply add an additional node for both left & right

We also support standard Haptic Curves, Play Haptic node from the engine is implemented similarly, so we wouldnt want to stray too much from engine practice.
