### ISSUE TITLE
Vive Shoulder button input not functioning 

### ISSUE THREAD

**Issue by Eyesaac** [ValveSoftware/steamvr_unreal_plugin#47]
After installing the plugin and following the input remapping process, I can't seem to get the motion controller shoulder button input to work for the Vive controllers.  No issues with the Index.

As a side note, there is also a "SteamVR HTC Vive ..."  input binding missing for the shoulder buttons, maybe this is related, maybe I'm missing something.

The "Motion Controller (R)/(L) Shoulder" does not seem to work whether it's as a binding or called specifically in the blueprints.  I am using engine version 4.19.

Thanks for any help.

**Comment by 1runeberg** [comment]
Hi @stearnsi1 - Can you:

1. Backup your Project's Config folder
2.  Add in "Steam VR Vive Controller Application Press Left/Right" in the Engine > Input settigns
3. Regenerate both the Action manifest and Controller Bindings using the Toolbar
4. Restart the Editor

Let me know how it goes!

**Comment by Eyesaac** [comment]
Thanks again for the help. I tried this and realized in the process that the "shoulder" buttons are actually called "application" buttons which work perfectly fine.  I had mistaken the terminology.

**Comment by Eyesaac** [comment]
It seems that the inputs work fine in the editor, however there are issues after shipping the build.  This time it is the "a" and "b", and trigger click not functioning on the index controller.  For the Vive controllers, the grip & shoulder aren't functioning after shipping the game.  I am not sure if this has anything to do with tweaking the input settings but I have already tried restoring the backup config folder and no luck.  

Something notable:
The controls that aren't working were new bindings created after the plugin was installed.

Not sure if this is my limited knowledge or another issue.  Thanks for any help.

**Comment by 1runeberg** [comment]
HI.... did you modify the bindings at all in the SteamVR Input dashboard?

**Comment by Eyesaac** [comment]
I created these bindings in: Project Settings --> Input 
Then ran the plugin buttons: "Add Sample Inputs"-->"regenerate Action Manifest"-->"Regenerate Controller Bindings"-->"Reload Action Manifest"
I do see the correct bindings when I open the input dashboard.

**Comment by 1runeberg** [comment]
Can you provide me with a screenshot of the bindings if possible?

if you are in the Knuckles Discord server, might be also faster.

**Comment by Eyesaac** [comment]
![InputScreenshot1](https://user-images.githubusercontent.com/51517910/59648616-ae0b5b80-914d-11e9-90b7-b7a355150fd6.JPG)
![InputScreenshot2](https://user-images.githubusercontent.com/51517910/59648617-aea3f200-914d-11e9-875b-912ce644d428.JPG)

**Comment by 1runeberg** [comment]
sorry i meant the SteamVR Input Dashboard.

**Comment by 1runeberg** [comment]
or hit me up in discord runeberg#9344

**Comment by Eyesaac** [comment]
I think this is what you're looking for? Thanks
![InputScreenshot3](https://user-images.githubusercontent.com/51517910/59670282-b1243d00-9189-11e9-95b5-4b0deb87029f.JPG)
![InputScreenshot4](https://user-images.githubusercontent.com/51517910/59670283-b1bcd380-9189-11e9-92cd-6890f88d40c7.JPG)
![InputScreenshot5](https://user-images.githubusercontent.com/51517910/59670395-df098180-9189-11e9-9b23-8ecff392404c.JPG)

**Comment by 1runeberg** [comment]
I was actually hoping to see how the Game/Project Title is written on top.

At any rate, when you make changes to the dashboard, ensure that you are using the "Replace Default Binding" button. This ensures that your changes are saved to your UE project and not to your local steamVR user  profile

Cheers,
Rune

**Comment by Eyesaac** [comment]
Strangely, I cannot find the "Replace Default Binding" button.
This one has the title in it:
![InputScreenshot6](https://user-images.githubusercontent.com/51517910/59723871-d8b0ef00-91f5-11e9-9e07-66f87fe026ba.JPG)
Should it match the title of the actual Unreal project?
Thanks

**Comment by 1runeberg** [comment]
You need to be editing the binding to see it. It could be an explanation for the input mismatch you are having in packaged projects.

This issue can be quite complicated though from here, so I suggest if we can move it to a chat platform. Might be faster to resolve. (Discord: runeberg#9344)

**Comment by Eyesaac** [comment]
Ok thanks, added (Isaac#0051)
