### ISSUE TITLE
HMD Proximity seems to not be able to be bound

### ISSUE THREAD

**Issue by smapty** [ValveSoftware/steamvr_unreal_plugin#48]
I'm not exactly sure where this issue resides, but I think the plugin should allow for proximity sensor support. Our game previously used this in order to have the game more responsive to the user wearing the HMD. I tried adding it manually by creating an action in the action manifest and binding to the VIVE's /user/head/proximity path, but it wasn't working and I wasn't sure how to get it working. In that particular case, I'd probably want it to use a binding that was more generic as to remain compatible with other HMDs as opposed to setting it up for a specific HMD.

**Comment by 1runeberg** [comment]
Hi @smapty - are you needing it so user's are able to rebind? The plugin shouldn't interfere with the "Get HMD Worn State" BP function, and should return accurate results depending on headset capability.

**Comment by 1runeberg** [comment]
Anyways, addressed this in develop branches.

To use, add the new key "SteamVR HMD Proximity" to an Action Mapping and regenerate Action Manifest (warning: overwrite) and controller bindings (warning: overwrite)
