### ISSUE TITLE
When cooking for the PC we get a number of SteamVRInput warnings

### ISSUE THREAD

**Issue by martinsweitzer** [ValveSoftware/steamvr_unreal_plugin#5]
Using this command line:

call Engine\Build\Batchfiles\RunUAT BuildCookRun -project="MyProj\MyProj.uproject" -platform=win64 -build -package -cook -stage -pak -clientconfig=Development -archive

we get:

LogClass: Warning: FAnimNode_SteamVRInputAnimPose::MotionRange is not initialized properly
  LogInit: Display: LogClass: Warning: FAnimNode_SteamVRInputAnimPose::Hand is not initialized properly
  LogInit: Display: LogClass: Warning: FAnimNode_SteamVRInputAnimPose::HandSkeleton is not initialized properly
  LogInit: Display: LogClass: Warning: BoolProperty FAnimNode_SteamVRInputAnimPose::Mirror is not initialized properly
  LogInit: Display: LogClass: Warning: FAnimNode_SteamVRSetWristTransform::HandSkeleton is not initialized properly
  LogInit: Display: LogAutomationTest: Warning: FAnimNode_SteamVRInputAnimPose::MotionRange is not initialized properly
  LogInit: Display: LogAutomationTest: Warning: FAnimNode_SteamVRInputAnimPose::Hand is not initialized properly
  LogInit: Display: LogAutomationTest: Warning: FAnimNode_SteamVRInputAnimPose::HandSkeleton is not initialized properly
  LogInit: Display: LogAutomationTest: Warning: BoolProperty FAnimNode_SteamVRInputAnimPose::Mirror is not initialized properly
  LogInit: Display: LogAutomationTest: Warning: FAnimNode_SteamVRSetWristTransform::HandSkeleton is not initialized properly

**Comment by 1runeberg** [comment]
Addressed in internal branches, included in upcoming 0.6a release
