### ISSUE TITLE
Having issues getting Rift controllers to work

### ISSUE THREAD

**Issue by OptimisticMonkey** [ValveSoftware/steamvr_unreal_plugin#52]
Sample project doesn't seem to recognize rift controllers

**Comment by 1runeberg** [comment]
Hi @OptimisticMonkey - I'm unable to replicate this issue. Can you send me please your UE4 Project logs?

runeb@valvesoftware.com

**Comment by xXWhirlybirdXx** [comment]
I'm Possibly having the same issue. Using Oculus Rift S and Unreal 4.22.3. Hands move, but fingers can't close or grab anything. I tried my own new project and the SteamVR sample project.

**Comment by OptimisticMonkey** [comment]
Thanks @1runeberg - I just received a Valve Index :-)….  so poor Rift is temporarily disconnected -  I will try again and post info 

BTW - SteamVRInput seems to work fine with Index.

**Comment by OffLEashEnt** [comment]
Also having trouble getting Rift inputs to work.

Edit - they work if I disable SteamVR plugin.

Edit 2 - Enabling SteamVR plugin and disabling Oculus plugin and now the SteamVR inputs for Oculus work.

**Comment by 1runeberg** [comment]
@xXWhirlybirdXx , @OptimisticMonkey - Are you still having issues when the the Oculus plugin is turned off? At the moment, as the engine loads the Oculus plugin first prior to SteamVR, having it enabled breaksparts of SteamVR Input, so we suggest disabling the Oculus plugin for SteamVR builds/editing of your project.

**Comment by 1runeberg** [comment]
Closing this now. Please feel free to re-open if you are still facing issues with your Rift S. Cheers.
