### ISSUE TITLE
Oculus Rift Having Issues

### ISSUE THREAD

**Issue by SimplyClueless** [ValveSoftware/steamvr_unreal_plugin#54]
Just saw this plugin and wanted to test out how the gripping worked as I was struggling with it myself. When playing in VR my head is stuck in the ground and my controllers don't want to give any input, nor do they match up with their actual position in the world. Oculus is always open by default as I can't use my Rift without that open but I have to manually open Steam VR. Could the clash between the two have something to do with it?

**Comment by SimplyClueless** [comment]
After some experimenting I found that I needed to disable the Oculus plugin from the plugins menu, now it works like a dream!

**Comment by xXWhirlybirdXx** [comment]
> After some experimenting I found that I needed to disable the Oculus plugin from the plugins menu, now it works like a dream!

Thank you! this solved my problem

**Comment by 1runeberg** [comment]
yes, we do advise disabling the engine's Oculus plugin when using SteamVR Input so it wouldn't override input controls.

Glad you got it all sorted.
