### ISSUE TITLE
Converting To C++

### ISSUE THREAD

**Issue by SimplyClueless** [ValveSoftware/steamvr_unreal_plugin#56]
I just tried converting the sample project into c++ to test some classes and it gave me an error in the editor saying that the actor class was created but I couldn't access it until i rebuild the code from the source. I closed the project and tried to generate project source file yet I keep getting this error and I have absolutely no idea why!

Running C:/Program Files/Epic Games/UE_4.22/Engine/Binaries/DotNET/UnrealBuildTool.exe  -projectfiles -project="E:/Unreal Projects/Project Files/SteamVRInputPlugin/SteamVRInputPlugin.uproject" -game -rocket -progress -log="E:\Unreal Projects\Project Files\SteamVRInputPlugin/Saved/Logs/UnrealVersionSelector-2019.07.14-00.06.18.log"
Discovering modules, targets and source code for project...
While compiling E:\Unreal Projects\Project Files\SteamVRInputPlugin\Intermediate\Build\BuildRules\SteamVRInputPluginModuleRules.dll:
e:\Unreal Projects\Project Files\SteamVRInputPlugin\Intermediate\Source\SteamVRInputPlugin.Build.cs(3,14) : error CS0101: The namespace '<global namespace>' already contains a definition for 'SteamVRInputPlugin'
e:\Unreal Projects\Project Files\SteamVRInputPlugin\Intermediate\Source\SteamVRInputPlugin.Target.cs(3,14) : error CS0101: The namespace '<global namespace>' already contains a definition for 'SteamVRInputPluginTarget'
ERROR: Unable to compile source files.

**Comment by 1runeberg** [comment]
Hi - A hot recompile should have been possible if you're adding it within the project code.

If you're adding classes to the plugin and/or have the same class names as those that already exist in the plugin, then you might get this error.

Try deleting the following folders (both plugin & project):

- Binaries
- Intermediate
- Saved
- Build (if it exists)
- .vs (if it exists)
- SteamVRInputPlugin.sln file (if it exists)

If this is  just the test project, also delete the 

-  SteamVRInputPlugin\Source subdirectory

Try opening the .uproject file again and it should load. 

When you add a C++ class, try adding a "GameModeBase" type and make sure you are adding hte C++ class to your project and not to the plugin. 

Choose a name such as the default "MyGameModeBase". This should cleanly convert the demo project to a C++ project and you can then properly modify C++ code.

I hope that helps.

**Comment by SimplyClueless** [comment]
It happened to be an issue caused by the existing .Build.cs and .Target.cs. I tried deleting them and then building the source and it managed to work!
