### ISSUE TITLE
cannot access private member declared in class 'UInputSettings' & 'FSteamVRInputDevice': cannot instantiate abstract class

### ISSUE THREAD

**Issue by CarstenZarbock** [ValveSoftware/steamvr_unreal_plugin#57]
Can't compile due to

```
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2259	'FSteamVRInputDevice': cannot instantiate abstract class	VRGame	D:\Unreal Projects\VRGame\Plugins\SteamVRInput\Source\SteamVRInputDevice\Private\SteamVRInputDeviceModule.cpp	41	
Error	C2248	'UInputSettings::ActionMappings': cannot access private member declared in class 'UInputSettings'	VRGame	D:\Unreal Projects\VRGame\Plugins\SteamVRInput\Source\SteamVRInputDevice\Private\SteamVRInputDevice.cpp	3902	
Error	C2248	'UInputSettings::AxisMappings': cannot access private member declared in class 'UInputSettings'	VRGame	D:\Unreal Projects\VRGame\Plugins\SteamVRInput\Source\SteamVRInputDevice\Private\SteamVRInputDevice.cpp	3913	
```

**Comment by CarstenZarbock** [comment]
Is it a proper fix to override GetHandJointPosition(...) in FSteamVRInputDevice and use the Getter for ActionMappings (GetActionMappings()) & AxisMappings (GetAxisMappings()) or am i missing something?

Thank you for the formatting edit.

**Comment by 1runeberg** [comment]
Hi @carstenzarbock - if you are using UE4. 23 Preview, please use the plugin in branch develop-4.23:

https://github.com/ValveSoftware/steamvr_unreal_plugin/tree/develop-4.23

**Comment by CarstenZarbock** [comment]
> 
> 
> Hi @CarstenZarbock - if you are using UE4. 23 Preview, please use the plugin in branch develop-4.23:
> 
> https://github.com/ValveSoftware/steamvr_unreal_plugin/tree/develop-4.23

I am indeed on 4.23 prev, wasn't aware. Thanks, works!
