### ISSUE TITLE
New input nodes like "grip strength" always returning 0, only A button and thumbstick work, which return '[STEAMVR INTERNAL] Temporary' bindings

### ISSUE THREAD

**Issue by StevenWaltherMedia** [ValveSoftware/steamvr_unreal_plugin#60]
There are a whole bunch of new valve knuckle bindings that showed up after putting in this plugin but none of them work, and instead only a few buttons return what appears to be internal testing bindings (I used an 'any key' event and had it display the key name). It feels like I have an old version of the plugin but I downloaded the most recent zip on the github page (4.22)

**Comment by 1runeberg** [comment]
Hi @StevenWaltherMedia. There's some required setup to use the new input System properly. A good place to start if you haven't already is our Quick Start Guide:

https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/Quickstart

There is also a sample project you can check out which might be good to try first:
https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin.zip

The new controller keys are meant to be used with the Action Bindings and won't trigger any events if used directly. Key and Axis Action Input events will need to be used.

There's no Grip Strength that came with the plugin, unless you meant Grip Force available for Index Controllers only. All new keys are pre-pended with SteamVR + {Manufacturer} + {Product Name}.

Let me know how you go!

**Comment by StevenWaltherMedia** [comment]
Hey there, thanks for the fast reply!

I went through the quick start guide and got it all up and running!

However there are still a few missing functions in the bindings, specifically capacitive touch information for the touch pad (both trackpadpress and trackpadtouch return 1 when force is applied to the trackpad, but 0 when your thumb is resting on the pad with no force)  and the grip 'paddle' touch location

Observing the grip paddle, its evident that it is capable of detecting where there is touch information, not just the grip power. Running your finger up and down the paddle and watching the fingers on the demo pawn clench and release in accordance of your location confirms this.

I looked at the demo pawn, as the individual finger functionality is working there, but it appears that it is a custom animation node in the animbp, which I can't really derive information from to make gameplay from (I mean i /could/ read the rotation info from the finger bones and make a bunch of float values but that's super impractical)

I would like to add that I'm not much of a coder, so if there's functionality in the code that is waiting to be exposed that's on me

**Comment by 1runeberg** [comment]
Hi @StevenWaltherMedia  - I'm guessing you're using Index Controllers then. For what you're describing, you'll need axis bindings.

Have a look at the Sample Inputs:
TeleportDirectionLeft_X
TeleportDirectionLeft_Y

For Index controllers, they return the X & Y axis values of the the thumb. Unreal doesn't have native support for Vector2 in the input mappings, so you need to define the X & Y values individually. 

The plugin will recognise them belonging to each other as a Vector 2 (X & Y) if it fits the following criteria:

(1) Two actions are similarly named with just the X & Y at the end being different (e.g. TeleportDirection_X, TeleportDirection_Y)
(2) The controller inputs for the actions in (1) have matching X & Y axis inputs belonging to the same controller type AND hand. For example:

TeleportDirection_X: SteamVR Valve Index Controller (L) Trackpad X
TeleportDirection_Y: SteamVR Valve Index Controller (R) Trackpad Y

Regenerating the Controller Bindigns (overwrite operation), will make the plugin create the appropriate json entries for steamvr and you should then be able to use the X & Y axis inputs.

I hope that helps, lemme know if its not clear as it can be slightly confusing. Looking at the sample inputs we provided though, hopefully will make it a bit easier to understand the concept for Vector2s (axis X & Y).

**Comment by StevenWaltherMedia** [comment]
Yes, I was able to set up the trackpad no problem, just find the correct axis from the list, apply it to a new binding, and use the steam vr input regenerate functions.

My problem is on the grip paddle. I want to be able to recreate the ability to move individual fingers based on where pressure is on the grip paddle to make functionality based on finger positions, but I can't find any axis binding for the 'where' part, just the grip power.

**Comment by 1runeberg** [comment]
Individual finger curl values for the Index Controllers aren't exposed directly as axis inputs. You'll need to use the node "Get Finger Curls and Splays".

We provided a sample on how to use these values in BP_JoeJeffCharacter, in the EventGraph when detecting custom gesture recognition.

**Comment by StevenWaltherMedia** [comment]
That's the magic bullet I was looking for! I'm sorry I missed it in the example blueprint!

Thanks so much!
