### ISSUE TITLE
Moving Steam VR assets to my own project

### ISSUE THREAD

**Issue by samuelthomson** [ValveSoftware/steamvr_unreal_plugin#61]
Hello, I have the recent VR sample project working for HTC Vive/Unreal v4.21: https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/Quickstart

However, I haven't been able to get the MotionControllerPawn working in my own project. Here's what I've tried to do:

Install the SteamVRPlugin
click SteamVRInput in the toolbar, and then click Add Sample Inputs, Regenerate Action Manifest, Regenerate Controller Bindings, and Reload Action Manifest
drop a copy of MotionControllerPawn into my scene
makesure my navmesh is there
When I run the game, I can look around in VR but I just seem to be floating in a random spot in the game, and I have no hands/controllers. I also get a "default pawn" asset spawning in my scene and I think this could be what actually gets possessed when the game runs.

I also get the following error message in the message log that might be relevant:

Blueprint Runtime Error: “Accessed None trying to read property K2Node_DynamicCast_AsHand_Anim_Interface”. Blueprint: BP Motion Controller, Function: Execute Ubergraph BP Motion Controller, Graph: Event Graph, Node: Set Grip State

Can anyone point me in the right direction? Are there other ways to get the VR sample assets working in my project? Have I forgotten to assign something important?

**Comment by samuelthomson** [comment]
Hello, I have the recent VR sample project working for HTC Vive/Unreal v4.21: https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/Quickstart

However, I haven't been able to get the MotionControllerPawn working in my own project.  Here's what I've tried to do: 

- Install the SteamVRPlugin
- click SteamVRInput in the toolbar, and then click Add Sample Inputs, Regenerate Action Manifest, Regenerate Controller Bindings, and Reload Action Manifest
- drop a copy of MotionControllerPawn into my scene 
- makesure my navmesh is there

When I run the game, I can look around in VR but I just seem to be floating in a random spot in the game, and I have no hands/controllers.  I also get a "default pawn" asset spawning in my scene and I think this could be what actually gets possessed when the game runs.   

I also get the following error message in the message log that might be relevant: 

Blueprint Runtime Error: “Accessed None trying to read property K2Node_DynamicCast_AsHand_Anim_Interface”.  Blueprint: BP Motion Controller, Function: Execute Ubergraph BP Motion Controller, Graph: Event Graph, Node: Set Grip State

Can anyone point me in the right direction?   Are there other ways to get the VR sample assets working in my project?  Have I forgotten to assign something important?

**Comment by samuelthomson** [comment]
For anyone else struggling, I've done the following and it seems to have fixed it: 

- refresh the steam VR input
- assign hand meshes and animations in the MotionControllerPawn settings
- changed the construction script on BP_MotionController to use a "Switch on EcontrollerHand" node.

**Comment by 1runeberg** [comment]
Ideally, the sample assets shouldn't be used as we may be updating them and can affect your game, if you make modifications.

You can use them as a starter though either by copying assets you need or creating child BP classes based on the sample ones we provided.

Glad however you got things sorted on your end for now. Any other questions on this, let me know!
