### ISSUE TITLE
Nodes "require refresh" upon reopening project

### ISSUE THREAD

**Issue by imaekgames** [ValveSoftware/steamvr_unreal_plugin#62]
When I close and reopen my project all of the SteamVR Input nodes are broken and require a "refresh" and then they are just fine. 

Extra: What's odd is that we tried making clones of projects and migrating to other projects and it's extremely isolated with this specific project(possibly specific Blueprints) which was a C++ project that was originally migrated from a 4.21 project.

**Comment by 1runeberg** [comment]
Hi @imaekgames - can you let us know which nodes in particular that need refreshing?

**Comment by 1runeberg** [comment]
or is it just Get Curls and Splays?

**Comment by imaekgames** [comment]
It's all of them says @parthnaik92

**Comment by imaekgames** [comment]
Here's two supporting images that might help 
https://i.gyazo.com/1f1550d30512c684e68ac9e7449e2397.png 
https://i.gyazo.com/08eca560bcb411fc9ad31c656007af4c.png

**Comment by 1runeberg** [comment]
Thanks @imaekgames @parthnaik92 - can you send me please the UE Project Logs to runeb@valvesoftware.com

**Comment by imaekgames** [comment]
Sent you an email from michael@vectre.xyz (sometimes email servers block our .xyz address so lemme know if u received)

**Comment by 1runeberg** [comment]
Hi.. Got it, thanks!

From the logs, it seems like another plugin, Dialogue System (?), is doing some BP compiles or you've modified content for that plugin and added our nodes in them.

This plugin also loads in the same loading phase as ours - which is pretty much the last loading phase (PostEngineInit).

Unfortunately, there's no guarantee which plugin would be loaded last in this scenario, it seems that this plugin needs to be loaded last in this sequence as it compiles project BPs which can host nodes from other plugins:

https://api.unrealengine.com/INT/API/Runtime/Projects/ELoadingPhase__Type/index.html

If you have a custom engine, you can try adding a new loading phase here so it gets loaded last.

From our end, ours need to be in PostEngineInit unfortunately so I wouldn't advise moving ours at an earlier phase.

**Comment by 1runeberg** [comment]
@imaekgames @parthnaik92 - can you migrate some parts with the issue (guessign its with the dialogue system) on a new project and send it over to me? Epic wants to have a stab at it.

**Comment by parthnaik92** [comment]
@1runeberg thanks for all the help! We will send you a project with the dialogue system plugin by the end of the day. You were correct when you said this "Dialogue System (?), is doing some BP compiles or you've modified content for that plugin and added our nodes in them." We were using "Get Finger Curls and Splays" node in our VR hand animation BP, which was referenced in the VR Pawn BP, which in turn was referenced in one of the BPs of our dialogue system setup. When I removed the VR Hand animation BP from VR Pawn, all the errors were gone.

**Comment by parthnaik92** [comment]
I changed the loading phase of the dialogue plugin to "PostEngineInit" from "PreDefault" and everything is working fine now. This could be a temporary fix.

**Comment by parthnaik92** [comment]
@1runeberg sent you the project

**Comment by 1runeberg** [comment]
Hi @parthnaik92 - forwarded that to Epic, but I think there's not really any action to do since moving the loading phase worked. Epic just wanted to have a closer look at a migrated project in case it was just a project config issue that we could be missing from the logs.

**Comment by 1runeberg** [comment]
Closing for now :)
