### ISSUE TITLE
Is it possible to use this plugin to get input from more than 2 Vive controllers?

### ISSUE THREAD

**Issue by finn-wa** [ValveSoftware/steamvr_unreal_plugin#66]
Hi, I'm doing a research project which involves two people interacting in VR on the same system. Currently I have two Vive Controllers connected through the headset and another two connected through Vive Tracker dongles (they are recognised by SteamVR as controllers). I can get their position and rotations by using the native UE4 functions GetValidTrackedDeviceIDs and GetTrackedDevicePositionAndOrientation. However, I'm not sure how to get button input from them as all of the input functions refer to a left and a right controller. Is it possible?

**Comment by 1runeberg** [comment]
Hi - No, we only support two controllers - one for the left hand and the other for the right with the new input system.

Vive Trackers are supported via the new input system however via the SteamVR Input interface but they dont have the same level of button support.

**Comment by finn-wa** [comment]
Is there any way I can make the extra controllers use the Tracker input system? Can I flash the firmware or something?

**Comment by 1runeberg** [comment]
there's no support for it in the runtime. there are only two paths - /input/left & /input/right which corresponds to inputs for the left & right controllers respectively.

is the research reliant on having hte players in a single physical system/PC rather than a single VR environment?

**Comment by finn-wa** [comment]
Yes, it's an interactive spectator system so ideally it would be running on one PC. Two PCs would make things a lot easier but unfortunately I've run out of time to make the switch. I think I'll be going with my backup option which is taping Vive Trackers to Wii remotes and getting the input from them. Obviously using the pogo pins on the trackers would be a more elegant solution but I don't have the resources or knowledge for that.

**Comment by 1runeberg** [comment]
one sec.. are you actually using TRACKERS and not two extra Vive Controllers?

if you are, is it the blue logo ones or the grey logo ones?

**Comment by finn-wa** [comment]
I have access to 4 Vive Trackers (2018 blue logo ones) and 4 Vive Controllers. The original plan was to have the primary VR user using their Vive controllers as normal, and then I'd tape Vive Trackers to some kind of one-handed controller (like a Wii remote) to act as the second player's controllers. Last night I discovered that the Tracker dongles can be used to connect extra controllers to SteamVR. I thought that using actual Vive Controllers for the second player would be a nicer solution than the Wii remote thing.

**Comment by 1runeberg** [comment]
not 4 Vive Controllers no.

tracker buttons can be mapped though to actions (blue logo ones)

**Comment by 1runeberg** [comment]
closign htis for now.
