### ISSUE TITLE
Some actions fail to work under Shipping build configuration

### ISSUE THREAD

**Issue by CrimsonZen** [ValveSoftware/steamvr_unreal_plugin#67]
I have a project based on a couple-weeks old 4.22 GitHub version of the plugin, where all actions were working fine in Shipping packaged builds and in editor. I ran into issues today after a couple days of developing in-editor with some newly added actions:

* Added about 10 actions to the project's inputs, such as `UINavEnterRight` (to correspond to pressing "A" on the Right controller.) Each action was assigned to:
* * An auto-generated temporary SteamVR input
* * A SteamVR bind for a Vive Controller (like HTC Vive Controller (R) Grip Press)
* * A SteamVR bind for an Oculus Touch
* * A SteamVR bind for an Index Controller
* Regenerate/Regenerate/Reload
* Ran Packaging (Shipping, Win64, Full Rebuild) into clean folder
* Opened packaged game, and noticed that none of the *new* binds worked. Old binds continued to work.
* * Binds showed up as assigned in the bindings tool if I manually located the entry for ProjectName-Win64-Shipping.exe, and registered properly in the debug view when pressed, but game would not react to them
* Repackaged (Development, Win64) into clean folder
* Opened dev packaged game; all binds work in this version of the game.
* Tried rebuilding & testing Shipping once again; issue continued to manifest but only in the Shipping configuration
* Works fine in editor

Will try to get more details.

**Comment by 1runeberg** [comment]
When running the shipping build, are you running the Editor as well in the background? 

Also, have you tried checking the action mappings from the Input Debugger (SteamVR Dashboard)?

**Comment by CrimsonZen** [comment]
* Am not running editor in background.
* Input debugger lights up the correct actions but I get no behavior in-game.

Additional discovery: it works fine in the `DebugGame` packaging configuration.

**Comment by 1runeberg** [comment]
are you able to try the build in a different machine? One that hasn't run this app or the editor build before?

**Comment by CrimsonZen** [comment]
Not at the moment, unfortunately.

**Comment by 1runeberg** [comment]
can you post screenshots of the SteamVRInput dashboard (full window) with the mappings and also the Input debugger. (Shipping build)

**Comment by CrimsonZen** [comment]
Bindings for shipping build:
![image](https://user-images.githubusercontent.com/2038173/64741385-2499ca00-d4ad-11e9-95ea-3700fb376cb3.png)
![image](https://user-images.githubusercontent.com/2038173/64741389-2c596e80-d4ad-11e9-9fa4-cdac9524fa96.png)
![image](https://user-images.githubusercontent.com/2038173/64741394-34191300-d4ad-11e9-9df3-b1c3f59987f8.png)

Part of the Input Debugger with relevant actions:
![image](https://user-images.githubusercontent.com/2038173/64741510-b7d2ff80-d4ad-11e9-83ca-e2bc6fa8e2f3.png)

**Comment by 1runeberg** [comment]
Arethe SideGripped Pressed the new actions?

**Comment by CrimsonZen** [comment]
Everything beginning with "UINav" are new. I actually missed the new ones in that screenshot; here's a better one:

![image](https://user-images.githubusercontent.com/2038173/64741786-a9d1ae80-d4ae-11e9-8f67-40844ce2d174.png)

**Comment by 1runeberg** [comment]
Id suggest testing those actions to a simpler mechanic. try rebinding the action to one of hte old actions that actually gets triggered in the game

**Comment by 1runeberg** [comment]
based on your feedback on using just the Enter key, could be something to do with what the functions the action is triggering thats not running properly in a shipping build as keyboard inputs should not fail.

**Comment by CrimsonZen** [comment]
Yeah, something's super fishy. It's particularly strange that the new InputActions in the shipping build work if I copy the build to another machine.

Seems like it's not _likely_ to be SteamVR Input related, unless there's some weird glitch in the action generation pipeline that created a wonky action?

**Comment by 1runeberg** [comment]
that'll be quite unlikely with those results from the Input Debugger.

Dpad actions as generated by the plugin are also used in a major published title, that wouldve broken as well (for a lot of users) if thats the case.

**Comment by CrimsonZen** [comment]
Might be related to this issue: https://answers.unrealengine.com/questions/909490/view.html

**Comment by dillyframe** [comment]
I can confirm that I had the same problem - new input didn't work in packaged build.
After deleting Input.ini in Local/MyProjectName/Saved/Config/WindowsNoEditor and launching game again everything worked as intended as Input.ini was autogenerated again with new input. But it was long before v1 plugin.

I thought it was something project related as the game was already in steam before integrating the plugin

**Comment by CrimsonZen** [comment]
Yep, I managed to confirm that fix earlier today as well, @dillyframe 

Probably safe to close this issue as not being related to SteamVR Input.

**Comment by 1runeberg** [comment]
@CrimsonZen @dillyframe  - Added a convenience node in develop-4.21/4.22/4.23 branches which delete the user's Input.ini file (use with caution):

![image](https://user-images.githubusercontent.com/17371351/68645061-01ea6700-056b-11ea-9b92-922e6ce39836.png)
