### ISSUE TITLE
Root bone of VR glove has a scale of 100?

### ISSUE THREAD

**Issue by jrlvr** [ValveSoftware/steamvr_unreal_plugin#68]
Just wondering why the root bone of the glove has a scale of 100? It is making it rather difficult to re-target the animation to a new glove due to this, and I was wondering if there is a specific reason why it has that scale?

**Comment by 1runeberg** [comment]
Hi @jrlvr - the reason for the scale is that data that comes from SteamVR is in metres and unreal's units are in cm, so we have to apply a conversion to the scale.

Hope that info helps!

Cheers,
Rune

**Comment by xavier150** [comment]
Hi, It is not possible to simply convert this in the code ? With a parameter in Anim BP for rescale the unit so that can adapts to different workflows.

**Comment by 1runeberg** [comment]
It is possible in the plugin code, but that would make an assumption on the skeletal mesh which could be different for different projects. The mesh came from the Unity plugin and it was re-scaled to suit. Other artists may choose to make custom skeletal meshes or use the standard UE4 skeleton.
