### ISSUE TITLE
Input doesn't work when you export the project with the plugin

### ISSUE THREAD

**Issue by MisterGenius0** [ValveSoftware/steamvr_unreal_plugin#69]
I don't know if im missing something but the input works in the editor but when I export the project the input stops working. This issue started with unreal 4.23

**Comment by 1runeberg** [comment]
HI @MisterGenius0  - do you mean in a packaged project?

If you're using Oculus, make sure that the engine's Oculus plugin is disabled and also, try clearing config/input files in  %APPDATA%

**Comment by MisterGenius0** [comment]
Yes, I did mean Package Project.

I deleted folder located C:\Users\...\AppData\Local\UnrealEngine\4.23\Saved\Config
and It didn't fix it. Also, the Oculus plugin is disabled. (I'm Using Vive)

**Comment by 1runeberg** [comment]
There should be a folder with your app name on appdata as well.

**Comment by MisterGenius0** [comment]
Ok, Strange, it's not there in AppData\Local no folder with the project name (I did see an older project there though)

**Comment by 1runeberg** [comment]
Do you have the plugin and steamvr bindings folder in your packaged project?

**Comment by MisterGenius0** [comment]
Yes, Located at D:\WindowsNoEditor\TestProject\Config\SteamVRBindings

**Comment by 1runeberg** [comment]
Can you post a screenshot of the steamvrbindings dashboard? Also, make sure you don't have the editor on when running the build.

**Comment by MisterGenius0** [comment]
Ok Here is One Event Out of many that are not executing 
![Annotation 2019-09-25 093926](https://user-images.githubusercontent.com/39445650/65622976-a7298b80-df7b-11e9-8e2b-52c0fd01c1eb.png)
![Annotation 2019-09-25 100124](https://user-images.githubusercontent.com/39445650/65622982-aa247c00-df7b-11e9-8afd-4b551ddbb6ba.png)
![Annotation 2019-09-25 100113](https://user-images.githubusercontent.com/39445650/65622989-abee3f80-df7b-11e9-8ba5-59ac28791e54.png)

**Comment by 1runeberg** [comment]
Can you post one from the dashboard when running the packaged build?

**Comment by MisterGenius0** [comment]
Ok Found out it might not be a plugin issue. One of the maps it working, So I have to look why the other maps are not working

Thanks for your help :)

**Comment by 1runeberg** [comment]
No prob!

**Comment by mcablePM** [comment]
Is it the first loaded map that has an issue? I've found on 4.23 that I get no events on the first map, but if I load another after that all the buttons and events work as expected.

**Comment by MisterGenius0** [comment]
YES! that's it I was just about to type that lol 👍
