### ISSUE TITLE
Axis input value from Thumbsticks and Trackpads always zero

### ISSUE THREAD

**Issue by Derp101010** [ValveSoftware/steamvr_unreal_plugin#74]
I haven't used earlier versions of the plugin. I updated UE4 to 4.23 and got the current version of the plugin from the marketplace a few days ago.

When I activate it, the axis input (that works without the plugin) from sticks/pads is always zero. I tried it in my own project with code and blueprint input functions, with the VR Template project by Epic and with the plugin's sample project. Also tried both the "Motion Controller..." and the "SteamVR Index ..." bindings. I followed the documentation on updating bindings. When I bind other keys to the same axes under input, they work as expected, just not the index sticks and pads. I noticed that the plugin created [internal] bindings for all my axis inputs except the first (forward axis: left thumbstick Y). I don't know if that's telling you something.
What's strange is that I can move the robot in the sample project with the remote after all, but no other inputs from stick/pad movement will work.

**Comment by 1runeberg** [comment]
Hi @Derp101010 - As UE doesn't have native support for Vector2 axis (combined X,Y floats), which I believe is going to be addressed soon by Epic, you need to configure the axis in a special configuration in order for the plugin to recognize it as a Vector2.

Below is a (unofficial) tutorial on how to set this up:
https://www.youtube.com/watch?v=oi93qXgNBjk&list=PLngZ5l9HmlORHi2E1UzxPxD6BnXHyZ6M0&index=5

Hope that helps, let me know if you have any further questions on this.

Cheers,
Rune

**Comment by Derp101010** [comment]
Ahhh. I did read that part in the documentation, but didn't understand what's so special about having a seperate axis input for each Vector2 component. That's what all my axis inputs looked like... Didn't realize the naming was important. I will try it tomorrow. Thank you. Gonna delete the posts on the steam vr forum I made.

edit: ok, now it works

**Comment by 1runeberg** [comment]
awesome. will close this issue now then.
