### ISSUE TITLE
input binding editor "mirror mode" fails to mirror Oculus Touch X/Y (left hand) vs A/B (right hand) buttons

### ISSUE THREAD

**Issue by benblo** [ValveSoftware/steamvr_unreal_plugin#76]
Title pretty much says it all... editing the left hand in mirror mode, adding a click on X (for a boolean action) results in a right-hand input using the path `"/user/hand/right/input/x"`... should be `"/user/hand/right/input/a"`

**Comment by 1runeberg** [comment]
Hi, the Unreal plugin does not generate or support mirror mode bindings as it reads input configs directly from the engine's bindings menu and requires runtime generated actions based on this configuration.

If you are not using the plugin and directly interfacing with openvr, this is possibly something you can add to this openvr issue:

https://github.com/ValveSoftware/openvr/issues/960

**Comment by benblo** [comment]
Sorry, wrong repo :/, that was meant for the Unity plugin... but I suppose they use the same web UI editor anyway right? Is the OpenVR repo you pointed me to responsible for that UI, or is it still in another place?
Thanks!

**Comment by 1runeberg** [comment]
No prob @benblo. It's actually SteamVR runtime, ideally posted in the steamvr forums, but I'll bring it up internally as well. Would be worth commenting on the open openvr issue though, so we get more visibility on impact.
