### ISSUE TITLE
Scaling the Root Component of the Player During Runtime causes the hands to track to the original location instead of the scaled location

### ISSUE THREAD

**Issue by JamesNyeVRGuy** [ValveSoftware/steamvr_unreal_plugin#77]
How to reproduce. 

Download and install SteamVR input plugin to a project. 

During runtime change the world scale of the root capsule component to 3, your hands will track to their original non scaled location

Then instead of doing this during runtime; inside your character, change the root capsule component to 3, your hands will track to their scaled location. 

This is at least on Engine Version 4.21, 4.22, and 4.23

**Comment by 1runeberg** [comment]
Hi @PotatoFaceJames --

I tried replicating the issue using the following steps:

(1) Create a new UE VR Template
(2) Assign a button to scale the VR Origin by 3 on all axes
(3) Test behavior during runtime

Result: Transforms are scaled and is applied to all child components including MCs

(4) Enable SteamVR Input Plugin
(5) Restart Editor
(6) Double check all bindings have been generated and is registered in steamvr dashboard
(7) Test behavior during runtime

Result: Similar results as Steps 1-3

I'm using the vanilla UE template to ensure there is no animation code or custom scene component heirarchy that could be overriding or causing incorrect transforms during scaling.

If you are using the sample content and this is the actual behavior you want, you will need to apply a scale on anim update on the final transform (wrist/root). If you are not using the sample content, I suggest having a closer look at other nodes or functionality that may be overriding and ensure you apply the custom scale.

Feel free to also try the repro steps above on your end to verify.

**Comment by JamesNyeVRGuy** [comment]
I did another attempt to reproduce. While this time controller position was correct, any object attached to it stayed in the original scale and translation. 

I've gone back to my project and did a LOT more debugging to verify this is the case. 

Thanks for trying to reproduce it, it led me down this path to find something wrong with how my objects were attaching and scaling.

**Comment by 1runeberg** [comment]
no prob James! good luck!
