### ISSUE TITLE
Input.ini is still not properly managed in shipping configuration

### ISSUE THREAD

**Issue by curs0** [ValveSoftware/steamvr_unreal_plugin#85]
Let's say you deployed a shipping build with some defined bindings. 
Running your game for the first time, a new file will be created by the engine (4.23.x) under:

%USERPROFILE%\AppData\Local\[yourgame]\Saved\Config\WindowsNoEditor\Input.ini
(storing your default bindings)

Now, let's say you want to deploy a new build changing previous bindings: 
you're supposed to ship a new build with a new Input.ini file, but when an old user will start it, the old existing Input.ini file won't be updated with new bindings and the engine will just ignore the new, packaged, Input.ini configuration.

In fact Input.ini is never regenerated with new packaged bindings, until user manually deletes it.

The issue was reported before in #67 but closed as not being related to SteamVR Input.
Without any proper workaround, this issue makes this plugin unreliable.
I think this should at least be highlighted in plugin wiki.
thanks & br

**Comment by 1runeberg** [comment]
Hi @curs0 - thanks for the feedback, we'll add notes in our guide. I do not understand what you mean by workaround, as there is no technical issue here.

This is more an engine usage scenario and is true for any ue project, vr or not that decides to change default bindings across shipping builds (e.g. adding new actions, renames, etc)- the game developers have the responsibility to clear or update the user-specific Input.ini on their project/game code as it involves user-data, we cannot blanketly update these settings for your end users. 

As each game/project is different and can have different use cases for the user-specific Input.ini,  you have to add the appropriate code yourself that makes sense for your specific game/project. 

I suggest bringing this to the attention of Epic Games however, to request perhaps providing BP nodes to make it easier for game developers to do so, as we do not have any control over core Engine architecture/features.

**Comment by curs0** [comment]
Fair enough but please highlight this behavior in plugin notes.
As a temporary quick&dirty workaround, we're deleting the original input.ini file on game shutdown.

**Comment by 1runeberg** [comment]
Thanks. In saying all this, as this is a fairly common question with any UE Project that adds new Actions for example in a succesive shipping build, I did bring this up with Epic Games before to ask for their recommendation, and they have recommended as best practice to merge the DefaultInput.ini with the new actions with the user-specific Input.ini, or if appropriate, simply delete the Input.ini as what you are doing now.

But perhaps with enough user feedback, they might make more facilities in the engine to make this simpler. I believe there are plugins created just for doing this, but not sure how updated they are.

We may consider adding a convenience BP node for a simple config wipe in future versions, but this functionality imo, really shouldnt be a SteamVR plugin provided convenience node, but rather an engine wide one.

**Comment by 1runeberg** [comment]
@curs0 - Added a convenience node in develop-4.21/4.22/4.23 branches which delete the user's Input.ini file (use with caution):

![image](https://user-images.githubusercontent.com/17371351/68645061-01ea6700-056b-11ea-9b92-922e6ce39836.png)
