### ISSUE TITLE
UE 4.23.1 Vive Trackers not working with the plugin enabled

### ISSUE THREAD

**Issue by SlothfulAlly** [ValveSoftware/steamvr_unreal_plugin#89]
Hi, for some reason the vive trackers don't track in UE4 whenever I enable the plugin in the project. The trackers show up correctly in SteamVR but doesn't reflect anything in UE4. Disabling the plugin makes them work as they should.
Is there some kind of setup required for the trackers to work correctly with the plugin? I couldn't find any documentation or anything related to it anywhere.

**Comment by 1runeberg** [comment]
Hi @DopeEnemy 

There's no auto-generation of bindings for Vive Trackers at the moment with the plugin, it has to be done via SteamVR. The plugin does recognize trackers though (poses), here're some steps to get you started:

**Configuration (UE):**

1. Attach a motioncontroller component in an actor 
2. Set Source to Special1/2/3/... etc

**Configuration (SteamVR):**

1. In the dashboard, switch to Vive Tracker
2. Select Manage Trackers
3. Assign tracker to one of the available roles (e.g. Waist)
4. Select Vive tracker {Role} in the button beside the "MANAGE TRACKERS"
5. Click Create New Binding
6. Assign an action to power button (e.g. Open Console)
7. Click Edit Action Poses
8. Assign Special 1 to pose slot (same special slot in UE Configuration step 2)
9. Save this binding

**Comment by 1runeberg** [comment]
Further, GitHub branches develop-4.19 to develop-4.23 now have better support for trackers.

New MotionSources are now exposed and recognised by the plugin:

![image](https://user-images.githubusercontent.com/17371351/70084192-fcf86f00-1661-11ea-8f26-8eee9228c2cb.png)

Json Tracker bindings that have been pre-mapped to appropriate actions will be generated by the plugin based on these motion sources
All you need to do is to configure your individual trackers to their roles in the dashboard:

![image](https://user-images.githubusercontent.com/17371351/70084229-0c77b800-1662-11ea-8263-2f278cbed931.png)

Everything else should be pre-configured for you (poses)

**NOTE 1:** 
_Migrating to the new tracker support:_
(a) Backup your vive_tracker_xxx.json files in your Config\SteamVRBindings folder
(b) Delete any vive_tracker_xxx.json files in Config\SteamVRBindings folder
(c) Restart editor or Regenerate Controller Bindings

**NOTE2:**
There are no default render models for the new Motion Sources so you would have to attach a custom static mesh (use "custom" setting in drop down) to visualize it.  Will open an Engine PR for this once everything is finalised.

**Comment by SlothfulAlly** [comment]
Hi, sorry for such a late reply, I followed your steps and set up the tracker's pose to Special_1 in SteamVR as well as mapped my motion controller to Special_1 in the project and then restarted the editor along with regenerating controller binding but the tracker still doesn't work for some reason. I tried getting it to work in 4.24 (with the plugin now integrated inside the engine) but unfortunately, the result was the same. The trackers just won't work (I've tried it with 3 different trackers but none of them work).

**Comment by 1runeberg** [comment]
Hi @DopeEnemy have you tried the version in develop-4.23? (see my last post) 

Also, did you manage to assign the correct poses in the steamvr dashboard (steps 4 to 8)?

Can you send some Screenshots please of the config made in SteamVR? 

Thanks.

**Comment by SlothfulAlly** [comment]
Hi, the trackers started working by following your steps after updating SteamVR to 1.9.15 version. I followed your steps and setup the exact same way before but the trackers refused to work. Either way, they're working properly now. Thank you very much for the assistance.
