### ISSUE TITLE
Strange rotation snapping when moving controllers around with plugin active

### ISSUE THREAD

**Issue by MisterGenius0** [ValveSoftware/steamvr_unreal_plugin#90]
[Youtube Video Of the issue](https://youtu.be/06O8mp_3F3c)

When I install this plugin on the default VR starter project in unreal 4.23 I get strange rotation snapping but when I disable or remove the plugin the rotation works normally 

I have the Vive controllers and Vive headset

**Comment by 1runeberg** [comment]
Hi @MisterGenius0 - Which version of Visual Studio are you on at the moment?

**Comment by MisterGenius0** [comment]
Im on Visual Studio Community 2019 Version: 16.3.8

**Comment by 1runeberg** [comment]
Please check Issue #79 - There is a known issue with Unreal Engine maths and a recent Microsoft patch update of VS 2019.  The plugin uses unreal engine provided-math functions and is therefore affected.

You will need to downgrade your C++ compiler, or use VS2017.
