### ISSUE TITLE
Oculus Rift S no longer detected/working

### ISSUE THREAD

**Issue by nathanjedwards** [ValveSoftware/steamvr_unreal_plugin#92]
I'm not sure if this is a problem with the latest SteamVR 1.8.20 update or a problem with the openvr sdk, or this plugin, but the Oculus Rift S no longer works with SteamVR Input. 

The SteamVR input bindings dashboard no longer launches from the editor i.e. it doesn't even open up the browser. When I attach the debugger in code I see that InitSteamVRSystem never successfully loads the device. 

Any bindings that I have setup for the Rift no longer work. 

Engine version 4.19 (I have also tried 4.22 without any luck)
Oculus firmware 2.0.0
SteamVR 1.8.20

**Comment by 1runeberg** [comment]
Hi @nathanjedwards - can you let me know please what version of the plugin you are using as well as whether it is from the Marketplace or not?

**Comment by nathanjedwards** [comment]
Version 1.51-sdk 1.5.17.  It isn't from the marketplace. 

Although I did try it with 4.22.3 and the plugin from the marketplace and had the same issue.

**Comment by 1runeberg** [comment]
thanks. are you able to try a source code version of the plugin? the code in the develop-4.19 should help with the dashboard issue, though I'm yet unsure what the issue is with the Rift S.

**Comment by nathanjedwards** [comment]
I tried a build from source. I still can't launch the dashboard with the Rift S. I can now with the Index and Vive so at least it works again for those devices. 

I think the dashboard not launching for the Rift S is a symptom of the device not being properly loaded/detected by the plugin. When USteamVRInputDeviceFunctionLibrary::ShowBindingsUI is called no device is loaded so it doesn't do anything.

FSteamVRInputDevice::InitSteamVRSystem() never successfully detects/inits the device. 

That makes me wonder if it is something in openvr has changed and that is the problem but I'm not sure.

**Comment by 1runeberg** [comment]
Hi @nathanjedwards - Sorry it took a while to get back to you on this.

I've just tested using UE4.23, SteamVR 1.8.20 and the latest code in develop-4.23:
https://github.com/ValveSoftware/steamvr_unreal_plugin/tree/develop-4.23

I'm not having any issues with the Rift S. It did ask for a Firmware Update though for boththe HMD and Controllers - can you double-check on your end if you have the latest Oculus firmware installed and then try with the latest code in our GitHub branch (see link above).

**Comment by nathanjedwards** [comment]
Hi @1runeberg 

I think I finally figured it out. Unreal Engine includes an OculusVR plugin that is enabled by default. It seems like with the latest update of Oculus the Rift S now uses that plugin by default. So SteamVR is never used and is not needed if that plugin is enabled.

If I disable the OculusVR plugin everything works again. 

Thanks for your help.

**Comment by 1runeberg** [comment]
Thanks @nathanjedwards - Just a couple of notes for others who might find this ticket in the future and is on a similar predicament.

Oculus does have a higher default platform priority than SteamVR in the Engine, so when both plugins are enabled, Oculus normally takes over input when an Oculus Hardware is present. Surprised that you only encountered this on a runtime upgrade.

This behavior can be overridden in Engine.ini or more easily, as you found, by disabling the Oculus plugin for builds and editor sessions while working with SteamVR.

Glad you got it all sorted!
