### ISSUE TITLE
Issue on Shipped Game

### ISSUE THREAD

**Issue by gradgr** [ValveSoftware/steamvr_unreal_plugin#93]
Hello my game, although shipped on Oculus SDK, today i pushed an update for Oper VR only using the github 4.23 plugin. On packaged it seems to work just fine, but now after pushed online, users report "it tells me that the controls are not suitable for this game and does not let me play." 

what should i do? also i cannot set the action manifest to work. Even on my end i get couldnt find action manifest on controller setting window. Can you please provide more info?

I switched to : This game uses legacy input and has controller-specific bindings.
instead of This game uses the SteamVR Input system and an action manifest file. 
And it seems to work on rift, but still doesnt know how people may change controls if stick into this solution or even if this works on other headsets.

The title is  https://store.steampowered.com/app/1172060/Rest_In_Pieces/

**Comment by 1runeberg** [comment]
Hi @gradgr - Thanks for reporting this. Can you confirm if your packaged game has the Oculus Plugin (from the Engine) also enabled?

Also, for 4.23, you should be using the develop-4.23 branch of the plugin for shipped builds:
https://github.com/ValveSoftware/steamvr_unreal_plugin/tree/develop-4.23

As it has a workaround for a known engine issues that got introduced with UE 4.23.

We are hoping to get the updated plugins in the Marketplace as well soon.

**Comment by gradgr** [comment]
@1runeberg i have disabled the plugin also unchecked it from steamworks and have only open vr. The Steam Input Plugin is from develop 4.23, the marketplace plugin wouldnt work. Can you please check it ? should i provide you a key to the title?

**Comment by 1runeberg** [comment]
@gradgr  - can you send me an email at: runeb@valvesoftware.com with a SteamVR System Report while the game is running. I'll review that first and see if we need to look deeper. You may need to give me until tomorrow though to give a thorough response.

Cheers,
Rune

**Comment by gradgr** [comment]
Email sent. Ok mate thank you!

**Comment by pablonaj** [comment]
> 
> 
> Hi @gradgr - Thanks for reporting this. Can you confirm if your packaged game has the Oculus Plugin (from the Engine) also enabled?
> 
> Also, for 4.23, you should be using the develop-4.23 branch of the plugin for shipped builds:
> https://github.com/ValveSoftware/steamvr_unreal_plugin/tree/develop-4.23
> 
> As it has a workaround for a known engine issues that got introduced with UE 4.23.
> 
> We are hoping to get the updated plugins in the Marketplace as well soon.

Hi RuneBerg - any update on when the updated plugin will be released for 4.23?

And I think you said somewhere that 4.24 already has the latest plugin included, is this correct? And is the issue with the inputs also solved on that one?

Cheers,

Pablo

**Comment by 1runeberg** [comment]
@pablonaj - Marketplace plugin is just going through internal checks atm. will post an update here once it's submitted to Epic.

The integrated plugin in 4.24 doesn't require this workaround.

**Comment by pablonaj** [comment]
Thanks RuneBerg, sounds good.

Can I suggest you add a link to the plugin Youtube videos in the UE4 Marketplace or the wiki here? They are great but it took me a while to find them.

Cheers,

**Comment by 1runeberg** [comment]
@pablonaj - thanks! :) the videos are not official, and with the release we're doing today, some parts is a bit outdated now, so i cant link them. 

But will see how we can make official ones especially more info on the integrated 4.24 version.

The latest update of the plugin is now already up in GitHub:
https://github.com/ValveSoftware/steamvr_unreal_plugin/releases

Marketplace version updates also sent to Epic, hopefully up within a few days :)

**Comment by 1runeberg** [comment]
Closing for now, please reopen if you have any more questions on this. thanks.
