### ISSUE TITLE
UE 4.23.1 Build, SteamVR says Waiting and not works (Vive)

### ISSUE THREAD

**Issue by codingapevs** [ValveSoftware/steamvr_unreal_plugin#94]
Hello,
I'm working on a game. Everthing works perfectly in Editor.
But when I build the game and open it, Game window is opened and map is also opend but SteamVR says "waiting" on Vive screen. Because of this, nothing works. It is like, it is working in Selected Viewport Mode not in VR Preview.

I don't know, is there any other setting that I didn't check or enabled.

Thank you so much.

Murat Karakaş

**Comment by 1runeberg** [comment]
Hi Murat,

Did you set the game to "start in vr" (via the project settings) or use the "Enable HMD" node?

Also, for 4.23.1 - can you use the version of the plugin here please:
https://github.com/ValveSoftware/steamvr_unreal_plugin/tree/develop-4.23

Let me know hoe you go.

Cheers,
Rune

**Comment by codingapevs** [comment]
Sorry to bother you, I found that 5 minutes before you reply.
I didn't see that option on any tutorials or any documents. 

Thank you so much.

Murat
