### ISSUE TITLE
Input.ini Gets Modified Every Time The Project Is Reloaded

### ISSUE THREAD

**Issue by MisterGenius0** [ValveSoftware/steamvr_unreal_plugin#95]
Every time I reload the project with the plugin enabled the input.ini always gets modified makeing source control hard to manage

**Before the project is Loaded**
![Before Project](https://user-images.githubusercontent.com/39445650/69396975-14664e00-0c99-11ea-8e80-2b5327c9f050.png)

**After Project Is Loaded**

![After Open Project](https://user-images.githubusercontent.com/39445650/69396992-22b46a00-0c99-11ea-92a7-cc0345220674.png)

**Changes with the file (I did not do)**

![Changes](https://user-images.githubusercontent.com/39445650/69397012-3790fd80-0c99-11ea-8695-53e9b24ed567.png)

**Right Closeup**

![Remove up close](https://user-images.githubusercontent.com/39445650/69397043-5c857080-0c99-11ea-94f6-65698e1c3469.png)

**Left Closeup**

![Add upclose](https://user-images.githubusercontent.com/39445650/69397049-65764200-0c99-11ea-80b5-0a52b86d957d.png)

**Comment by 1runeberg** [comment]
Hi @MisterGenius0 

Thanks for reporting this.

It seems that for UE4.23, calls to UpdateDefaultConfigFile() does not appear to be behaving as expected (should only save any changes to input settings). 

Might be related to the seeming randomness on the way its capturing Axis properties from the UI. Entries appear accurate though regardless of the randomness in line entry sequence, so should be safe even in the case of accidentally committing changes in VC.

UE4.15-UE4.22 and upcoming UE4.24 does not exhibit this issue. 

As it may be unlikely that Epic will fix this with 4.24 release coming soon, so have made a workaround in the plugin, can you try the plugin code in develop and let me know how you go:

https://github.com/ValveSoftware/steamvr_unreal_plugin/tree/develop-4.23

**Comment by MisterGenius0** [comment]
looks like it works! Thanks for the quick workaround

**Comment by 1runeberg** [comment]
No prob! Let me know if you encounter any more issues with this.

Cheers,
Rune
