### ISSUE TITLE
Generic Input Mappings don't fire in BPs

### ISSUE THREAD

**Issue by Luis7a** [ValveSoftware/steamvr_unreal_plugin#98]
Using a Cosmos with UE 4.23.

Doing the input bindings and regenerating the .json files works fine. Does the plugin support calling an action by it's button name? For example, you used to be able to add an event for "Motion Controller (L) Trigger" without having to bind it. Can you not do that with the specific controller buttons?

![image](https://user-images.githubusercontent.com/11464596/70259267-15908400-174b-11ea-87f6-7fb6a88c5c5b.png)

The top execution fires and goes through, the bottom never fires.

**Comment by 1runeberg** [comment]
@Luis7a 
Yeah, the individual button key events are not supported with the SteamVR Input System (these events are actually disabled already in 4.24 for XR Keys/Controller to conform with the OpenXR specification).

You have to use Action events exclusively. The idea is to help ensure your app is as hardware agnostic as possible and you & your end users can easily remap keys to different actions without having to do any re-coding.

**Comment by Luis7a** [comment]
@1runeberg Will the events be disabled in the engine version of 4.24 or with the 4.24 version of the plugin? 

That makes sense, and will surely streamline the process. Was just looking for confirmation in order to avoid using those if they currently in use.

**Comment by 1runeberg** [comment]
No prob! Unfortunately theres no efficient way of disabling those events in engine versions prior to 4.24.

I'll add this to the FAQ im compiling.
