### ISSUE TITLE
4.24 ?

### ISSUE THREAD

**Issue by gradgr** [ValveSoftware/steamvr_unreal_plugin#99]
Until its released on marketplace could we dn it from github?

**Comment by 1runeberg** [comment]
Hi @gradgr - There appears to be an oversight in the Epic release notes, this line unfortunately didn't end up in the final version released to the public:

**"Integrated the SteamVR Input marketplace plugin into the SteamVR plugin""**

While we may release a separate 4.24 Marketplace version in the future, we've currently put the effort in the integration to 4.24, so you should have all the features of the Marketplace plugin already in 4.24 built-in, but do let us know if you have any issues.

**Comment by cafeoh** [comment]
Hi, piggy-backing on this issue: Where can I find the content of the plugin in 4.24? I do have the SteamVR Input button and all that, but I can't find the pawns, motion controller BPs and all anymore 😕 

@1runeberg Also for the future, I realize github's issue tracker is not meant for that, but how averse are you to "support" issue that don't actually point to a bug? It seems there's a lot of those around, so I'm just wondering.

**Comment by 1runeberg** [comment]
@cafeoh - Uploaded a version of the sample project for use with the Integrated version of the plugin here:

https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

You may need a third party decompression tool if you aren't using any yet (e.g. 7Zip, WinZip)

Questions on usage or problems with the plugin that may or may not be bugs are welcome :) The closed issues are also handy for searching prior issues and/or queries that may have already been answered.

**Comment by cafeoh** [comment]
@1runeberg Thanks a lot, that's exactly what I was looking for! 😄  (Still struggling with project architecture a bit and couldn't quite manage to take the content from the previous plugin and port it to the integrated version myself...)

**Comment by gradgr** [comment]
Trying to open a 4.23.1 Project already using SteamVR Input Plugin leads to Crash. Tried with and without the 4.23 compiled plugin folder. Is there a way to open older projects in 4.24 binary version?

EDIT : Deleting any steam vr input related file in /config , opened the project, inputs seems to be renamed in intergrated ver [Steam VR string infront missing, Also Cosmos Input missing] , so will try to re-map all and report if still there's an issue.

EDIT : Changing an input to new intergrated, will crash when Previewing in VR. To launch without crash, i had to remove old plugin mapping. What should i do with Cosmos setup? I guess i should just use Rift input as they are the same?

Thank you!

Assertion failed: Key.IsValid() [File:D:/Build/++UE4/Sync/Engine/Source/Runtime/Slate/Private/Framework/Application/SlateApplication.cpp] [Line: 5536]

UE4Editor_Core
UE4Editor_Core
UE4Editor_Slate
UE4Editor_SteamVRInputDevice
UE4Editor_SteamVRInputDevice
UE4Editor_ApplicationCore
UE4Editor_Slate
UE4Editor
UE4Editor
UE4Editor
UE4Editor
UE4Editor
kernel32
ntdll

**Comment by 1runeberg** [comment]
Hi @gradgr - yes, you'll need to remap keys as the key naming have been harmonised with the new engine OpenXR keys.

Normally, you shouldnt get a crash, but try backing up your DefaultInput.ini and delete it. Your project should also use Action events exclusively and not the controller button events as they have now been disabled in the Engine as per OpenXR spec.

Cosmos keys are available if you enable the integrated SteamVR Plugin, they should be in the controller list:
![image](https://user-images.githubusercontent.com/17371351/71204749-ff5ef800-22f4-11ea-9ff6-4ccb29140653.png)

**Comment by dustycoder** [comment]
I'm not seeing an update to the SteamVR Plugin (still 1.0 without an option to update). When I try to view plugin content there isn't anything there that resembles what was in the Input Plugin. Running UE 4.24.1

**Comment by 1runeberg** [comment]
Hi @dustycoder - The plugin has been integrated in the engine and is part of UE 4.24 so you shouldn't need the Marketplace plugin for this latest version of the engine.

We may release a separate 4.24 Marketplace version in the future, but for now, we've put the effort in the integration to 4.24 to make it easier for devs to use the new Input system.

We've also uploaded a version of the sample project for use with UE4.24 here or if you want/need the assets that came with the Marketplace plugin:

https://github.com/ValveSoftware/steamvr_unreal_plugin/wiki/sample/SteamVRInputPlugin_UEIntegrated.7z

(to decompress, you may need a third party tool if you aren't using any yet (e.g. 7Zip, WinZip))

**Comment by 1runeberg** [comment]
@gradgr - closing issue since plugin has been released as an integrated one in UE4.24 for a while now and we are now in Hotfix 3 :) 

let us know though if you have any further questions on this.
